import { ChecklistItemInteractionType, ChecklistItemType } from "@base/Shared/ChecklistSystem/ChecklistItem";
import { HondaJetChecklist, HondaJetChecklistCategory } from "../Checklist";

export enum HondaJetNormalChecklistNames {
  BEFORESTARTINGENGINES = "BEFORE STARTING ENGINES",
  STARTINGENGINES = "STARTING ENGINES",
  BEFORETAXI = "BEFORE TAXI",
  TAXI = "TAXI",
  BEFORETAKEOFF = "BEFORE TAKEOFF",
  AFTERTAKEOFF = "AFTER TAKEOFF",
  CLIMB = "CLIMB",
  CRUISE = "CRUISE",
  DESCENT = "DESCENT",
  APPROACH = "APPROACH",
  BEFORELANDING = "BEFORE LANDING",
  BALKEDLANDING = "BALKED LANDING",
  AFTERLANDING = "AFTER LANDING",
  SHUTDOWN = "SHUTDOWN",
  ENGINEDRYMOTOR = "ENGINE DRY MOTOR",
}

/** A utility class to generate Vision Jet Normal checklist data. */
export class HondaJetNormalChecklists {
  /**
   * Generates the Vision Jet Normal checklist data.
   * @returns An array of Vision Jet Normal checklists.
   **/
  public static getChecklists(): HondaJetChecklist[] {
    return [
      new HondaJetChecklist(HondaJetNormalChecklistNames.BEFORESTARTINGENGINES, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Challenge,
          content: "BATTERY",
          color: "white",
          fontSize: 12,
          response: "ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "OXYGEN",
          color: "white",
          fontSize: 12,
          response: "(Checked, ON and NORM)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "PRESSURIZATION",
          color: "white",
          fontSize: 12,
          response: "(NORM)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ELECTRICAL",
          color: "white",
          fontSize: 12,
          response: "(ON and NORM)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ELT",
          color: "white",
          fontSize: 12,
          response: "NORM",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "NOSE WHEEL STEERING",
          color: "white",
          fontSize: 12,
          response: "NORM",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "LANDING GEAR",
          color: "white",
          fontSize: 12,
          response: "DN",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ALTERNATE GEAR RELEASE Handle",
          color: "white",
          fontSize: 12,
          response: "Stowed (fully in)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "PARKING BRAKE",
          color: "white",
          fontSize: 12,
          response: "Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 12,
          response: "UP",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Thrust Levers",
          color: "white",
          fontSize: 12,
          response: "CUT OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SPEEDBRAKE<br>(if installed)",
          color: "white",
          fontSize: 12,
          response: "RET",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ICE PROTECTION",
          color: "white",
          fontSize: 12,
          response: "(NORM and OFF)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FUEL Panel",
          color: "white",
          fontSize: 12,
          response: "(NORM)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "TRIM Panel",
          color: "white",
          fontSize: 12,
          response: "(Checked, set and NORM)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "WINDSHIELD HEAT Panel",
          color: "white",
          fontSize: 12,
          response: "NORM",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "PNEUMATIC Panel",
          color: "white",
          fontSize: 12,
          response: "(NORM)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Glareshield Panels",
          color: "white",
          fontSize: 12,
          response: "(Dark)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Standby Instrument",
          color: "white",
          fontSize: 12,
          response: "Checked",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AVIONICS INITIALIZATION",
          color: "white",
          fontSize: 12,
          response: "(Complete)",
        },
      ]),
      new HondaJetChecklist(HondaJetNormalChecklistNames.STARTINGENGINES, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Challenge,
          content: "Passenger Briefing",
          color: "white",
          fontSize: 12,
          response: "Complete",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Rudder Pedals",
          color: "white",
          fontSize: 12,
          response: "Adjusted",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Seats, Safety Belts",
          color: "white",
          fontSize: 12,
          response: "Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Doors",
          color: "white",
          fontSize: 12,
          response: "Closed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "PARKING BRAKE",
          color: "white",
          fontSize: 12,
          response: "Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CAS Messages",
          color: "white",
          fontSize: 12,
          response: "Review",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ELEC VOLTS",
          color: "white",
          fontSize: 12,
          response: "23.5 Volts minimum",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Engines",
          color: "white",
          fontSize: 12,
          response: "(Start)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Engine Instruments",
          color: "white",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ENGINE ANTI-ICE",
          color: "white",
          fontSize: 12,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "External Power",
          color: "white",
          fontSize: 12,
          response: "Disconnect",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flight Controls",
          color: "white",
          fontSize: 12,
          response: "Free and correct",
        },
      ]),
      new HondaJetChecklist(HondaJetNormalChecklistNames.BEFORETAXI, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Challenge,
          content: "WING ANTI-ICE",
          color: "white",
          fontSize: 12,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Avionics / Flight Data",
          color: "white",
          fontSize: 12,
          response: "(Set/Entered)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Altimeters",
          color: "white",
          fontSize: 12,
          response:
            "Set BARO, verify altitude within 75 feet of the field elevation and agree within 75 feet of each other",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 12,
          response: "Set for takeoff",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SPEEDBRAKE<br>(if installed)",
          color: "white",
          fontSize: 12,
          response: "Checked then RET",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CABIN SIGNS",
          color: "white",
          fontSize: 12,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "PARKING BRAKE",
          color: "white",
          fontSize: 12,
          response: "Release",
        },
      ]),
      new HondaJetChecklist(HondaJetNormalChecklistNames.TAXI, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Challenge,
          content: "Brakes",
          color: "white",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Nosewheel Steering",
          color: "white",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flight Instruments",
          color: "white",
          fontSize: 12,
          response: "Check",
        },
      ]),
      new HondaJetChecklist(HondaJetNormalChecklistNames.BEFORETAKEOFF, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 12,
          response: "Set for takeoff",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Trims",
          color: "white",
          fontSize: 12,
          response: "Set for takeoff",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SPEEDBRAKE<br>(if installed)",
          color: "white",
          fontSize: 12,
          response: "RET",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CAS Messages",
          color: "white",
          fontSize: 12,
          response: "Review",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Navigation",
          color: "white",
          fontSize: 12,
          response: "Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flight Guidance",
          color: "white",
          fontSize: 12,
          response: "Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "TOLD Data",
          color: "white",
          fontSize: 12,
          response: "Confirmed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Takeoff Briefing",
          color: "white",
          fontSize: 12,
          response: "Complete",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Radar",
          color: "white",
          fontSize: 12,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ICE PROTECTION",
          color: "white",
          fontSize: 12,
          response: "(As required)",
        },
      ]),
      new HondaJetChecklist(HondaJetNormalChecklistNames.AFTERTAKEOFF, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Challenge,
          content: "LANDING GEAR",
          color: "white",
          fontSize: 12,
          response: "UP (Positive rate of climb)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Yaw Damper",
          color: "white",
          fontSize: 12,
          response: "Verify engaged",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 12,
          response: "UP (130 KIAS minimum)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Thrust Levers",
          color: "white",
          fontSize: 12,
          response: "MCT",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flight Guidance",
          color: "white",
          fontSize: 12,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ICE PROTECTION",
          color: "white",
          fontSize: 12,
          response: "(As required)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CABIN SIGNS",
          color: "white",
          fontSize: 12,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "WINDSHIELD HEAT",
          color: "white",
          fontSize: 12,
          response: "As required",
        },
      ]),
      new HondaJetChecklist(HondaJetNormalChecklistNames.CLIMB, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Challenge,
          content: "Pressurization",
          color: "white",
          fontSize: 12,
          response: "Checked",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Altimeters<br>(transition altitude)",
          color: "white",
          fontSize: 12,
          response: "Set STD",
          blanksBelow: 1,
        },
        {
          type: ChecklistItemType.Text,
          content: "PRIOR TO ENTERING RVSM AIRSPACE",
          color: "white",
          fontSize: 14,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flight Guidance",
          color: "white",
          fontSize: 12,
          response: "CPL to pilot flying,<br>select desired modes",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Autopilot",
          color: "white",
          fontSize: 12,
          response: "Engage",
        },
      ]),
      new HondaJetChecklist(HondaJetNormalChecklistNames.CRUISE, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Text,
          content: "WHEN IN RVSM AIRSPACE, ONCE PER HOUR",
          color: "white",
          fontSize: 14,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Altimeters / Altitude",
          color: "white",
          fontSize: 12,
          response: "Set /  Agree within 200 ft",
          blanksBelow: 1,
        },
        {
          type: ChecklistItemType.Text,
          content: "DURING ALL PHASES OF CRUISE FLIGHT",
          color: "white",
          fontSize: 14,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Systems",
          color: "white",
          fontSize: 12,
          response: "Monitor",
        },
      ]),
      new HondaJetChecklist(HondaJetNormalChecklistNames.DESCENT, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Challenge,
          content: "WINDSHIELD HEAT",
          color: "white",
          fontSize: 12,
          response: "NORM (passing 18,000 ft)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Landing Field Elevation",
          color: "white",
          fontSize: 12,
          response: "Verify set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ENGINE ANTI-ICE",
          color: "white",
          fontSize: 12,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Altimeters<br>(transition altitude)",
          color: "white",
          fontSize: 12,
          response: "Set",
        },
      ]),
      new HondaJetChecklist(HondaJetNormalChecklistNames.APPROACH, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Challenge,
          content: "Seats and Seat Belts",
          color: "white",
          fontSize: 12,
          response: "Adjusted and secure",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Passenger Briefing",
          color: "white",
          fontSize: 12,
          response: "Complete",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CABIN SIGNS",
          color: "white",
          fontSize: 12,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Avionics",
          color: "white",
          fontSize: 12,
          response: "Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Landing Data ",
          color: "white",
          fontSize: 12,
          response: "Set and confirmed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CAS Messages",
          color: "white",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Approach Briefing",
          color: "white",
          fontSize: 12,
          response: "Complete",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 12,
          response: "TO/APPR",
          blanksBelow: 1,
        },
      ]),
      new HondaJetChecklist(HondaJetNormalChecklistNames.BEFORELANDING, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Challenge,
          content: "LANDING GEAR",
          color: "white",
          fontSize: 12,
          response: "DN",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SPEEDBRAKE (if installed)",
          color: "white",
          fontSize: 12,
          response: "RET",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 12,
          response: "LDG<br>or TO/APPR (ice)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Airspeed",
          color: "white",
          fontSize: 12,
          response: "Vref",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Autopilot/Yaw Damper",
          color: "white",
          fontSize: 12,
          response: "Disengage",
          blanksBelow: 1,
        },
        {
          type: ChecklistItemType.Link,
          content: "AFTER LANDING Checklist",
          color: "cyan",
          fontSize: 15,
          linkTarget: {
            checklistName: HondaJetNormalChecklistNames.AFTERLANDING,
            checklistCategory: HondaJetChecklistCategory.Normal,
          },
        },
        {
          type: ChecklistItemType.Link,
          content: "BALKED LANDING Checklist",
          color: "cyan",
          fontSize: 15,
          linkTarget: {
            checklistName: HondaJetNormalChecklistNames.BALKEDLANDING,
            checklistCategory: HondaJetChecklistCategory.Normal,
          },
        },
      ]),
      new HondaJetChecklist(HondaJetNormalChecklistNames.BALKEDLANDING, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Challenge,
          content: "TO/GA",
          color: "white",
          fontSize: 12,
          response: "Press",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Thrust Levers",
          color: "white",
          fontSize: 12,
          response: "TO",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Airspeed",
          color: "white",
          fontSize: 12,
          response: "Maintain Vref",
          blanksBelow: 1,
        },
        {
          type: ChecklistItemType.Text,
          content: "WHEN CLEAR OF OBSTACLES",
          color: "white",
          fontSize: 14,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 12,
          response: "TO/APPR",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "LANDING GEAR",
          color: "white",
          fontSize: 12,
          response: "UP (positive rate of climb)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Yaw Damper",
          color: "white",
          fontSize: 12,
          response: "Engaged",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Airspeed",
          color: "white",
          fontSize: 12,
          response: "Maintain Vac",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 12,
          response: "UP (130 KIAS minimum)<br>or TO/APPR (ice)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Thrust Levers",
          color: "white",
          fontSize: 12,
          response: "MCT",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flight Guidance",
          color: "white",
          fontSize: 12,
          response: "As required",
        },
      ]),
      new HondaJetChecklist(HondaJetNormalChecklistNames.AFTERLANDING, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Challenge,
          content: "CABIN SIGNS",
          color: "white",
          fontSize: 12,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ENGINE ANTI-ICE",
          color: "white",
          fontSize: 12,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SPEEDBRAKE<br>(if installed)",
          color: "white",
          fontSize: 12,
          response: "RET",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 12,
          response: "UP  or TO/APPR (ice)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Trims",
          color: "white",
          fontSize: 12,
          response: "Set in green band",
        },
      ]),
      new HondaJetChecklist(HondaJetNormalChecklistNames.SHUTDOWN, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Challenge,
          content: "PARKING BRAKE",
          color: "white",
          fontSize: 12,
          response: "Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Wheel Chocks",
          color: "white",
          fontSize: 12,
          response: "Installed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ENGINE ANTI-ICE",
          color: "white",
          fontSize: 12,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "External Power",
          color: "white",
          fontSize: 12,
          response: "As desired",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Thrust Levers",
          color: "white",
          fontSize: 12,
          response: "CUT OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CABIN SIGNS",
          color: "white",
          fontSize: 12,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "OXYGEN SUPPLY",
          color: "white",
          fontSize: 12,
          response: "Pull off",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "PARKING BRAKE",
          color: "white",
          fontSize: 12,
          response: "Release",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "BATTERY",
          color: "white",
          fontSize: 12,
          response: "OFF",
          blanksBelow: 1,
        },
      ]),
      new HondaJetChecklist(HondaJetNormalChecklistNames.ENGINEDRYMOTOR, HondaJetChecklistCategory.Normal, [
        {
          type: ChecklistItemType.Text,
          content: "(Motoring the engine without introducing fuel is required.)",
          color: "white",
          fontSize: 14,
          blanksBelow: 1,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Thurst Lever<br>(affected engine)",
          color: "white",
          fontSize: 12,
          response: "CUT OFF",
        },
        {
          type: ChecklistItemType.Text,
          content: "NOTE: For dry motoring ensure the thrust lever remains in the CUT OFF position.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Engine START Switch<br>(affected engine)",
          color: "white",
          fontSize: 12,
          response: "Press",
        },
        {
          type: ChecklistItemType.Text,
          content: "NOTE: Ensure the duration of dry motoring doesn't exceed the starter duty cycle limitation.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Engine PUSH to DISC",
          color: "white",
          fontSize: 12,
          response: "Press",
        },
      ]),
    ];
  }
}
