import {
  ChecklistItemInteractionType,
  ChecklistItemType,
  Justification,
} from "@base/Shared/ChecklistSystem/ChecklistItem";
import { LongitudeChecklist, LongitudeChecklistCategory } from "../Checklist";

export enum LongitudeAbbrevProcChecklistNames {
  BeforeTakeoff = "Before Takeoff",
  AfterTakeoff = "After Takeoff",
  IceProtectionCheck = "Ice Protection Check",
  EngineDryMotor = "Engine Dry Motor",
}

/** A utility class to generate abbrev checklist data. */
export class LongitudeAbbrevChecklists {
  /**
   * Generates the abbrev checklist data.
   * @returns An array of abbrev checklists.
   **/
  public static getChecklists(): LongitudeChecklist[] {
    return [
      new LongitudeChecklist(LongitudeAbbrevProcChecklistNames.BeforeTakeoff, LongitudeChecklistCategory.AbbrevProc, [
        {
          type: ChecklistItemType.Text,
          content: "Cockpit Items",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Circuit Breakers",
          color: "silver",
          fontSize: 12,
          response: "In",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "STBY PWR Switch",
          color: "silver",
          fontSize: 12,
          response: "TEST/ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "BATT Buttons (both)",
          color: "silver",
          fontSize: 12,
          response: "ON, Check Volts",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EIS/CAS",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Smoke Goggles",
          color: "silver",
          fontSize: 12,
          response: "Stowed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Oxygen System",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Hydraulics Data",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "APU",
          color: "silver",
          fontSize: 12,
          response: "Start",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "External Power",
          color: "silver",
          fontSize: 12,
          response: "Disconnected",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Cockpit Controls",
          color: "silver",
          fontSize: 12,
          response: "Check/Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Trims (3)",
          color: "silver",
          fontSize: 12,
          response: "Check/Set",
        },
        {
          type: ChecklistItemType.Text,
          content:
            "Stab Trim Postiion - %MAC/Stab<br>____________________________________  <br>24%/-6.4    26%/-5.8   28%/-5.1    30%/-4.5<br>32%/-3.9    34%/-3.2   36%-40%/-2.6",
          color: "gray",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Initialization",
          color: "silver",
          fontSize: 12,
          response: "Complete",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Fuel Quantity and Balance",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Autopilot",
          color: "silver",
          fontSize: 12,
          response: "Engage/Disengage",
        },
        {
          type: ChecklistItemType.Text,
          content: "Takeoff Simplified Criteria",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content:
            "Static Takeoff, No Obstacles, Ice Protection OFF, <br>APR Auto, No Tailwind, Dry Rwy,<br>Press Alt at or below 3000 ft, <br>Ambient temp at or below 35 deg C, <br>Flaps 2, Rwy Grad 0% to -2%, <br>Max Brake Temp: <br>Before Taxi 150 deg C  <br>Before Takeoff 195 deg C <br>______________________________________<br>Weight         V1/VR/V2/VFTO         TFL       <br>24-28k,         99/103/117/185       (>4000)  <br>28-32k,       109/112/124/185       (>4700)  <br>32-33.5k     114/115/126/185       (>5000)  <br>33.5-36.5k  121/122/131/185       (>5800)  <br>36.5-39.5k  128/128/137/185       (>7100)",
          color: "gray",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "Before Start",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Parking Brake",
          color: "silver",
          fontSize: 12,
          response: "Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Wheel Chocks",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Cabin Door/Cabin Door Curtain",
          color: "silver",
          fontSize: 12,
          response: "Closed/Stowed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Passenger Briefing",
          color: "silver",
          fontSize: 12,
          response: "Complete",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Cabin Divider (if installed)",
          color: "silver",
          fontSize: 12,
          response: "Secured Open",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Seats, Pedals, Seat Belts",
          color: "silver",
          fontSize: 12,
          response: "Adjusted/Fastened",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SEAT BELTS Button",
          color: "silver",
          fontSize: 12,
          response: "ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EIS/CAS",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Text,
          content: "Starting Engines",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Throttles",
          color: "silver",
          fontSize: 12,
          response: "IDLE",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Engines",
          color: "silver",
          fontSize: 12,
          response: "Start",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EIS/CAS",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Text,
          content: "Before Taxi",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Wheel Chocks",
          color: "silver",
          fontSize: 12,
          response: "Removed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flight Controls",
          color: "silver",
          fontSize: 12,
          response: "Free and Correct",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Nosewheel Steering Disconnect",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Speedbrakes",
          color: "silver",
          fontSize: 12,
          response: "Check/Retracted",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "PTCU",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flight Instruments/Avionics",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Ice Protection",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Text,
          content: "Taxi",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Exterior Lights",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Brakes",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Nosewheel Steering",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Thrust Reversers",
          color: "silver",
          fontSize: 12,
          response: "Check, as Required/Stowed",
        },
        {
          type: ChecklistItemType.Text,
          content: "Before Takeoff",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flaps",
          color: "silver",
          fontSize: 12,
          response: "Set for Takeoff",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Speedbrakes",
          color: "silver",
          fontSize: 12,
          response: "Retracted",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Trims (3)",
          color: "silver",
          fontSize: 12,
          response: "Set for Takeoff",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Ice Protection",
          color: "silver",
          fontSize: 12,
          response: "Check, as Required*",
        },
        {
          type: ChecklistItemType.Link,
          content: "Ice Protection Check",
          color: "cyan",
          fontSize: 15,
          linkTarget: {
            checklistName: LongitudeAbbrevProcChecklistNames.IceProtectionCheck,
            checklistCategory: LongitudeChecklistCategory.AbbrevProc,
          },
          justification: Justification.Indent2,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "V Speeds",
          color: "silver",
          fontSize: 12,
          response: "Displayed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SPD Knob",
          color: "silver",
          fontSize: 12,
          response: "FMS",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Crew Briefing",
          color: "silver",
          fontSize: 12,
          response: "Complete",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Radar",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Text,
          content: "-  CLEARED FOR TAKEOFF -",
          color: "silver",
          fontSize: 15,
          justification: Justification.Center,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Control Lock",
          color: "silver",
          fontSize: 12,
          response: "Unlocked",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flight Controls",
          color: "silver",
          fontSize: 12,
          response: "Free",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Ice Protection",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Exterior Lights",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EIS/CAS",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
      ]),
      new LongitudeChecklist(LongitudeAbbrevProcChecklistNames.AfterTakeoff, LongitudeChecklistCategory.AbbrevProc, [
        {
          type: ChecklistItemType.Text,
          content: "After Takeoff/Climb",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Landing Gear",
          color: "silver",
          fontSize: 12,
          response: "Up",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flaps (at or above V2+20)",
          color: "silver",
          fontSize: 12,
          response: "Up",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Throttles",
          color: "silver",
          fontSize: 12,
          response: "CLB",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Ice Protection (above 400 ft AGL)",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Pressurization",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SEAT BELTS Button",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Altimeters (at transition altitude)",
          color: "silver",
          fontSize: 12,
          response: "Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Exterior Lights",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Text,
          content: "Descent",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Pressurization LDG ELEV",
          color: "silver",
          fontSize: 12,
          response: "Verify",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Altimeters (at transition level)",
          color: "silver",
          fontSize: 12,
          response: "Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Exterior Lights",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Text,
          content: "Landing Simplified Criteria",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content:
            "IDLE at 50 ft, Ice Protection Off, <br>Flaps: Approach - 2, Landing -FULL, <br>No Tailwind, Dry Rwy, Rwy Grad:-0.5% to 2%, <br>Rwy Length 4200 ft or longer, <br>Press Alt at or below 4000 ft, <br>Ambient Temp at or below 40 deg C<br>____________________________________<br>Weight     VAPP/VREF<br>23.5k       113/104<br>25.5k       118/108<br>27.5k       123/112<br>29.5k       128/116 <br>31.5k       133/121<br>33.5k       137/125",
          color: "gray",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "Approach",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Landing Data",
          color: "silver",
          fontSize: 12,
          response: "Confirm",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Ice Protection",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flight Instruments/Avionics",
          color: "silver",
          fontSize: 12,
          response: "Check/Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Crew Briefing",
          color: "silver",
          fontSize: 12,
          response: "Complete",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Passenger Briefing",
          color: "silver",
          fontSize: 12,
          response: "Complete",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Cabin Divider (if installed)",
          color: "silver",
          fontSize: 12,
          response: "Secured Open",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Cabin Door Curtain",
          color: "silver",
          fontSize: 12,
          response: "Stowed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Seats/Seat Belts",
          color: "silver",
          fontSize: 12,
          response: "Adjusted/Fastened",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SEAT BELTS Button",
          color: "silver",
          fontSize: 12,
          response: "ON",
        },
        {
          type: ChecklistItemType.Text,
          content: "Before Landing",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Landing Gear",
          color: "silver",
          fontSize: 12,
          response: "Down (3 Green)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flaps",
          color: "silver",
          fontSize: 12,
          response: "FULL",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Exterior Lights",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Speedbrakes",
          color: "silver",
          fontSize: 12,
          response: "Retracted",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EIS/CAS",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Autopilot",
          color: "silver",
          fontSize: 12,
          response: "Disengage",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Autothrottle (prior to 50 feet AGL)",
          color: "silver",
          fontSize: 12,
          response: "Disengage",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Airspeed",
          color: "silver",
          fontSize: 12,
          response: "VREF",
        },
        {
          type: ChecklistItemType.Text,
          content: "Go-Around",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "TO/GA Button",
          color: "silver",
          fontSize: 12,
          response: "Push",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Throttles",
          color: "silver",
          fontSize: 12,
          response: "TO",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Pitch Attitude",
          color: "silver",
          fontSize: 12,
          response: "7.5 deg Nose Up Initially",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flaps",
          color: "silver",
          fontSize: 12,
          response: "2",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Climb Speed",
          color: "silver",
          fontSize: 12,
          response: "VAPP (Minimum)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Landing Gear",
          color: "silver",
          fontSize: 12,
          response: "Up",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flaps (at or above VAPP + 10)",
          color: "silver",
          fontSize: 12,
          response: "Up",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SPD Knob",
          color: "silver",
          fontSize: 12,
          response: "FMS",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Throttles",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Text,
          content: "After Landing",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Thrust Reversers",
          color: "silver",
          fontSize: 12,
          response: "Stow",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flaps",
          color: "silver",
          fontSize: 12,
          response: "As Desired",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Ice Protection",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Exterior Lights",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Text,
          content: "Shutdown/Quick Turn",
          color: "gray",
          fontSize: 18,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Throttles",
          color: "silver",
          fontSize: 12,
          response: "IDLE",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Parking Brake",
          color: "silver",
          fontSize: 12,
          response: "Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Ice Protection",
          color: "silver",
          fontSize: 12,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ENGINE RUN/STOP Buttons",
          color: "silver",
          fontSize: 12,
          response: "STOP",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SEAT BELTS Button",
          color: "silver",
          fontSize: 12,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "APU",
          color: "silver",
          fontSize: 12,
          response: "Off",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EIS/CAS",
          color: "silver",
          fontSize: 12,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Main Batteries",
          color: "silver",
          fontSize: 12,
          response: "Connected",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "APU",
          color: "silver",
          fontSize: 12,
          response: "As Desired",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Turn-Around Time/ Brake Temps",
          color: "silver",
          fontSize: 12,
          response: "Consider",
        },
        {
          type: ChecklistItemType.Link,
          content: "Return to Cockpit Items (if Quick Turn)",
          color: "cyan",
          fontSize: 15,
          linkTarget: {
            checklistName: LongitudeAbbrevProcChecklistNames.BeforeTakeoff,
            checklistCategory: LongitudeChecklistCategory.AbbrevProc,
          },
          justification: Justification.Indent2,
        },
        {
          type: ChecklistItemType.Text,
          content: "- CONTINUE WITH SHUTDOWN -",
          color: "silver",
          fontSize: 15,
          justification: Justification.Center,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EMER LTS Switch",
          color: "silver",
          fontSize: 12,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "STBY PWR Switch",
          color: "silver",
          fontSize: 12,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "APU Knob",
          color: "silver",
          fontSize: 12,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Exterior Lights",
          color: "silver",
          fontSize: 12,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Control Lock",
          color: "silver",
          fontSize: 12,
          response: "As Required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "BATT Buttons (both)",
          color: "silver",
          fontSize: 12,
          response: "OFF",
        },
      ]),
      new LongitudeChecklist(
        LongitudeAbbrevProcChecklistNames.IceProtectionCheck,
        LongitudeChecklistCategory.AbbrevProc,
        [
          {
            type: ChecklistItemType.Text,
            content: "Ice Protection Check",
            color: "gray",
            fontSize: 18,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Throttles",
            color: "silver",
            fontSize: 12,
            response: "IDLE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Engine Ice Protection",
            color: "silver",
            fontSize: 12,
            response: "On/Verify CAS/Off",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Stab Ice Protection",
            color: "silver",
            fontSize: 12,
            response: "On/Verify CAS/Off",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "APU Bleed",
            color: "silver",
            fontSize: 12,
            response: "Off",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Engine HP Valves (Anti-ice Synoptic)",
            color: "silver",
            fontSize: 12,
            response: "Open",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Throttles",
            color: "silver",
            fontSize: 12,
            response: "Slowly Increase/Valve Close",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Wing Ice Protection",
            color: "silver",
            fontSize: 12,
            response: "On/Valves Open/Off",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Throttles",
            color: "silver",
            fontSize: 12,
            response: "Idle",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "APU Bleed",
            color: "silver",
            fontSize: 12,
            response: "As Desired",
          },
          {
            type: ChecklistItemType.Link,
            content: "Return to Abbreviated Procedures, Before Takeoff",
            color: "cyan",
            fontSize: 15,
            linkTarget: {
              checklistName: LongitudeAbbrevProcChecklistNames.BeforeTakeoff,
              checklistCategory: LongitudeChecklistCategory.AbbrevProc,
            },
          },
        ],
      ),
      new LongitudeChecklist(
        LongitudeAbbrevProcChecklistNames.EngineDryMotor,
        LongitudeChecklistCategory.AbbrevProc,
        [
          {
            type: ChecklistItemType.Text,
            content: "Engine Dry Motor",
            color: "gray",
            fontSize: 18,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Throttle",
            color: "silver",
            fontSize: 12,
            response: "IDLE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "ENGINE RUN/STOP Button",
            color: "silver",
            fontSize: 12,
            response: "STOP",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "ENGINE STARTER Button",
            color: "silver",
            fontSize: 12,
            response: "Push and Hold (>19% N2 or 15 seconds)",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Repeat for opposite engine.",
            color: "silver",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Next Start Attempt",
            color: "silver",
            fontSize: 12,
            response: "White ENG DRY MTR PROC L and/or R CAS Message Clears",
          },
        ],
        true,
      ),
    ];
  }
}
