import {
  ChecklistItemType,
  Justification,
  ChecklistItemInteractionType,
} from "@base/Shared/ChecklistSystem/ChecklistItem";
import { ChecklistFilePaths } from "@base/Shared";
import { TbmChecklist, TbmChecklistCategory } from "../Checklist";

export enum TbmNormalProceduresChecklistNames {
  InsideInspection = "Inside inspection",
  BeforeStartingEngine = "Before starting engine",
  Motoring = "Motoring (if residual ITT > 150°C)",
  EngineStart = "Engine start",
  AfterEngineStartWithGPU = "After engine start with GPU",
  AfterEngineStart = "After engine start",
  BeforeTaxiing = "Before taxiing",
  BeforeLineUp = "Before line up",
  NormalTakeoff = "Normal takeoff",
  ShortTakeoff = "Short takeoff",
  AfterTakeoff = "After takeoff",
  Climb = "Climb",
  Cruise = "Cruise",
  BeforeDescent = "Before descent",
  Approach = "Approach",
  FinalOrDownwind = "Final approach (in GS) or downwind leg (VMC)",
  ShortFinal = "Short final (≈ 500 ft)",
  RunwayClear = "Runway clear",
  Shutdown = "Shutdown",
}

/** A utility class to generate normal checklist data. */
export class TbmNormalChecklists {
  /**
   * Generates the normal checklist data.
   * @returns An array of normal checklists.
   **/
  public static getChecklists(): TbmChecklist[] {
    return [
      new TbmChecklist(TbmNormalProceduresChecklistNames.InsideInspection, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Text,
          content: "Initial inside inspection and outside inspection performed.",
          color: "white",
          fontSize: 18,
        },
        {
          type: ChecklistItemType.Text,
          content: "OXYGEN cylinder open.",
          color: "white",
          fontSize: 18,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Cabin door and pilot door, if installed",
          color: "white",
          fontSize: 15,
          response: "Closed / Locked",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Baggage",
          color: "white",
          fontSize: 15,
          response: "Stowed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EMERGENCY EXIT pin",
          color: "white",
          fontSize: 15,
          response: "Removed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Seat, pedals, harness",
          color: "white",
          fontSize: 15,
          response: "Adjust / Lock",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "PASSENGER OXYGEN",
          color: "white",
          fontSize: 15,
          response: "STBY",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "OXYGEN",
          color: "white",
          fontSize: 15,
          response: "ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Crew oxygen masks",
          color: "white",
          fontSize: 15,
          response: "Test",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EXT LIGHTS",
          color: "white",
          fontSize: 15,
          response: "All OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "INT LIGHTS",
          color: "white",
          fontSize: 15,
          response: "All OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Crash lever",
          color: "white",
          fontSize: 15,
          response: "Down",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "STARTER",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "IGNITION",
          color: "white",
          fontSize: 15,
          response: "AUTO",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AUX BP",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FUEL SEL",
          color: "white",
          fontSize: 15,
          response: "MAN",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AP / TRIMS",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "A/C",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SEATS HTRS MASTER",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CB LIGHTS",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "MICRO / MASK",
          color: "white",
          fontSize: 15,
          response: "MICRO / Guarded",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "DE ICE SYSTEM",
          color: "white",
          fontSize: 15,
          response: "All OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "INERT SEP",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "PARK BRAKE",
          color: "white",
          fontSize: 15,
          response: "Reset / ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "LANDING GEAR",
          color: "white",
          fontSize: 15,
          response: "DN",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "DUMP",
          color: "white",
          fontSize: 15,
          response: "NORM / Guarded",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "BLEED",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "HOT AIR FLOW",
          color: "white",
          fontSize: 15,
          response: "Fully turned to the right",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "MAN OVRD",
          color: "white",
          fontSize: 15,
          response: "Full backward (notched)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "THROTTLE",
          color: "white",
          fontSize: 15,
          response: "CUT OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FUEL TANK SELECTOR",
          color: "white",
          fontSize: 15,
          response: "Open / L or R",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ALTERNATE STATIC SOURCE",
          color: "white",
          fontSize: 15,
          response: "Pushed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EMERGENCY RAM AIR",
          color: "white",
          fontSize: 15,
          response: "Pushed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ESS BUS TIE",
          color: "white",
          fontSize: 15,
          response: "NORM / Guarded",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Breakers",
          color: "white",
          fontSize: 15,
          response: "All pushed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Landing gear emergency pump handle",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.BeforeStartingEngine, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Challenge,
          content: "Crash lever",
          color: "white",
          fontSize: 15,
          response: "Up",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ATIS",
          color: "white",
          fontSize: 15,
          response: "Copied",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Start clearance",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SOURCE",
          color: "white",
          fontSize: 15,
          response: "BATT or GPU",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "GENERATOR",
          color: "white",
          fontSize: 15,
          response: "MAIN",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "TEST",
          color: "white",
          fontSize: 15,
          response: "Press",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "LANDING GEAR LIGHTS / CHECK DOWN",
          color: "white",
          fontSize: 15,
          response: "Test",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "MFD",
          color: "white",
          fontSize: 15,
          response: "Initialize",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Fuel on board",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Residual ITT",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Link,
          content: "If residual ITT > 150°C, refer to Motoring procedure",
          color: "cyan",
          fontSize: 15,
          linkTarget: {
            checklistName: TbmNormalProceduresChecklistNames.Motoring,
            checklistCategory: TbmChecklistCategory.NormalProcedures,
          },
        },
        {
          type: ChecklistItemType.Challenge,
          content: "VOLTS : BATT > 24.5 V / GPU ~ 28 V",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CAS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.EngineStart, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Text,
          content:
            "< CAUTION ><br>After aborted engine starts, wait :<br>1 min / 5 min / 30 min before 2nd / 3rd / 4th new engine start.",
          color: "yellow",
          fontSize: 15,
          justification: Justification.Center,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "IGNITION",
          color: "white",
          fontSize: 15,
          response: "AUTO",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AUX BP",
          color: "white",
          fontSize: 15,
          response: "ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AUX BOOST PMP ON",
          color: "white",
          fontSize: 15,
          response: "Check ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Propeller area",
          color: "white",
          fontSize: 15,
          response: "Clear",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "STARTER",
          color: "white",
          fontSize: 15,
          response: "ON, 2 sec then OFF",
        },
        {
          type: ChecklistItemType.Text,
          content: "When Ng around 13 % :",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "THROTTLE",
          color: "white",
          fontSize: 15,
          response: "LO-IDLE",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ITT, Ng, OIL °C and OIL PSI",
          color: "white",
          fontSize: 15,
          response: "Monitor",
          imagePath: ChecklistFilePaths.ASSETS_PATH + "/max-engine-values.png",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Text,
          content: "When<br>- Ng > 50 % and,<br>- 1 minute max :",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Starter",
          color: "white",
          fontSize: 15,
          response: "Check OFF automatically",
          justification: Justification.Indent1,
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.AfterEngineStart, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Link,
          content: "If engine started with GPU, refer to After engine start with GPU procedure",
          color: "cyan",
          fontSize: 15,
          linkTarget: {
            checklistName: TbmNormalProceduresChecklistNames.AfterEngineStartWithGPU,
            checklistCategory: TbmChecklistCategory.NormalProcedures,
          },
        },
        {
          type: ChecklistItemType.Challenge,
          content: "THROTTLE",
          color: "white",
          fontSize: 15,
          response: "LO-IDLE ▶ Flight IDLE",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Ng",
          color: "white",
          fontSize: 15,
          response: "Check 70 % ± 2 %",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "OIL °C and OIL PSI",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AUX BP",
          color: "white",
          fontSize: 15,
          response: "AUTO",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FUEL SEL",
          color: "white",
          fontSize: 15,
          response: "AUTO",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SHIFT",
          color: "white",
          fontSize: 15,
          response: "Test",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AP / TRIMS",
          color: "white",
          fontSize: 15,
          response: "ON",
        },
        {
          type: ChecklistItemType.Text,
          content: "If BATT < 80 amps :",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "GENERATOR",
          color: "white",
          fontSize: 15,
          response: "ST-BY / Test",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "GENERATOR",
          color: "white",
          fontSize: 15,
          response: "MAIN",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CAS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "A/C",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SEATS HTRS MASTER",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "BLEED",
          color: "white",
          fontSize: 15,
          response: "AUTO or MAX DIFF",
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.BeforeTaxiing, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Challenge,
          content: "Stand-by instruments",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "DE ICE SYSTEM",
          color: "white",
          fontSize: 15,
          response: "Test",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "INERT SEP",
          color: "white",
          fontSize: 15,
          response: "ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Flight controls",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "TRIMS",
          color: "white",
          fontSize: 15,
          response: "Test",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 15,
          response: "UP",
        },
        {
          type: ChecklistItemType.Text,
          content: "MFD",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FPL",
          color: "white",
          fontSize: 15,
          response: "Set",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "LFE",
          color: "white",
          fontSize: 15,
          response: "Set / Check",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "WX RADAR",
          color: "white",
          fontSize: 15,
          response: "STBY",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "THROTTLE",
          color: "white",
          fontSize: 15,
          response: "Feather twice",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EIS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CAS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "TAXI lights",
          color: "white",
          fontSize: 15,
          response: "ON",
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.BeforeLineUp, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Challenge,
          content: "LDG lights",
          color: "white",
          fontSize: 15,
          response: "ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "NAV",
          color: "white",
          fontSize: 15,
          response: "ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "STROBE",
          color: "white",
          fontSize: 15,
          response: "ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "IGNITION",
          color: "white",
          fontSize: 15,
          response: "As required, AUTO or ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AUX BP",
          color: "white",
          fontSize: 15,
          response: "AUTO",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FUEL SEL",
          color: "white",
          fontSize: 15,
          response: "AUTO",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "DE ICE SYSTEM",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "PITOT L HTR / PITOT R & STALL HTR",
          color: "white",
          fontSize: 15,
          response: "ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "INERT SEP",
          color: "white",
          fontSize: 15,
          response: "ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "TRIMS",
          color: "white",
          fontSize: 15,
          response: "TO",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 15,
          response: "TO",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "A/C",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "BLEED",
          color: "white",
          fontSize: 15,
          response: "AUTO or MAX DIFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "LFE",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FUEL gages",
          color: "white",
          fontSize: 15,
          response: "Check imbalance",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "BATT",
          color: "white",
          fontSize: 15,
          response: "Check below 50 amps",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EIS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CAS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Altimeters setting",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Instruments departure setting",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SID (PROC)",
          color: "white",
          fontSize: 15,
          response: "Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "ALT SEL",
          color: "white",
          fontSize: 15,
          response: "Set",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "XPDR squawk",
          color: "white",
          fontSize: 15,
          response: "Set",
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.NormalTakeoff, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Challenge,
          content: "ADI, HSI, headings",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "PROP RPM",
          color: "white",
          fontSize: 15,
          response: "Green sector",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Brakes",
          color: "white",
          fontSize: 15,
          response: "Release",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "TRQ",
          color: "white",
          fontSize: 15,
          response: "100 %",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Rotation airspeed",
          color: "white",
          fontSize: 15,
          imagePath: ChecklistFilePaths.ASSETS_PATH + "/rotation-airspeed.png",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Attitude",
          color: "white",
          fontSize: 15,
          response: "10° Up",
        },
        {
          type: ChecklistItemType.Text,
          content: "When vertical speed is positive :",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Brakes",
          color: "white",
          fontSize: 15,
          response: "Apply",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "LANDING GEAR",
          color: "white",
          fontSize: 15,
          response: "UP",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Text,
          content: "When airspeed above 115 KIAS :",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 15,
          response: "UP",
          justification: Justification.Indent1,
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.AfterTakeoff, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Challenge,
          content: "LANDING GEAR",
          color: "white",
          fontSize: 15,
          response: "Check UP",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 15,
          response: "Check UP",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "TRQ",
          color: "white",
          fontSize: 15,
          response: "Check max 100 %",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EIS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CAS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "DE ICE SYSTEM",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "INERT SEP",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.Climb, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Challenge,
          content: "ALT SEL",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Altimeters setting",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Autopilot",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "TRQ adjustment / ITT / Ng",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EIS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CAS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "WX RADAR",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Pressurization",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FUEL gages",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AMPS / VOLTS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "DE ICE SYSTEM",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "INERT SEP",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "LDG lights",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.Cruise, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Challenge,
          content: "Altimeters setting",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Autopilot",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "TRQ adjustment / ITT / Ng",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EIS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "CAS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Pressurization",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FUEL gages",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AMPS / VOLTS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "DE ICE SYSTEM",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "INERT SEP",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "LDG lights",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Top of descent",
          color: "white",
          fontSize: 15,
          response: "Computed",
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.BeforeDescent, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Challenge,
          content: "Briefing before approach",
          color: "white",
          fontSize: 15,
          response: "Completed",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Altimeters setting",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Pressurization",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "LFE",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FUEL gages",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AMPS / VOLTS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "DE ICE SYSTEM",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "INERT SEP",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.Approach, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Challenge,
          content: "Altimeters setting (QNH)",
          color: "white",
          fontSize: 15,
          response: "Set / Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Minimums",
          color: "white",
          fontSize: 15,
          response: "Set / Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "COM / NAV / GPS",
          color: "white",
          fontSize: 15,
          response: "Set / Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Pressurization",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "LFE",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FUEL gages",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AMPS / VOLTS",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "DE ICE SYSTEM",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "INERT SEP",
          color: "white",
          fontSize: 15,
          response: "ON",
        },
        {
          type: ChecklistItemType.Text,
          content: "Below FL 100 :",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "LDG lights",
          color: "white",
          fontSize: 15,
          response: "ON",
          justification: Justification.Indent1,
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.FinalOrDownwind, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Challenge,
          content: "LDG lights",
          color: "white",
          fontSize: 15,
          response: "ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "LANDING GEAR",
          color: "white",
          fontSize: 15,
          response: "DN, check 3 green",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 15,
          response: "TO",
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.ShortFinal, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Challenge,
          content: "LANDING GEAR",
          color: "white",
          fontSize: 15,
          response: "Check, DN and 3 green",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 15,
          response: "LDG",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AP / YD",
          color: "white",
          fontSize: 15,
          response: "Disconnect",
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.RunwayClear, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Challenge,
          content: "TAXI light",
          color: "white",
          fontSize: 15,
          response: "ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "NAV",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "STROBE",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "DE ICE SYSTEM",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "TRIMS",
          color: "white",
          fontSize: 15,
          response: "Reset to TO",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FLAPS",
          color: "white",
          fontSize: 15,
          response: "UP",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "A/C",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "XPDR",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "WX RADAR",
          color: "white",
          fontSize: 15,
          response: "Check",
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.Shutdown, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Challenge,
          content: "PARK BRAKE",
          color: "white",
          fontSize: 15,
          response: "Set / ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "EXT LIGHTS",
          color: "white",
          fontSize: 15,
          response: "All OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "INT LIGHTS",
          color: "white",
          fontSize: 15,
          response: "As required",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "OXYGEN",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "FUEL SEL",
          color: "white",
          fontSize: 15,
          response: "MAN",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AP / TRIMS",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "A/C",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SEATS HTRS MASTER",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "BLEED",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "THROTTLE",
          color: "white",
          fontSize: 15,
          response: "Flight IDLE for 2 min",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "THROTTLE",
          color: "white",
          fontSize: 15,
          response: "LO-IDLE for 15 sec",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "THROTTLE",
          color: "white",
          fontSize: 15,
          response: "CUT OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "INERT SEP",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AUX BOOST PMP ON",
          color: "white",
          fontSize: 15,
          response: "Check ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AUX BP",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "GENERATOR",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Text,
          content: "When inertial separator is retracted, after approximately 40 sec :",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "SOURCE",
          color: "white",
          fontSize: 15,
          response: "OFF",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Crash lever",
          color: "white",
          fontSize: 15,
          response: "Pull down",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Stand-by instruments",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Oxygen cylinder (right wing fairing)",
          color: "white",
          fontSize: 15,
          response: "Close",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Install air inlet and static port plugs, and exhaust and pitot covers.",
          color: "white",
          fontSize: 15,
        },
        {
          type: ChecklistItemType.Text,
          content: "< NOTE ><br>Be careful of exhaust stubs temperature before installing covers.",
          color: "white",
          fontSize: 15,
          justification: Justification.Center,
        },
        {
          type: ChecklistItemType.Text,
          content: "< NOTE ><br>15 to 20 minutes after the engine shutdown, check engine oil level.",
          color: "white",
          fontSize: 15,
          justification: Justification.Center,
        },
      ]),
      new TbmChecklist(TbmNormalProceduresChecklistNames.Motoring, TbmChecklistCategory.NormalProcedures, [
        {
          type: ChecklistItemType.Challenge,
          content: "IGNITION",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AUX BP",
          color: "white",
          fontSize: 15,
          response: "ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AUX BOOST PMP ON",
          color: "white",
          fontSize: 15,
          response: "Check ON",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "Propeller area",
          color: "white",
          fontSize: 15,
          response: "Clear",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "STARTER",
          color: "white",
          fontSize: 15,
          response: "ON, 2 sec then OFF",
        },
        {
          type: ChecklistItemType.Text,
          content: "After 30 seconds maximum :",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "STARTER",
          color: "white",
          fontSize: 15,
          response: "ABORT, then OFF",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "AUX BP",
          color: "white",
          fontSize: 15,
          response: "OFF",
        },
        {
          type: ChecklistItemType.Link,
          content: "Return to Before starting engine procedure",
          color: "cyan",
          fontSize: 15,
          linkTarget: {
            checklistName: TbmNormalProceduresChecklistNames.BeforeStartingEngine,
            checklistCategory: TbmChecklistCategory.NormalProcedures,
          },
        },
      ]),
      new TbmChecklist(
        TbmNormalProceduresChecklistNames.AfterEngineStartWithGPU,
        TbmChecklistCategory.NormalProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "SOURCE",
            color: "white",
            fontSize: 15,
            response: "BATT",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "GPU",
            color: "white",
            fontSize: 15,
            response: "Disconnect",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "GPU DOOR",
            color: "white",
            fontSize: 15,
            response: "Check OFF",
          },
          {
            type: ChecklistItemType.Link,
            content: "Return to After engine start procedure",
            color: "cyan",
            fontSize: 15,
            linkTarget: {
              checklistName: TbmNormalProceduresChecklistNames.AfterEngineStart,
              checklistCategory: TbmChecklistCategory.NormalProcedures,
            },
          },
        ],
      ),
      new TbmChecklist(
        TbmNormalProceduresChecklistNames.ShortTakeoff,
        TbmChecklistCategory.NormalProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "ADI, HSI, headings",
            color: "white",
            fontSize: 15,
            response: "Check",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "PROP RPM",
            color: "white",
            fontSize: 15,
            response: "Green sector",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "TRQ",
            color: "white",
            fontSize: 15,
            response: "100 %",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Brakes",
            color: "white",
            fontSize: 15,
            response: "Release",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Rotation airspeed",
            color: "white",
            fontSize: 15,
            imagePath: ChecklistFilePaths.ASSETS_PATH + "/rotation-airspeed.png",
          },
          {
            type: ChecklistItemType.Text,
            content: "Weight < 6579 lbs (2984 kg) :",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Attitude",
            color: "white",
            fontSize: 15,
            response: "15° Up",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Weight > 6579 lbs (2984 kg) :",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Attitude",
            color: "white",
            fontSize: 15,
            response: "12.5° Up",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "When vertical speed is positive :",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Brakes",
            color: "white",
            fontSize: 15,
            response: "Apply",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "LANDING GEAR",
            color: "white",
            fontSize: 15,
            response: "UP",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "When airspeed above 115 KIAS :",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "FLAPS",
            color: "white",
            fontSize: 15,
            response: "UP",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Link,
            content: "Continue with After takeoff procedure",
            color: "cyan",
            fontSize: 15,
            linkTarget: {
              checklistName: TbmNormalProceduresChecklistNames.AfterTakeoff,
              checklistCategory: TbmChecklistCategory.NormalProcedures,
            },
          },
        ],
        true,
      ),
    ];
  }
}
