import {
  ChecklistItemInteractionType,
  ChecklistItemType,
  Justification,
} from "@base/Shared/ChecklistSystem/ChecklistItem";
import { VisionJetChecklist, VisionJetChecklistCategory } from "../Checklist";
import { VisionJetWarningChecklistNames } from "../Checklists/VisionJetWarningChecklist";

export enum VisionJetEmergencyProceduresChecklistNames {
  AbnormalEngineStart = "Abnormal Engine Start",
  AFCSAlerts = "AFCS Alerts",
  AirspeedsforEmergencyOperations = "Airspeeds for Emergency Operations",
  AirStart = "Air Start",
  AutomaticFlightControlMalfunctionStickPusherESPUSPAutopilot = "Automatic Flight Control Malfunction (Stick Pusher, ESP, USP, Autopilot)",
  BestGlideSpeed = "Best Glide Speed",
  CabinFireInFlight = "Cabin Fire In Flight",
  CAPSActivation = "CAPS Activation",
  Ditching = "Ditching",
  EmergencyDescent = "Emergency Descent",
  EmergencyGroundEgress = "Emergency Ground Egress",
  EmergencyLandingwoPower = "Emergency Landing w/o Power",
  EngineEmergencyOnTakeoffSpeedBelowVR = "Engine Emergency On Takeoff - Speed Below VR",
  EngineFailureInFlight = "Engine Failure In Flight",
  EngineFailureOnTakeoffLowAltitude = "Engine Failure On Takeoff - Low Altitude",
  EngineFireOnTakeoffLowAltitude = "Engine Fire On Takeoff - Low Altitude",
  FlameoutPrecautionaryApproach = "Flameout / Precautionary Approach",
  JammedElevatorTrimTab = "Jammed Elevator Trim Tab",
  LandingWithoutAileronControl = "Landing Without Aileron Control",
  LandingWithoutElevatorControl = "Landing Without Elevator Control",
  LandingWithoutRudderControl = "Landing Without Rudder Control",
  LossofAllFlightDisplays = "Loss of All Flight Displays",
  LossofReliableAirspeedIndication = "Loss of Reliable Airspeed Indication",
  LossofThrustControl = "Loss of Thrust Control",
  PitchTrimRunawayFailure = "Pitch Trim Runaway / Failure",
  RejectedTakeoff = "Rejected Takeoff",
  RollTrimRunawayFailure = "Roll Trim Runaway / Failure",
  SmokeRemoval = "Smoke Removal",
  UncontainedEngineFailureRotorBurstinFlight = "Uncontained Engine Failure (Rotor Burst in Flight)",
}

/** A utility class to generate Vision Jet Emergency checklist data. */
export class VisionJetEmergencyProceduresChecklists {
  /**
   * Generates the Vision Jet Emergency checklist data.
   * @returns An array of Vision Jet Emergency checklists.
   **/
  public static getChecklists(): VisionJetChecklist[] {
    return [
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.AbnormalEngineStart,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Engine Knob",
            color: "white",
            fontSize: 12,
            response: "OFF",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Engine Button",
            color: "white",
            fontSize: 12,
            response: "PRESS AND HOLD 15 - 30 SECONDS",
          },
          {
            type: ChecklistItemType.Challenge,
            content:
              '3. See Section 2: Limitations, "Powerplant Limitations" and Section 2:Limitations, "Outside Air Temperature Limits" in for corrective actions.',
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.AFCSAlerts,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "For more information on AFCS alerts, refer to SF50 Garmin Cockpit Reference Guide.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.AirspeedsforEmergencyOperations,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "Maneuvering Speed:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "6000 lb (2721 kg)",
            color: "white",
            fontSize: 12,
            response: "150 KIAS",
          },
          {
            type: ChecklistItemType.Text,
            content: "Emergency Landing:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Flaps UP",
            color: "white",
            fontSize: 12,
            response: "100 KIAS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Flaps 50%",
            color: "white",
            fontSize: 12,
            response: "95 KIAS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "Flaps 100%",
            color: "white",
            fontSize: 12,
            response: "90 KIAS",
          },
          {
            type: ChecklistItemType.Text,
            content: "Best Glide (Gear and Flaps: UP):",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "6000 lb (2721 kg)",
            color: "white",
            fontSize: 12,
            response: "114 KIAS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5000 lb (2268 kg)",
            color: "white",
            fontSize: 12,
            response: "104 KIAS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4000 lb (1814 kg)",
            color: "white",
            fontSize: 12,
            response: "93 KIAS",
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.AirStart,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Airspeed",
            color: "white",
            fontSize: 12,
            response: "120 - 200 KIAS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Altitude",
            color: "white",
            fontSize: 12,
            response: "< 18,000 FEET",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Thrust Lever",
            color: "white",
            fontSize: 12,
            response: "IDLE",
          },
          {
            type: ChecklistItemType.Text,
            content: "Engine reset:",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Engine Knob",
            color: "white",
            fontSize: 12,
            response: "OFF",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5. Engine Button",
            color: "white",
            fontSize: 12,
            response: "PRESS (MOMENTARY)",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "6. N2",
            color: "white",
            fontSize: 12,
            response: "WAIT UNTIL < 24%",
          },
          {
            type: ChecklistItemType.Text,
            content: "If time permits:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. N2",
            color: "white",
            fontSize: 12,
            response: "WAIT UNTIL < 16%",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Engine start:",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "7. Engine Knob",
            color: "white",
            fontSize: 12,
            response: "RUN",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "8. Engine Button",
            color: "white",
            fontSize: 12,
            response: "PRESS (MOMENTARY)",
          },
          {
            type: ChecklistItemType.Text,
            content: "If air start is successful:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. GEN 1 & GEN 2",
            color: "white",
            fontSize: 12,
            response: "VERIFY ON",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Engine Instruments",
            color: "white",
            fontSize: 12,
            response: "MONITOR",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If air start is unsuccessful:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Engine Knob",
            color: "white",
            fontSize: 12,
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Engine Button",
            color: "white",
            fontSize: 12,
            response: "PRESS (MOMENTARY)",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. GEN 1 and GEN 2",
            color: "white",
            fontSize: 12,
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. Perform Emergency Landing w/o Power checklist.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content:
              'CAUTION <br>Probability of engine restart is greater when N2 < 16%.<br>Do not attempt a restart until N2 < 24%.<br>See Section 2: Limitations, "Engine Start (In flight)" for Engine Air Start envelope.',
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.AutomaticFlightControlMalfunctionStickPusherESPUSPAutopilot,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content:
              "CAUTION: Delay of AP DISC Button in response to an automatic flight control malfunction while manually overriding controls may result in excessive pitch out of trim condition and will require retrimming of the aircraft as needed.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Grip side stick firmly.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. AP DISC Button",
            color: "white",
            fontSize: 12,
            response: "PRESS AND HOLD",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Airplane Control",
            color: "white",
            fontSize: 12,
            response: "MAINTAIN",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. AP SERVOS CB (A3)",
            color: "white",
            fontSize: 12,
            response: "PULL",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5. AP DISC Button",
            color: "white",
            fontSize: 12,
            response: "RELEASE",
          },
          {
            type: ChecklistItemType.Text,
            content: "If in RVSM airspace:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Airplane Control",
            color: "white",
            fontSize: 12,
            response: "MAINTAIN",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Exit RVSM airspace.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "6. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.BestGlideSpeed,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "6000 lb",
            color: "white",
            fontSize: 12,
            response: "114 KIAS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5000 lb",
            color: "white",
            fontSize: 12,
            response: "104 KIAS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4000 lb",
            color: "white",
            fontSize: 12,
            response: "93 KIAS",
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.CabinFireInFlight,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Oxygen Mask",
            color: "white",
            fontSize: 12,
            response: "DON, EMER",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Smoke Goggles (if equipped)",
            color: "white",
            fontSize: 12,
            response: "DON",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. PAX OXY DEPLOY Switch",
            color: "white",
            fontSize: 12,
            response: "ON",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. MIC SELECT Switch",
            color: "white",
            fontSize: 12,
            response: "MASK MIC",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5. BAT 1 Switch",
            color: "white",
            fontSize: 12,
            response: "OFF",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "6. GEN 1 and GEN 2",
            color: "white",
            fontSize: 12,
            response: "OFF",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "7. Fire Extinguisher",
            color: "white",
            fontSize: 12,
            response: "A/R",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "8. Oxygen Mask",
            color: "white",
            fontSize: 12,
            response: "ADJUST TO NORM IF ABLE AND BELOW 20,000 FT",
          },
          {
            type: ChecklistItemType.Text,
            content: "If airflow is not sufficient to clear smoke or fumes:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Perform Smoke Removal checklist.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.CAPSActivation,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Airspeed",
            color: "white",
            fontSize: 12,
            response: "REDUCE BELOW 135 KIAS / 145 KTAS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Activation Handle",
            color: "white",
            fontSize: 12,
            response: "PULL DOWN STEADILY WITH BOTH HANDS",
          },
          {
            type: ChecklistItemType.Text,
            content: "NOTE: Wait for plane to stabilize beneath canopy before proceeding.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Oxygen Mask (above 15,000 ft)",
            color: "white",
            fontSize: 12,
            response: "DON, 100%",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. PAX OXY DEPLOY Switch",
            color: "white",
            fontSize: 12,
            response: "ON",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5. MIC SELECT Switch",
            color: "white",
            fontSize: 12,
            response: "MASK MIC",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "6. Instruct passengers to don oxygen masks.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "7. Passenger Oxygen",
            color: "white",
            fontSize: 12,
            response: "ENSURE PASSENGERS ARE RECEIVING OXYGEN",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "8. ENGINE FIRE ACK",
            color: "white",
            fontSize: 12,
            response: "LIFT GUARD, TOGGLE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "9. ELT",
            color: "white",
            fontSize: 12,
            response: "VERIFY ON",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "10. Landing Gear",
            color: "white",
            fontSize: 12,
            response: "UP",
          },
          {
            type: ChecklistItemType.Text,
            content: "Turn the BAT/GEN Switches OFF after completing any necessary radio communications.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "11. BAT/GEN Switches (below 15,000 ft)",
            color: "white",
            fontSize: 12,
            response: "OFF",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "12. Loose Items",
            color: "white",
            fontSize: 12,
            response: "SECURE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "13. Seat Belts",
            color: "white",
            fontSize: 12,
            response: "TIGHTEN",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "14. Assume emergency landing body position.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "After airplane comes to a complete stop:",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "15. Evacuate quickly and move upwind, well clear of the aircraft and parachute.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.Ditching,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Radio",
            color: "white",
            fontSize: 12,
            response: "TRANSMIT (ATC OR 121.5 MHZ) MAYDAY WITH LOCATION & INTENTIONS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Transponder",
            color: "white",
            fontSize: 12,
            response: "SQUAWK 7700",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. ELT",
            color: "white",
            fontSize: 12,
            response: "ON",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Landing Gear",
            color: "white",
            fontSize: 12,
            response: "UP",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5. Flaps",
            color: "white",
            fontSize: 12,
            response: "100% (RECOMMENDED)",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "6. CABIN PRESSURE DUMP Button",
            color: "white",
            fontSize: 12,
            response: "PRESS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "7. Airspeed",
            color: "white",
            fontSize: 12,
            response: "VREF",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "8. Rate of Descent",
            color: "white",
            fontSize: 12,
            response: "200 - 300 FEET PER MINUTE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "9. Align approach parallel to swells and attempt to touchdown along a wave crest or behind it.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "If surface winds are strong, or waves rough and irregular:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Ditch into the wind on the backside of a wave.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "10. Pitch attitude at water contact",
            color: "white",
            fontSize: 12,
            response: "SLIGHTLY HIGHER THAN NORMAL LANDING ATTITUDE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "11. Airspeed & Rate of Descent",
            color: "white",
            fontSize: 12,
            response: "REDUCE TO MINIMUM, ABOVE STALL WARNING",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "12. Thrust Lever",
            color: "white",
            fontSize: 12,
            response: "IDLE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "13. Water Touchdown",
            color: "white",
            fontSize: 12,
            response: "CONTACT ON CREST OF SWELL, PARALLEL TO MAJOR SWELL",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "14. Airplane",
            color: "white",
            fontSize: 12,
            response: "EVACUATE",
          },
          {
            type: ChecklistItemType.Text,
            content:
              "WARNING: Evacuate via either egress window or main cabin door. However, main cabin door evacuation shall be done only via the upper cabin door. To avoid flooding the airplane, do not open lower cabin door.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "15. Flotation Devices (if equipped)",
            color: "white",
            fontSize: 12,
            response: "INFLATE WHEN CLEAR OF AIRPLANE",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.EmergencyDescent,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. AP DISC",
            color: "white",
            fontSize: 12,
            response: "PRESS AND RELEASE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Thrust Lever",
            color: "white",
            fontSize: 12,
            response: "IDLE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Pitch",
            color: "white",
            fontSize: 12,
            response: "-20 DEGREES (APPROX.)",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Airspeed",
            color: "white",
            fontSize: 12,
            response: "INCREASE TO VMO (250 KIAS) / MMO (0.53 Mach) MAXIMUM",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.EmergencyGroundEgress,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Engine Knob",
            color: "white",
            fontSize: 12,
            response: "OFF",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Engine Button",
            color: "white",
            fontSize: 12,
            response: "PRESS (MOMENTARY)",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. BAT 1 and BAT 2",
            color: "white",
            fontSize: 12,
            response: "OFF",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Parking Brake",
            color: "white",
            fontSize: 12,
            response: "SET",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5. Egress aircraft through exits.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.EmergencyLandingwoPower,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Airplane Control",
            color: "white",
            fontSize: 12,
            response: "MAINTAIN",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Pitch for glide speed.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Turn toward nearest practical landing site.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Radio",
            color: "white",
            fontSize: 12,
            response: "TRANSMIT (ATC OR 121.5 MHZ) MAYDAY WITH LOCATION & INTENTIONS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5. Transponder",
            color: "white",
            fontSize: 12,
            response: "SQUAWK 7700",
          },
          {
            type: ChecklistItemType.Text,
            content: "If landing site is improved:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Landing Gear",
            color: "white",
            fontSize: 12,
            response: "DOWN",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Flaps",
            color: "white",
            fontSize: 12,
            response: "A/R",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Seat Belt(s)",
            color: "white",
            fontSize: 12,
            response: "SECURED",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. CABIN PRESSURE DUMP Button",
            color: "white",
            fontSize: 12,
            response: "PRESS",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. Touchdown",
            color: "white",
            fontSize: 12,
            response: "NORMAL TECHNIQUE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content:
              'WARNING: Refer to Section 3: Emergency Procedures, "Flameout / Precautionary Approach" checklist. If a safe landing is not assured by the High-Key/Low-Key approach, consider CAPS procedures.',
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "After landing:",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "f. BAT 1 and BAT 2",
            color: "white",
            fontSize: 12,
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "g. Evacuate airplane.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If landing site is unimproved:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Landing Gear",
            color: "white",
            fontSize: 12,
            response: "A/R",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Flaps",
            color: "white",
            fontSize: 12,
            response: "A/R WITHIN GLIDING DISTANCE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Seat Belt(s)",
            color: "white",
            fontSize: 12,
            response: "SECURED",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. CABIN PRESSURE DUMP Button",
            color: "white",
            fontSize: 12,
            response: "PRESS",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. Touchdown",
            color: "white",
            fontSize: 12,
            response: "MINIMUM CONTROLLABLE AIRSPEED",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content:
              'WARNING: Refer to Section 3: Emergency Procedures, "Flameout / Precautionary Approach" checklist.<br>If a safe landing is not assured by the High-Key/Low-Key approach, consider CAPS procedures.',
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "After landing:",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "f. BAT 1 and BAT 2",
            color: "white",
            fontSize: 12,
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "g. Evacuate airplane.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.EngineEmergencyOnTakeoffSpeedBelowVR,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "NOTE: Includes emergencies such as engine failure or fire.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Brakes",
            color: "white",
            fontSize: 12,
            response: "MAX PILOT EFFORT W/O SKIDDING",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Thrust Lever",
            color: "white",
            fontSize: 12,
            response: "IDLE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Engine Knob",
            color: "white",
            fontSize: 12,
            response: "OFF",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Engine Button",
            color: "white",
            fontSize: 12,
            response: "PRESS (MOMENTARY)",
          },
          {
            type: ChecklistItemType.Text,
            content: "If ENGINE FIRE Warning occurs:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. ENGINE FIRE ACK",
            color: "white",
            fontSize: 12,
            response: "LIFT GUARD, TOGGLE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. L / R PUSH TO DISCHARGE",
            color: "white",
            fontSize: 12,
            response: "PUSH",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. CABIN PRESSURE DUMP Button",
            color: "white",
            fontSize: 12,
            response: "PRESS",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. GEN 1 & GEN 2",
            color: "white",
            fontSize: 12,
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. BAT 1 and BAT 2",
            color: "white",
            fontSize: 12,
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "f. Evacuate airplane.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If no indication of engine fire:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Parking Brake",
            color: "white",
            fontSize: 12,
            response: "DO NOT SET",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Exit aircraft normally when safe to do so.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "After airplane comes to a complete stop:",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5. Brakes",
            color: "white",
            fontSize: 12,
            response: "COOL DOWN",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content:
              "CAUTION: For maximum brake effectiveness, retract flaps, hold side stick control full back, and bring the airplane to a stop by smooth, even application of the brakes. A cool down period and brake overheat inspection are required after high-energy braking events. Refer to Section 2: Limitations, Brakes.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.EngineFailureInFlight,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Pitch for air start",
            color: "white",
            fontSize: 12,
            response: "AIRSPEED 120 - 200 KIAS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Turn toward possible landing site(s).",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Oxygen Mask",
            color: "white",
            fontSize: 12,
            response: "DON, 100%",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. MIC SELECT Switch",
            color: "white",
            fontSize: 12,
            response: "MASK MIC",
          },
          {
            type: ChecklistItemType.Text,
            content:
              "NOTE: Engine can be considered safe to attempt restart if no abnormal, loud noises or vibrations were noted prior to or during shutdown, N1 rotation is observed, and no exceedances were noted prior to shutdown.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If engine appears safe to attempt a restart:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Perform Air Start checklist.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If engine is unsafe to restart:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Engine Knob",
            color: "white",
            fontSize: 12,
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Engine Button",
            color: "white",
            fontSize: 12,
            response: "PRESS (MOMENTARY)",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Perform Emergency Landing w/o Power checklist.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content:
              "If engine failure is accompanied by fuel fumes in the cockpit, or if internal engine damage is suspected:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. ENGINE FIRE ACK",
            color: "white",
            fontSize: 12,
            response: "LIFT GUARD, TOGGLE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Shut down engine. Do not attempt a restart.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Perform Emergency Landing w/o Power checklist.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.EngineFailureOnTakeoffLowAltitude,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Best Glide or Landing Speed",
            color: "white",
            fontSize: 12,
            response: "100 KIAS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Landing Gear",
            color: "white",
            fontSize: 12,
            response: "A/R",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Flaps",
            color: "white",
            fontSize: 12,
            response: "A/R",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Land straight ahead.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "If time permits:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Engine Knob",
            color: "white",
            fontSize: 12,
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Engine Button",
            color: "white",
            fontSize: 12,
            response: "PRESS (MOMENTARY)",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. CABIN PRESSURE DUMP Button",
            color: "white",
            fontSize: 12,
            response: "PRESS",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. GEN 1 & GEN 2",
            color: "white",
            fontSize: 12,
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. BAT 1 and BAT 2",
            color: "white",
            fontSize: 12,
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.EngineFireOnTakeoffLowAltitude,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Land as soon as possible.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If immediate landing is not possible:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Link,
            content: "a. Perform ENGINE FIRE Warning - In Flight checklist.",
            color: "cyan",
            fontSize: 15,
            linkTarget: {
              checklistName: VisionJetWarningChecklistNames.ENGINEFIREWarningInFlight,
              checklistCategory: VisionJetChecklistCategory.Warning,
            },
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.FlameoutPrecautionaryApproach,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "POSITION......ALTITUDE......AIRSPEED",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "High-Key......3000 ft AGL......115-130 KIAS",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "Low-Key......1500 ft AGL......120 KIAS",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "Base Leg......1000 ft AGL.......120 KIAS",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.JammedElevatorTrimTab,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "During Cruise:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Thrust Lever",
            color: "white",
            fontSize: 12,
            response: "A/R",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Landing Gear",
            color: "white",
            fontSize: 12,
            response: "A/R",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Airspeed",
            color: "white",
            fontSize: 12,
            response: "MAINTAIN LAST TRIMMED AIRSPEED OR A/R",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. Flaps",
            color: "white",
            fontSize: 12,
            response: "UP OR A/R FOR CONDITIONS",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "During Takeoff or Go-Around:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Pitch and Thrust",
            color: "white",
            fontSize: 12,
            response: "MAINTAIN ALTITUDE AND FLYING SPEED AS REQUIRED",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "NOTE: Expect extremely high stick forces.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "When safely airborne and clear of obstacles:",
            color: "white",
            fontSize: 15,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Flaps",
            color: "white",
            fontSize: 12,
            response: "PLACE IN POSITION THAT JAM OCCURRED",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "NOTE: 100% flaps may alleviate excessive nose-up tendencies following a normal takeoff.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Landing Gear",
            color: "white",
            fontSize: 12,
            response: "DO NOT RETRACT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.LandingWithoutAileronControl,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Flaps",
            color: "white",
            fontSize: 12,
            response: "50%",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Trim",
            color: "white",
            fontSize: 12,
            response: "VREF",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Thrust Lever",
            color: "white",
            fontSize: 12,
            response: "A/R",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Use rudder as necessary to align the aircraft with the runway.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.LandingWithoutElevatorControl,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Use manual trim wheel to control pitch attitude.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Flaps",
            color: "white",
            fontSize: 12,
            response: "50%",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Make small pitch and power changes and prepare for landing configuration early.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "After touchdown and after the nose wheel is on the ground:",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Brakes",
            color: "white",
            fontSize: 12,
            response: "A/R",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.LandingWithoutRudderControl,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Touchdown",
            color: "white",
            fontSize: 12,
            response: "ACCOMPLISH",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Maintain directional control on ground, using brakes and ailerons as required.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.LossofAllFlightDisplays,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. BAT 1 and BAT 2",
            color: "white",
            fontSize: 12,
            response: "VERIFY ON",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. GEN 1 and GEN 2",
            color: "white",
            fontSize: 12,
            response: "VERIFY ON",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Land as soon as possible.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.LossofReliableAirspeedIndication,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Autopilot",
            color: "white",
            fontSize: 12,
            response: "DISENGAGE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. AOA Display",
            color: "white",
            fontSize: 12,
            response: "ON",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Use following AOA guidance pertaining to phase of flight.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Climb:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. AOA",
            color: "white",
            fontSize: 12,
            response: "0.25",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "NOTE: Airspeed is approximately 160 KIAS.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "Cruise:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Power",
            color: "white",
            fontSize: 12,
            response: 'SET N1% PER Section 5: Performance Data, "Cruise Performance"',
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Descent:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. AOA",
            color: "white",
            fontSize: 12,
            response: "0.25",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "NOTE: Airspeed is approximately 160 KIAS.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "Approach:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "Gear UP:",
            color: "white",
            fontSize: 15,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) AOA",
            color: "white",
            fontSize: 12,
            response: "0.35",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Text,
            content: "NOTE: Airspeed is approximately 120 KIAS.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "Gear DOWN, Flaps DOWN",
            color: "white",
            fontSize: 15,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) AOA",
            color: "white",
            fontSize: 12,
            response: "0.53",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Text,
            content: "NOTE: Refer to VREF Speeds table.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "Go Around:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. AOA",
            color: "white",
            fontSize: 12,
            response: "0.53",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "NOTE: Refer to VREF Speeds table.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.LossofThrustControl,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Shut down engine, if required.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Flaps",
            color: "white",
            fontSize: 12,
            response: "A/R",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Landing Gear",
            color: "white",
            fontSize: 12,
            response: "A/R",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If the thrust lever is stuck at, or near, the T/O detent:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Turn toward nearest practical landing site.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Engine Knob",
            color: "white",
            fontSize: 12,
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Engine Button",
            color: "white",
            fontSize: 12,
            response: "PRESS (MOMENTARY)",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. Fly a Flameout/Precautionary Approach.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. If necessary, consider CAPS Activation.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content:
              "If the thrust lever is stuck at, or near, the IDLE position, and straight and level flight cannot be maintained:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Pitch for glide speed.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Turn toward nearest practical landing site.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Fly a Flameout/Precautionary Approach.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. If necessary, consider CAPS Activation.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.PitchTrimRunawayFailure,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "Red PTRM annunciator on PFD.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Grip side stick firmly.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. AP DISC Button",
            color: "white",
            fontSize: 12,
            response: "PRESS AND HOLD",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Pitch Trim",
            color: "white",
            fontSize: 12,
            response: "A/R (MANUAL TRIM WHEEL)",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. PITCH TRIM CB (A1)",
            color: "white",
            fontSize: 12,
            response: "PULL",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5. AP DISC Button",
            color: "white",
            fontSize: 12,
            response: "RELEASE",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.RejectedTakeoff,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Brakes",
            color: "white",
            fontSize: 12,
            response: "MAX. PILOT EFFORT W/O SKIDDING",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Thrust Lever",
            color: "white",
            fontSize: 12,
            response: "IDLE",
          },
          {
            type: ChecklistItemType.Text,
            content: "After airplane comes to a complete stop:",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Brakes",
            color: "white",
            fontSize: 12,
            response: "COOL DOWN",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.RollTrimRunawayFailure,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Grip side stick firmly.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. AP DISC Button",
            color: "white",
            fontSize: 12,
            response: "PRESS AND HOLD",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Airspeed",
            color: "white",
            fontSize: 12,
            response: "REDUCE (A/R TO MINIMIZE FORCE)",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. ROLL TRIM CB (A2)",
            color: "white",
            fontSize: 12,
            response: "PULL",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5. AP DISC Button",
            color: "white",
            fontSize: 12,
            response: "RELEASE",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.SmokeRemoval,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Oxygen Mask",
            color: "white",
            fontSize: 12,
            response: "DON, EMER",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Smoke Goggles (if equipped)",
            color: "white",
            fontSize: 12,
            response: "DON",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. PAX OXY DEPLOY Switch",
            color: "white",
            fontSize: 12,
            response: "ON",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. MIC SELECT Switch",
            color: "white",
            fontSize: 12,
            response: "MASK MIC",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5. Instruct passenger(s) to don mask(s).",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "6. DEFOG Button",
            color: "white",
            fontSize: 12,
            response: "ON",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "7. CABIN PRESSURE DUMP Button",
            color: "white",
            fontSize: 12,
            response: "PRESS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "8. Perform Emergency Descent checklist as required.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "9. BLEED Switch (below 14,000 feet)",
            color: "white",
            fontSize: 12,
            response: "FRESH",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "10. ECS DISABLE",
            color: "white",
            fontSize: 12,
            response: "SELECT",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "11. FIRE EXTINGUISHER",
            color: "white",
            fontSize: 12,
            response: "A/R",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "12. All Other Switches (except BAT 2)",
            color: "white",
            fontSize: 12,
            response: "OFF",
          },
          {
            type: ChecklistItemType.Text,
            content:
              "If setting switches off eliminates fire / fumes source and airplane is in night or IFR conditions:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. BAT 1 Switch",
            color: "white",
            fontSize: 12,
            response: "ON",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. GEN 1 & GEN 2",
            color: "white",
            fontSize: 12,
            response: "A/R",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Required Systems",
            color: "white",
            fontSize: 12,
            response: "ACTIVATE ONE AT A TIME",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. Temperature Select",
            color: "white",
            fontSize: 12,
            response: "COLD",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. Panel Air Outlets",
            color: "white",
            fontSize: 12,
            response: "OPEN",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "f. Land as soon as possible.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "g. Oxygen Masks",
            color: "white",
            fontSize: 12,
            response: "ADJUST TO NORM IF ABLE AND BELOW 20,000 FEET",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "13. Land as soon as possible.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "14. Oxygen Mask",
            color: "white",
            fontSize: 12,
            response: "ADJUST TO NORM IF ABLE AND BELOW 20,000 FT",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetEmergencyProceduresChecklistNames.UncontainedEngineFailureRotorBurstinFlight,
        VisionJetChecklistCategory.EmergencyProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Pitch for 120 KIAS (APPROX.)",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Turn toward possible landing site(s).",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Oxygen Mask",
            color: "white",
            fontSize: 12,
            response: "DON, 100%",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. MIC SELECT Switch",
            color: "white",
            fontSize: 12,
            response: "MASK MIC",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5. ENGINE FIRE ACK",
            color: "white",
            fontSize: 12,
            response: "LIFT GUARD, TOGGLE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "6. L / R PUSH TO DISCHARGE",
            color: "white",
            fontSize: 12,
            response: "PUSH (REGARDLESS OF ARMED LIGHT)",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "7. Engine Knob",
            color: "white",
            fontSize: 12,
            response: "OFF",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "8. Engine Button",
            color: "white",
            fontSize: 12,
            response: "PRESS (MOMENTARY)",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "9. GEN 1 and GEN 2",
            color: "white",
            fontSize: 12,
            response: "OFF",
          },
          {
            type: ChecklistItemType.Link,
            content: "10. Perform Emergency Landing w/o Power checklist.",
            color: "cyan",
            fontSize: 15,
            linkTarget: {
              checklistName: VisionJetEmergencyProceduresChecklistNames.EmergencyLandingwoPower,
              checklistCategory: VisionJetChecklistCategory.EmergencyProcedures,
            },
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
        true,
      ),
    ];
  }
}
