import {
  ChecklistItemInteractionType,
  ChecklistItemType,
  Justification,
} from "@base/Shared/ChecklistSystem/ChecklistItem";
import { VisionJetChecklist, VisionJetChecklistCategory } from "../Checklist";

export enum VisionJetAbnormalProceduresChecklistNames {
  AbnormalEngineShutdownOnGround = "Abnormal Engine Shutdown On Ground",
  AFCSAlerts = "AFCS Alerts",
  AileronMistrimLeftRight = "Aileron Mistrim Left/Right",
  AlternateGearExtension = "Alternate Gear Extension",
  AutopilotAbnormalDisconnect = "Autopilot Abnormal Disconnect",
  AutopilotFailure = "Autopilot Failure",
  AutopilotPreflightTestFail = "Autopilot Preflight Test Fail",
  CommunicationsFailure = "Communications Failure",
  DryMotoringEngineFailedEngineStart = "Dry Motoring Engine - Failed Engine Start",
  ElevatorMistrimDown = "Elevator Mistrim Down",
  ElevatorMistrimUp = "Elevator Mistrim Up",
  FlapsInoperativeApproachLanding = "Flaps Inoperative Approach/Landing",
  FlightThroughVolcanicAsh = "Flight Through Volcanic Ash",
  GearIndicationsNotDownLocked = "Gear Indication(s) Not Down/Locked",
  LandingWithFailedBrakes = "Landing With Failed Brakes",
  LandingWithFlatTire = "Landing With Flat Tire",
  LossofGPSNavigation = "Loss of GPS Navigation",
  PitchAxisFailure = "Pitch Axis Failure",
  RollAxisFailure = "Roll Axis Failure",
  WingStabIPSActivatedinRVSMAirspace = "Wing/Stab IPS Activated in RVSM Airspace",
  YawAxisFailure = "Yaw Axis Failure",
}

/** A utility class to generate Vision Jet Abnormal checklist data. */
export class VisionJetAbnormalProceduresChecklists {
  /**
   * Generates the Vision Jet Abnormal checklist data.
   * @returns An array of Vision Jet Abnormal checklists.
   **/
  public static getChecklists(): VisionJetChecklist[] {
    return [
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.AbnormalEngineShutdownOnGround,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "If normal engine shutdown is not successful:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Thrust Lever",
            color: "white",
            fontSize: 12,
            response: "IDLE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. ENGINE FIRE ACK",
            color: "white",
            fontSize: 12,
            response: "LIFT GUARD, TOGGLE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.AFCSAlerts,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "For more information on AFCS alerts, refer to SF50 Garmin Cockpit Reference Guide.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.AileronMistrimLeftRight,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "Yellow (left/right arrow) AIL annunciator on PFD.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "NOTE: Be prepared for out of trim condition if AP is disengaged.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Manipulate aileron trim as required to eliminate the mistrim condition.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content:
              "NOTE: Momentary roll trim input in the direction of mistrim indication will typically correct the condition.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If condition persists:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Disengage autopilot.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Retrim aircraft as desired.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.AlternateGearExtension,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Airspeed",
            color: "white",
            fontSize: 12,
            response: "BELOW 210 KIAS",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. LANDING GEAR HYD CB (B4)",
            color: "white",
            fontSize: 12,
            response: "PULL",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Landing Gear Handle",
            color: "white",
            fontSize: 12,
            response: "DOWN",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Alternate Gear Extension Handle",
            color: "white",
            fontSize: 12,
            response: "PULL TO STOP, RESTOW",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5. Verify 3 Green, DOWN / LOCKED indications.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "If landing gear is down and locked:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. No further action required.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If landing gear is not down and locked:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Alternate Gear Extension Handle",
            color: "white",
            fontSize: 12,
            response: "PULL TO STOP, RESTOW",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content:
              "NOTE: Pull the handle to the end of its available travel to ensure landing gear is fully unlocked.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content:
              "b. Reduce airspeed, or increase load factor (g) by increasing bank angle to assist in extending/locking the gear.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content:
              "c. Check landing gear indications. If landing gear indications are still not confirmed down, prepare for landing with possible gear issue.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. Perform visual verification of gear position by ATC (towered airport), if possible.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.AutopilotAbnormalDisconnect,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "Red AP flashing on PFD; continuous high-low aural tone.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. AP DISC Button",
            color: "white",
            fontSize: 12,
            response: "PRESS AND RELEASE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Airplane Control",
            color: "white",
            fontSize: 12,
            response: "MAINTAIN",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.AutopilotFailure,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "Red AFCS annunciator on PFD; red AP flashing on PFD; continuous high-low aural tone.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. AP DISC Button",
            color: "white",
            fontSize: 12,
            response: "PRESS AND RELEASE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Airplane Control",
            color: "white",
            fontSize: 12,
            response: "MAINTAIN",
          },
          {
            type: ChecklistItemType.Text,
            content: "If in RVSM airspace:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Exit RVSM airspace.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.AutopilotPreflightTestFail,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "Red PFT annunciator on PFD.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Do not dispatch.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.CommunicationsFailure,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Switches, Controls",
            color: "white",
            fontSize: 12,
            response: "CHECK",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Frequency",
            color: "white",
            fontSize: 12,
            response: "CHANGE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Circuit Breakers",
            color: "white",
            fontSize: 12,
            response: "SET",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Headset",
            color: "white",
            fontSize: 12,
            response: "CHANGE OR SPEAKER",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "5. Attempt to use oxygen mask microphone or hand-held microphone and cabin speakers.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "If Precipitation-static is experienced during flight:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. WINDSHLD IPS",
            color: "white",
            fontSize: 12,
            response: "ON",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.DryMotoringEngineFailedEngineStart,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Thrust Lever",
            color: "white",
            fontSize: 12,
            response: "IDLE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Engine Knob",
            color: "white",
            fontSize: 12,
            response: "OFF",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. BLEED Switch",
            color: "white",
            fontSize: 12,
            response: "FRESH",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Engine Button",
            color: "white",
            fontSize: 12,
            response: "PRESS AND HOLD 15 - 30 SECONDS",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.ElevatorMistrimDown,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "Yellow (down arrow) ELE annunciator on PFD.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "NOTE: Be prepared for out of trim condition if AP is disengaged.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Manipulate elevator trim down to eliminate the mistrim condition.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "If condition persists:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Disengage autopilot.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Retrim aircraft as desired.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.ElevatorMistrimUp,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "Yellow (up arrow) ELE annunciator on PFD.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "NOTE: Be prepared for out of trim condition if AP is disengaged.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Manipulate elevator trim up to eliminate the mistrim condition.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "If condition persists:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Disengage autopilot.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Retrim aircraft as desired.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.FlapsInoperativeApproachLanding,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. VREF",
            color: "white",
            fontSize: 12,
            response: "REFER TO GREEN DONUT",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Landing Gear",
            color: "white",
            fontSize: 12,
            response: "DOWN AND LOCKED",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.FlightThroughVolcanicAsh,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. Engine Parameters",
            color: "white",
            fontSize: 12,
            response: "MONITOR",
          },
          {
            type: ChecklistItemType.Text,
            content: "If engine parameters cannot be kept within limits:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land as soon as possible.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.GearIndicationsNotDownLocked,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "If in flight:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Landing Gear",
            color: "white",
            fontSize: 12,
            response: "CYCLE UP, THEN DOWN",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "If Landing Gear is down and locked:",
            color: "white",
            fontSize: 15,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Monitor landing gear indications.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If Landing Gear is not down and locked:",
            color: "white",
            fontSize: 15,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Perform Alternate Gear Extension checklist.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If on ground:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Do not taxi.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Landing Gear",
            color: "white",
            fontSize: 12,
            response: "CHECK DOWN",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.LandingWithFailedBrakes,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "If one brake is inoperative:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land on the side of runway corresponding to the inoperative brake.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Maintain directional control using rudder and operational brake.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Shut down engine as soon as practical.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If both brakes are inoperative:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Divert to the longest, widest runway with the most direct headwind.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Land on downwind side of the runway.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Use the rudder and aileron for directional control.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. Shut down engine as soon as practical.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.LandingWithFlatTire,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "If main gear tire is flat:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land on the side of the runway corresponding to the good tire.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Maintain directional control with the brakes, rudder, and aileron.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Do not taxi. Stop the airplane and perform a normal Engine Shutdown.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If nose gear tire is flat:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land in the center of the runway.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Hold the nosewheel off the ground as long as possible.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Do not taxi. Stop the airplane and perform a normal Engine Shutdown.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.LossofGPSNavigation,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "Amber GPS LOI text left of HSI and/or white system message on touchscreen controller.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Navigation",
            color: "white",
            fontSize: 12,
            response: "VISUAL, OR SELECT VOR AND/OR DME",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Perform STICK PUSHER FAIL Caution checklist.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.PitchAxisFailure,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "Red PTCH annunciator on PFD.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Altitude",
            color: "white",
            fontSize: 12,
            response: "MONITOR AND MAINTAIN AS POSSIBLE",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.RollAxisFailure,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "Red ROLL annunciator on PFD.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Airplane Control",
            color: "white",
            fontSize: 12,
            response: "MAINTAIN",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.WingStabIPSActivatedinRVSMAirspace,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "If activated by pilot:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Advise ATC of non RVSM status.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If activated uncommanded:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Verify WING/STAB Switch OFF.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. WING/STAB IPS CB (A6)",
            color: "white",
            fontSize: 12,
            response: "PULL",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAbnormalProceduresChecklistNames.YawAxisFailure,
        VisionJetChecklistCategory.AbnormalProcedures,
        [
          {
            type: ChecklistItemType.Text,
            content: "Red YAW annunciator on PFD.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Continue flight.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
        true,
      ),
    ];
  }
}
