import {
  ChecklistItemInteractionType,
  ChecklistItemType,
  Justification,
} from "@base/Shared/ChecklistSystem/ChecklistItem";
import { VisionJetChecklist, VisionJetChecklistCategory } from "../Checklist";

export enum VisionJetAdvisoryChecklistNames {
  CAPSAUTOPILOTINOPAdvisory = "CAPS AUTOPILOT INOP Advisory",
  CAPSMISCOMPAREAdvisory = "CAPS MISCOMPARE Advisory",
  DOOROPENAdvisory = "DOOR OPEN Advisory",
  EDMDISABLEDAdvisory = "EDM DISABLED Advisory",
  ESPFAILAdvisory = "ESP FAIL Advisory",
  ESPOFFAdvisory = "ESP OFF Advisory",
  FIREEXTLOWLAdvisory = "FIRE EXT LOW L Advisory",
  FIREEXTLOWRAdvisory = "FIRE EXT LOW R Advisory",
  FUELPUMPONAdvisory = "FUEL PUMP ON Advisory",
  FUELSHUTOFFAdvisory = "FUEL SHUTOFF Advisory",
  FUELTANKBALANCEDAdvisory = "FUEL TANK BALANCED Advisory",
  IPSENGINLETUNDERPRESSAdvisory = "IPS ENG INLET UNDERPRESS Advisory",
  IPSFLUIDLOWAdvisory = "IPS FLUID LOW Advisory",
  MASKMICROPHONEAdvisory = "MASK MICROPHONE Advisory",
  OXYGENONAdvisory = "OXYGEN ON Advisory",
  SFDNOCOMPAREAdvisory = "SFD NO-COMPARE Advisory",
  STALLSPEEDHIGHAdvisory = "STALL SPEED HIGH Advisory",
  STARTERENGAGEDAdvisory = "STARTER ENGAGED Advisory",
  SURFACEWATCHFAILAdvisory = "SURFACEWATCH FAIL Advisory",
  TAKEOFFPITCHTRIMAdvisory = "TAKEOFF PITCH TRIM Advisory",
  TAKEOFFTHRUSTAdvisory = "TAKEOFF THRUST Advisory",
  WHEELSPEEDFAULTAdvisory = "WHEEL SPEED FAULT Advisory",
  WOWDISAGREEAdvisory = "WOW DISAGREE Advisory",
}

/** A utility class to generate Vision Jet Advisory checklist data. */
export class VisionJetAdvisoryChecklists {
  /**
   * Generates the Vision Jet Advisory checklist data.
   * @returns An array of Vision Jet Advisory checklists.
   **/
  public static getChecklists(): VisionJetChecklist[] {
    return [
      new VisionJetChecklist(
        VisionJetAdvisoryChecklistNames.CAPSAUTOPILOTINOPAdvisory,
        VisionJetChecklistCategory.Advisory,
        [
          {
            type: ChecklistItemType.Text,
            content: "Minimize CAPS deployment speed.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If in an emergency situation:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Airspeed",
            color: "white",
            fontSize: 12,
            response: "MANUALLY REDUCE BELOW 135 KIAS AND 145 KTAS BEFORE DEPLOYING PARACHUTE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Throttle",
            color: "white",
            fontSize: 12,
            response: "ENSURE THROTTLE IS REDUCED TO IDLE BEFORE DEPLOYING PARACHUTE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAdvisoryChecklistNames.CAPSMISCOMPAREAdvisory,
        VisionJetChecklistCategory.Advisory,
        [
          {
            type: ChecklistItemType.Text,
            content: "CAPS service required.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If in flight:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If on ground:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Do not dispatch.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(VisionJetAdvisoryChecklistNames.DOOROPENAdvisory, VisionJetChecklistCategory.Advisory, [
        {
          type: ChecklistItemType.Text,
          content: "One or more doors are open.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "On ground only:",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Advisory only. No further action required.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(VisionJetAdvisoryChecklistNames.EDMDISABLEDAdvisory, VisionJetChecklistCategory.Advisory, [
        {
          type: ChecklistItemType.Text,
          content: "Emergency Descent Mode is disabled.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Advisory only. No further action required.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(VisionJetAdvisoryChecklistNames.ESPFAILAdvisory, VisionJetChecklistCategory.Advisory, [
        {
          type: ChecklistItemType.Text,
          content: "ESP is inoperative.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Advisory only. No further action required.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(VisionJetAdvisoryChecklistNames.ESPOFFAdvisory, VisionJetChecklistCategory.Advisory, [
        {
          type: ChecklistItemType.Text,
          content: "ESP selected off.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Advisory only. No further action required.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(VisionJetAdvisoryChecklistNames.FIREEXTLOWLAdvisory, VisionJetChecklistCategory.Advisory, [
        {
          type: ChecklistItemType.Text,
          content: "Pressure is low in the left fire extinguisher.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Continue flight.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "2. Service aircraft as soon as practical.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(VisionJetAdvisoryChecklistNames.FIREEXTLOWRAdvisory, VisionJetChecklistCategory.Advisory, [
        {
          type: ChecklistItemType.Text,
          content: "Pressure is low in the right fire extinguisher.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Continue flight.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "2. Service aircraft as soon as practical.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(VisionJetAdvisoryChecklistNames.FUELPUMPONAdvisory, VisionJetChecklistCategory.Advisory, [
        {
          type: ChecklistItemType.Text,
          content: "Fuel pump is ON for normal operations.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Advisory only. No further action required.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(VisionJetAdvisoryChecklistNames.FUELSHUTOFFAdvisory, VisionJetChecklistCategory.Advisory, [
        {
          type: ChecklistItemType.Text,
          content: "Fuel shutoff valve is closed.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. ENGINE FIRE ACK",
          color: "white",
          fontSize: 12,
          response: "CLOSE GUARD",
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(
        VisionJetAdvisoryChecklistNames.FUELTANKBALANCEDAdvisory,
        VisionJetChecklistCategory.Advisory,
        [
          {
            type: ChecklistItemType.Text,
            content: "Fuel tank quantity balance has been detected.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Fuel Control Switch",
            color: "white",
            fontSize: 12,
            response: "AUTO",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAdvisoryChecklistNames.IPSENGINLETUNDERPRESSAdvisory,
        VisionJetChecklistCategory.Advisory,
        [
          {
            type: ChecklistItemType.Text,
            content: "Engine IPS bleed flow low with engine at idle.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "On ground only:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If in icing conditions:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Increase engine thrust to extinguish message.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(VisionJetAdvisoryChecklistNames.IPSFLUIDLOWAdvisory, VisionJetChecklistCategory.Advisory, [
        {
          type: ChecklistItemType.Text,
          content: "IPS fluid below minimum dispatch quantity.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "On ground only:",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Fill IPS fluid as desired.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(
        VisionJetAdvisoryChecklistNames.MASKMICROPHONEAdvisory,
        VisionJetChecklistCategory.Advisory,
        [
          {
            type: ChecklistItemType.Text,
            content: "A crew mask microphone is switched on.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If not wearing oxygen mask:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Turn MIC selection switch to normal headset position.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(VisionJetAdvisoryChecklistNames.OXYGENONAdvisory, VisionJetChecklistCategory.Advisory, [
        {
          type: ChecklistItemType.Text,
          content: "Oxygen is on.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "On ground only:",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Advisory only. No further action required.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(
        VisionJetAdvisoryChecklistNames.SFDNOCOMPAREAdvisory,
        VisionJetChecklistCategory.Advisory,
        [
          {
            type: ChecklistItemType.Text,
            content: "SFD comparison data missing.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Exit IMC.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAdvisoryChecklistNames.STALLSPEEDHIGHAdvisory,
        VisionJetChecklistCategory.Advisory,
        [
          {
            type: ChecklistItemType.Text,
            content: "Stall protection system adjusted for icing.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If airframe is no longer ice contaminated:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. IPS Stall Offset Reset via MFD Controller:",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) From Home, touch Aircraft Systems.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(2) Touch the IPS Stall Offset Reset Button.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAdvisoryChecklistNames.STARTERENGAGEDAdvisory,
        VisionJetChecklistCategory.Advisory,
        [
          {
            type: ChecklistItemType.Text,
            content: "Engine start in progress.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "NOTE: Receiving a STARTER ENGAGED CAS Advisory is normal during an engine start.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAdvisoryChecklistNames.SURFACEWATCHFAILAdvisory,
        VisionJetChecklistCategory.Advisory,
        [
          {
            type: ChecklistItemType.Text,
            content: "SurfaceWatch failed.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "NOTE: SurfaceWatch is unavailable.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAdvisoryChecklistNames.TAKEOFFPITCHTRIMAdvisory,
        VisionJetChecklistCategory.Advisory,
        [
          {
            type: ChecklistItemType.Text,
            content: "Pitch trim not in takeoff configuration.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "On ground only:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Pitch Trim Position",
            color: "white",
            fontSize: 12,
            response: "WITHIN GREEN ARC",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAdvisoryChecklistNames.TAKEOFFTHRUSTAdvisory,
        VisionJetChecklistCategory.Advisory,
        [
          {
            type: ChecklistItemType.Text,
            content: "Engine is in takeoff thrust.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Thrust Lever",
            color: "white",
            fontSize: 12,
            response: "MCT",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAdvisoryChecklistNames.WHEELSPEEDFAULTAdvisory,
        VisionJetChecklistCategory.Advisory,
        [
          {
            type: ChecklistItemType.Text,
            content: "Wheel speed sensor fault detected.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Advisory only. No further action required.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetAdvisoryChecklistNames.WOWDISAGREEAdvisory,
        VisionJetChecklistCategory.Advisory,
        [
          {
            type: ChecklistItemType.Text,
            content: "WOW indicating opposite on ground/in air states.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Continue flight.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
        true,
      ),
    ];
  }
}
