import {
  ChecklistItemInteractionType,
  ChecklistItemType,
  Justification,
} from "@base/Shared/ChecklistSystem/ChecklistItem";
import { VisionJetChecklist, VisionJetChecklistCategory } from "../Checklist";
import { VisionJetAbnormalProceduresChecklistNames } from "../Checklists/VisionJetAbnormalProceduresChecklist";

export enum VisionJetCautionAFChecklistNames {
  AOAFAILCaution = "AOA FAIL Caution",
  AOAHEATFAILCaution = "AOA HEAT FAIL Caution",
  BLEEDAIRCaution = "BLEED AIR Caution",
  BLEEDLEAKCaution = "BLEED LEAK Caution",
  BLEEDOFFCaution = "BLEED OFF Caution",
  BLEEDOPENCaution = "BLEED OPEN Caution",
  BLEEDOVERPRESSURECaution = "BLEED OVERPRESSURE Caution",
  CABINLFENOTSETCaution = "CABIN LFE NOT SET Caution",
  CABINPRESSURECTRLFAILCaution = "CABIN PRESSURE CTRL FAIL Caution",
  DOOROPENEMEREXITCaution = "DOOR OPEN EMER EXIT Caution",
  ECSBLEEDHOTCaution = "ECS BLEED HOT Caution",
  ECSBLEEDOVERHEATCaution = "ECS BLEED OVERHEAT Caution",
  ECSCONTROLFAILCaution = "ECS CONTROL FAIL Caution",
  ECSTEMPBACKUPCaution = "ECS TEMP BACKUP Caution",
  EMERBATTERYFAILCaution = "EMER BATTERY FAIL Caution",
  EMERBATTERYFAULTCaution = "EMER BATTERY FAULT Caution",
  ENGINESTARTBATTEMPCaution = "ENGINE START BAT TEMP Caution",
  ENGINESTARTVOLTSCaution = "ENGINE START VOLTS Caution",
  ESSBUSVOLTSCaution = "ESS BUS VOLTS Caution",
  EXTERNALPOWERCONNECTEDCaution = "EXTERNAL POWER CONNECTED Caution",
  FADECNODISPATCHCaution = "FADEC NO DISPATCH Caution",
  FIREDETECTORFAILCaution = "FIRE DETECTOR FAIL Caution",
  FIREEXTLOWLRCaution = "FIRE EXT LOW L-R Caution",
  FLAPSAIRSPEEDINHIBITCaution = "FLAPS AIRSPEED INHIBIT Caution",
  FLAPSDISAGREECaution = "FLAPS DISAGREE Caution",
  FLAPSFAILCaution = "FLAPS FAIL Caution",
  FLAPSSELECTORFAILCaution = "FLAPS SELECTOR FAIL Caution",
  FLIGHTIDLEFAILCaution = "FLIGHT IDLE FAIL Caution",
  FUELIMBALANCECaution = "FUEL IMBALANCE Caution",
  FUELLOWLEFTRIGHTTOTALCaution = "FUEL LOW LEFT/RIGHT/TOTAL Caution",
  FUELPUMPFAILCaution = "FUEL PUMP FAIL Caution",
  FUELPUMPONCaution = "FUEL PUMP ON Caution",
  FUELQTYMISCOMPARECaution = "FUEL QTY MISCOMPARE Caution",
  FUELSELECTORFAILCaution = "FUEL SELECTOR FAIL Caution",
  FUELSHUTOFFFAILCaution = "FUEL SHUTOFF FAIL Caution",
  FUELTEMPLOWCaution = "FUEL TEMP LOW Caution",
  FUELVALVE1FAILCaution = "FUEL VALVE #1 FAIL Caution",
  FUELVALVE2FAILCaution = "FUEL VALVE #2 FAIL Caution",
  FUELVALVEAUTOFAILCaution = "FUEL VALVE AUTO FAIL Caution",
}

/** A utility class to generate Vision Jet Caution (A-F) checklist data. */
export class VisionJetCautionAFChecklists {
  /**
   * Generates the Vision Jet Caution (A-F) checklist data.
   * @returns An array of Vision Jet Caution (A-F) checklists.
   **/
  public static getChecklists(): VisionJetChecklist[] {
    return [
      new VisionJetChecklist(VisionJetCautionAFChecklistNames.AOAFAILCaution, VisionJetChecklistCategory.CautionAF, [
        { type: ChecklistItemType.Note, content: "AOA signal invalid.", justification: Justification.Left },
        { type: ChecklistItemType.Challenge, content: "1. Airspeed", response: "REFER TO VREF SPEEDS TABLE" },
        {
          type: ChecklistItemType.Challenge,
          content: "2. Avoid stalls, low airspeed, and uncoordinated or abrupt control inputs.",
          response: null,
        },
        { type: ChecklistItemType.Challenge, content: "3. Land as soon as practicable.", response: null },
        { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        { type: ChecklistItemType.Note, content: "VREF Speeds (KIAS)", justification: Justification.Left },
        {
          type: ChecklistItemType.Note,
          content: "-------------------------------------",
          justification: Justification.Left,
        },
        {
          type: ChecklistItemType.Note,
          content: "FLAPS....4000lb 4500lb 5000lb 5550lb 6000lb",
          justification: Justification.Left,
        },
        {
          type: ChecklistItemType.Note,
          content: "-------------------------------------",
          justification: Justification.Left,
        },
        { type: ChecklistItemType.Note, content: "UP or", justification: Justification.Left },
        {
          type: ChecklistItemType.Note,
          content: "UNKNOWN....89....95....100.......104.....109",
          blanksBelow: 1,
          interactionType: ChecklistItemInteractionType.ScrollStop,
        },
        { type: ChecklistItemType.Note, content: "UP (Ice", justification: Justification.Left },
        { type: ChecklistItemType.Note, content: "Contamin.", justification: Justification.Left },
        {
          type: ChecklistItemType.Note,
          content: "Airframe)....115....122...128.......135......140",
          interactionType: ChecklistItemInteractionType.ScrollStop,
        },
        {
          type: ChecklistItemType.Note,
          content: "50%...........82.....87.....91.........96.....100",
          blanksBelow: 1,
          interactionType: ChecklistItemInteractionType.ScrollStop,
        },
        { type: ChecklistItemType.Note, content: "50% (Ice", justification: Justification.Left },
        { type: ChecklistItemType.Note, content: "Contamin.", justification: Justification.Left },
        {
          type: ChecklistItemType.Note,
          content: "Airframe).....98....104...110.......115.....120",
          blanksBelow: 1,
          interactionType: ChecklistItemInteractionType.ScrollStop,
        },
        {
          type: ChecklistItemType.Note,
          content: "100%..........71.....76.....81.........85......89",
          interactionType: ChecklistItemInteractionType.ScrollStop,
        },
      ]),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.AOAHEATFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          { type: ChecklistItemType.Note, content: "AOA heat failure.", justification: Justification.Left },
          { type: ChecklistItemType.Challenge, content: "1. PROBE HT RIGHT CB (E4)", response: "CYCLE" },
          { type: ChecklistItemType.Challenge, content: "2. PROBE HT LEFT CB (A8)", response: "CYCLE" },
          { type: ChecklistItemType.Challenge, content: "3. Avoid/exit icing conditions.", response: null },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(VisionJetCautionAFChecklistNames.BLEEDAIRCaution, VisionJetChecklistCategory.CautionAF, [
        {
          type: ChecklistItemType.Note,
          content: "ECS bleed air system pressure low or failed.",
          justification: Justification.Left,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. BLEED Switch",
          response: "CYCLE FRESH, BLEED WITHIN < 1 SEC",
        },
        { type: ChecklistItemType.Challenge, content: "2. Cabin Altitude", response: "MONITOR" },
        { type: ChecklistItemType.Subtitle, content: "If message extinguishes:" },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Continue flight.",
          response: null,
          justification: Justification.Indent1,
        },
        { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        { type: ChecklistItemType.Subtitle, content: "If message persists:" },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Land as soon as practicable.",
          response: null,
          justification: Justification.Indent1,
        },
        { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
      ]),
      new VisionJetChecklist(VisionJetCautionAFChecklistNames.BLEEDLEAKCaution, VisionJetChecklistCategory.CautionAF, [
        {
          type: ChecklistItemType.Note,
          content: "Bleed leak detected in tailcone.",
          justification: Justification.Left,
        },
        { type: ChecklistItemType.Challenge, content: "1. Oxygen Mask", response: "DON, 100%" },
        { type: ChecklistItemType.Challenge, content: "2. BLEED Switch", response: "FRESH" },
        { type: ChecklistItemType.Challenge, content: "3. MIC SELECT Switch", response: "MASK MIC" },
        { type: ChecklistItemType.Challenge, content: "4. Wait 15 seconds.", response: null },
        { type: ChecklistItemType.Subtitle, content: "If message extinguishes:" },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Descend and land as soon as practicable.",
          response: null,
          justification: Justification.Indent1,
        },
        { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        { type: ChecklistItemType.Subtitle, content: "If message persists:" },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Perform Emergency Descent checklist as required.",
          response: null,
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "b. Thrust Lever",
          response: "REDUCE (MINIMUM REQUIRED)",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "c. Land as soon as possible.",
          response: null,
          justification: Justification.Indent1,
        },
        { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
      ]),
      new VisionJetChecklist(VisionJetCautionAFChecklistNames.BLEEDOFFCaution, VisionJetChecklistCategory.CautionAF, [
        {
          type: ChecklistItemType.Note,
          content: "Bleed air is switched to OFF/FRESH.",
          justification: Justification.Left,
        },
        { type: ChecklistItemType.Subtitle, content: "If bleed is desired OFF:" },
        {
          type: ChecklistItemType.Challenge,
          content: "a. No further action required.",
          response: null,
          justification: Justification.Indent1,
        },
        { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        { type: ChecklistItemType.Subtitle, content: "If bleed is not desired OFF:" },
        {
          type: ChecklistItemType.Challenge,
          content: "a. BLEED Switch",
          response: "CYCLE TO BLEED",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "b. Verify message is extinguished.",
          response: null,
          justification: Justification.Indent1,
        },
        { type: ChecklistItemType.Subtitle, content: "If message persists:", justification: Justification.Indent1 },
        {
          type: ChecklistItemType.Challenge,
          content: "(1) Cabin Altitude",
          response: "MONITOR",
          justification: Justification.Indent2,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "(2) Monitor for CABIN ALTITUDE HIGH Warning.",
          response: null,
          justification: Justification.Indent2,
        },
        { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent2 },
      ]),
      new VisionJetChecklist(VisionJetCautionAFChecklistNames.BLEEDOPENCaution, VisionJetChecklistCategory.CautionAF, [
        {
          type: ChecklistItemType.Note,
          content: "Shutoff solenoid failed to close.",
          justification: Justification.Left,
        },
        { type: ChecklistItemType.Challenge, content: "1. BLEED Switch", response: "CYCLE" },
        { type: ChecklistItemType.Challenge, content: "2. BLEED AIR SHUTOFF CB (D7)", response: "CYCLE" },
        { type: ChecklistItemType.Challenge, content: "3. Land as soon as practicable.", response: null },
        { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
      ]),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.BLEEDOVERPRESSURECaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "ECS bleed air system pressure high.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. Thrust", response: "REDUCE" },
          {
            type: ChecklistItemType.Challenge,
            content: "2. BLEED Switch",
            response: "CYCLE FRESH, BLEED WITHIN < 1 SEC",
          },
          { type: ChecklistItemType.Subtitle, content: "If message extinguishes:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Continue flight.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
          { type: ChecklistItemType.Subtitle, content: "If message still persists:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Thrust",
            response: "MINIMIZE A/R",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Land as soon as practicable.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.CABINLFENOTSETCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Landing field elevation is not set.",
            justification: Justification.Left,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Input destination airport in flight plan.",
            response: null,
          },
          { type: ChecklistItemType.Note, content: "OR", justification: Justification.Left },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Manually set Landing Field Elevation on GTC.",
            response: null,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.CABINPRESSURECTRLFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Detected failure of CPCS Controller.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. Cabin Altitude", response: "MONITOR" },
          { type: ChecklistItemType.Challenge, content: "2. Monitor for CABIN ALTITUDE HIGH Warning.", response: null },
          { type: ChecklistItemType.Challenge, content: "3. Land as soon as practicable.", response: null },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.DOOROPENEMEREXITCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          { type: ChecklistItemType.Note, content: "Emergency exit door is open.", justification: Justification.Left },
          { type: ChecklistItemType.Subtitle, content: "If in flight:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Visually check window latch handle position.",
            response: null,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Land as soon as practicable.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
          { type: ChecklistItemType.Subtitle, content: "If on ground:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Verify window is latched.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.ECSBLEEDHOTCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Bleed supply temperature is too hot.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. Cabin Temp Knob", response: "FULL COLD" },
          { type: ChecklistItemType.Subtitle, content: "If message extinguishes:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. No further action required.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
          { type: ChecklistItemType.Subtitle, content: "If message persists:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. TEMP BACKUP",
            response: "SELECT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Verify message is extinguished.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.ECSBLEEDOVERHEATCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Bleed supply temperature is too hot.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. Cabin Temp Knob", response: "FULL COLD" },
          { type: ChecklistItemType.Subtitle, content: "If message extinguishes:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. No further action required.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
          { type: ChecklistItemType.Subtitle, content: "If message persists:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. TEMP BACKUP",
            response: "SELECT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Verify message is extinguished.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Subtitle, content: "If message persists:", justification: Justification.Indent1 },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Thrust",
            response: "REDUCE AS PRACTICAL",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(2) Verify message is extinguished.",
            response: null,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Subtitle,
            content: "If message persists or if TCV CONTROL FAIL is displayed:",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(a) Oxygen Mask",
            response: "DON, 100%",
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(b) BLEED",
            response: "FRESH",
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(c) MIC SELECT Switch",
            response: "MASK MIC",
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(d) Cabin Altitude",
            response: "MONITOR",
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(e) Monitor for CABIN ALTITUDE HIGH Warning.",
            response: null,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(f) Land as soon as practicable.",
            response: null,
            justification: Justification.Indent3,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent3 },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.ECSCONTROLFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          { type: ChecklistItemType.Note, content: "ECS controller has failed, OR", justification: Justification.Left },
          {
            type: ChecklistItemType.Note,
            content: "All cabin temperature sensors have failed, OR",
            justification: Justification.Left,
          },
          {
            type: ChecklistItemType.Note,
            content: "All ECS fans in cabin have failed, OR",
            justification: Justification.Left,
          },
          {
            type: ChecklistItemType.Note,
            content: "Bleed duct temperature sensor has failed.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. TEMP BACKUP", response: "SELECT" },
          { type: ChecklistItemType.Challenge, content: "2. Cabin Temp Knob", response: "ADJUST FOR CABIN COMFORT" },
          { type: ChecklistItemType.Challenge, content: "3. Monitor for ECS BLEED OVERHEAT Caution.", response: null },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Perform ECS BLEED OVERHEAT Caution checklist, if required.",
            response: null,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.ECSTEMPBACKUPCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Environmental control temperature backup mode.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Subtitle, content: "If TEMP BACKUP mode engaged intentionally:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Cabin Temp Knob",
            response: "ADJUST FOR CABIN COMFORT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Monitor for ECS BLEED HOT or ECS BLEED OVERHEAT cautions.",
            response: null,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Subtitle,
            content: "If ECS BLEED HOT is displayed:",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Perform ECS BLEED HOT caution checklist.",
            response: null,
            justification: Justification.Indent2,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent2 },
          {
            type: ChecklistItemType.Subtitle,
            content: "If ECS BLEED OVERHEAT is displayed:",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Perform ECS BLEED OVERHEAT caution checklist.",
            response: null,
            justification: Justification.Indent2,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent2 },
          { type: ChecklistItemType.Subtitle, content: "If TEMP BACKUP mode engaged unintentionally:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. TEMP BACKUP",
            response: "DESELECT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. ECS Controls",
            response: "A/R",
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.EMERBATTERYFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Emergency battery (Bat 2) service is required.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. Exit IMC as soon as practicable.", response: null },
          { type: ChecklistItemType.Challenge, content: "2. Land as soon as practicable.", response: null },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
          {
            type: ChecklistItemType.Note,
            content: "CAUTION: Emergency battery may be unavailable.",
            justification: Justification.Left,
          },
          {
            type: ChecklistItemType.Note,
            content:
              "NOTE: Battery FAIL indicates an internal condition which reduces capability of the battery. Possible conditions include a faulty temperature sensor, disconnected heater, etc.",
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.EMERBATTERYFAULTCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Emergency battery (Bat 2) fault detected.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. BAT 2 Switch", response: "CYCLE" },
          { type: ChecklistItemType.Subtitle, content: "If message extinguishes:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Continue flight.",
            response: null,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Service aircraft as soon as practicable.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Subtitle, content: "If message persists:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Exit IMC as soon as practicable.",
            response: null,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Land as soon as practicable.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Challenge, content: "2. Contact Cirrus for corrective action.", response: null },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
          {
            type: ChecklistItemType.Note,
            content: "CAUTION: Emergency battery is unavailable.",
            justification: Justification.Left,
          },
          {
            type: ChecklistItemType.Note,
            content:
              "NOTE: Battery FAULT indicates a condition causing the battery to disable charging and/or discharging until corrected. Possible conditions include under-voltage, over-voltage, over-current, short-circuit, and over-temperature.",
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.ENGINESTARTBATTEMPCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Main battery (Bat 1) is below minimum start temp.",
            justification: Justification.Left,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Wait until message extinguishes before attempting start.",
            response: null,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.ENGINESTARTVOLTSCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Main battery (Bat 1) insufficient charge for reliable engine start.",
          },
          { type: ChecklistItemType.Subtitle, content: "On ground only:" },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Battery service, preheat and/or charging is required.",
            response: null,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.ESSBUSVOLTSCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Essential power bus voltage is low, OR",
            justification: Justification.Left,
          },
          {
            type: ChecklistItemType.Note,
            content: "Loss of forward essential power bus voltage.",
            justification: Justification.Left,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Perform GENERATOR 1 CURRENT Caution and GENERATOR 2 CURRENT Caution Checklists.",
            response: null,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.EXTERNALPOWERCONNECTEDCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          { type: ChecklistItemType.Note, content: "External power is connected.", justification: Justification.Left },
          { type: ChecklistItemType.Subtitle, content: "On ground only:" },
          {
            type: ChecklistItemType.Note,
            content: "NOTE: Indicates external power is connected.",
            justification: Justification.Left,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Ensure external power is removed before moving airplane.",
            response: null,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FADECNODISPATCHCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Reference FADEC Fault Code Messages.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. ENG. IPS Switch (OAT < 50 F)", response: "VERIFY ON" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Allow sufficient time for ice to clear from inlet probes.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Challenge, content: "2. FADEC Reset via MFD Controller:", response: null },
          {
            type: ChecklistItemType.Challenge,
            content: "a. From Home, touch Aircraft Systems.",
            response: null,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Touch the FADEC Stale Fault Reset Button.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Subtitle, content: "If message extinguishes:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. No further action required.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
          { type: ChecklistItemType.Subtitle, content: "If message persists:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Continuance of flight is permitted.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FIREDETECTORFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Engine fire detector loop low pressure.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Subtitle, content: "If in flight:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land as soon as practicable.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
          { type: ChecklistItemType.Subtitle, content: "If on ground:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Do not dispatch.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FIREEXTLOWLRCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Pressure is low in both fire extinguishers.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Subtitle, content: "If in flight:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land as soon as practicable.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
          { type: ChecklistItemType.Subtitle, content: "If on ground:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Do not dispatch.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FLAPSAIRSPEEDINHIBITCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          { type: ChecklistItemType.Note, content: "Flaps motion inhibited.", justification: Justification.Left },
          { type: ChecklistItemType.Challenge, content: "1. Airspeed", response: "INCREASE OR REDUCE, AS REQUIRED" },
          { type: ChecklistItemType.Note, content: "OR", justification: Justification.Left },
          { type: ChecklistItemType.Challenge, content: "2. Flaps", response: "RETURN TO PREVIOUS POSITION" },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FLAPSDISAGREECaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Flaps are not within commanded position limits.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. Flaps", response: "CYCLE TO DESIRED POSITION" },
          { type: ChecklistItemType.Subtitle, content: "If message extinguishes:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Continue flight.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
          { type: ChecklistItemType.Subtitle, content: "If message persists:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Flaps",
            response: "MONITOR POSITION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Subtitle,
            content: "If flap position is unknown:",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Airspeed",
            response: "BELOW 150 KIAS",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Perform Flaps Inoperative Approach/Landing checklist.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        ],
      ),
      new VisionJetChecklist(VisionJetCautionAFChecklistNames.FLAPSFAILCaution, VisionJetChecklistCategory.CautionAF, [
        { type: ChecklistItemType.Note, content: "Flaps system inoperative, OR", justification: Justification.Left },
        {
          type: ChecklistItemType.Note,
          content: "Flaps position sensor miscompare, OR",
          justification: Justification.Left,
        },
        {
          type: ChecklistItemType.Note,
          content: "Flaps sensors failed, position unknown, OR",
          justification: Justification.Left,
        },
        {
          type: ChecklistItemType.Note,
          content: "Flaps have not reached the selected position.",
          justification: Justification.Left,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Place flaps in last known or safe position.",
          response: null,
        },
        { type: ChecklistItemType.Challenge, content: "2. FLAPS CB (C2)", response: "CYCLE" },
        { type: ChecklistItemType.Subtitle, content: "If message persists:" },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Perform Flaps Inoperative Approach/Landing checklist.",
          response: null,
          justification: Justification.Indent1,
        },
        { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
      ]),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FLAPSSELECTORFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Cannot determine flaps selector position.",
            justification: Justification.Left,
          },
          {
            type: ChecklistItemType.Link,
            content: "1. Perform Flaps Inoperative Approach/Landing checklist.",
            linkTarget: {
              checklistName: VisionJetAbnormalProceduresChecklistNames.FlapsInoperativeApproachLanding,
              checklistCategory: VisionJetChecklistCategory.AbnormalProcedures,
            },
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FLIGHTIDLEFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          { type: ChecklistItemType.Note, content: "Engine idle N2 is too low.", justification: Justification.Left },
          { type: ChecklistItemType.Challenge, content: "1. Maintain at least 70% N2.", response: null },
          { type: ChecklistItemType.Challenge, content: "2. Land as soon as practicable.", response: null },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELIMBALANCECaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Fuel imbalance greater than or equal to 15 gallons.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. Fuel Control Switch", response: "AUTO" },
          { type: ChecklistItemType.Challenge, content: "2. Fuel Quantity/Fuel Remaining", response: "COMPARE" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Refer to EIS for fuel quantity (based on level sensors).",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Challenge, content: "3. Fuel Control Switch", response: "FULLEST TANK" },
          { type: ChecklistItemType.Challenge, content: "4. Airspeed", response: "MAINTAIN FOR ADEQUATE ROLL CONTROL" },
          { type: ChecklistItemType.Subtitle, content: "If message extinguishes or imbalance decreases:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Continue flight.",
            response: null,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Fuel Control Switch",
            response: "AUTO",
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
          { type: ChecklistItemType.Subtitle, content: "If message persists or imbalance increases:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land as soon as possible.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELLOWLEFTRIGHTTOTALCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          { type: ChecklistItemType.Note, content: "Left fuel quantity is low, OR", justification: Justification.Left },
          {
            type: ChecklistItemType.Note,
            content: "Right fuel quantity is low, OR",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Note, content: "Total fuel quantity is low.", justification: Justification.Left },
          { type: ChecklistItemType.Challenge, content: "1. Fuel Quantity", response: "CHECK" },
          { type: ChecklistItemType.Challenge, content: "2. Thrust Lever", response: "REDUCE (MINIMUM REQUIRED)" },
          { type: ChecklistItemType.Challenge, content: "3. Land as soon as practicable.", response: null },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELPUMPFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          { type: ChecklistItemType.Note, content: "Fuel pump has failed.", justification: Justification.Left },
          { type: ChecklistItemType.Challenge, content: "1. Avoid abrupt thrust lever movements.", response: null },
          { type: ChecklistItemType.Challenge, content: "2. Land as soon as practicable.", response: null },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(VisionJetCautionAFChecklistNames.FUELPUMPONCaution, VisionJetChecklistCategory.CautionAF, [
        {
          type: ChecklistItemType.Note,
          content: "Fuel pump is ON due to low fuel pressure.",
          justification: Justification.Left,
        },
        { type: ChecklistItemType.Challenge, content: "1. Fuel Control Switch", response: "SWITCH TO OTHER TANK" },
        {
          type: ChecklistItemType.Challenge,
          content:
            "a. Refer to EIS for current tank selection (AUTO selection shown in white; LEFT/RIGHT selection shown in cyan).",
          response: null,
          justification: Justification.Indent1,
        },
        { type: ChecklistItemType.Challenge, content: "2. Fuel Control Switch", response: "AUTO" },
        { type: ChecklistItemType.Subtitle, content: "If message extinguishes and does not reappear:" },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Continue flight.",
          response: null,
          justification: Justification.Indent1,
        },
        { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        { type: ChecklistItemType.Subtitle, content: "If message persists or reappears:" },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Fuel Control Switch",
          response: "FULLEST TANK",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "b. Fuel Quantity",
          response: "MAINTAIN BALANCE",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "c. Land as soon as practicable.",
          response: null,
          justification: Justification.Indent1,
        },
        { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
      ]),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELQTYMISCOMPARECaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Sensed and totalized fuel quantity disagreement.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. Fuel Quantity/Fuel Remaining", response: "COMPARE" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Refer to EIS for fuel quantity (based on level sensors).",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELSELECTORFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Cannot determine fuel selector position.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. Fuel Control Switch", response: "CHECK LEFT/AUTO/RIGHT" },
          { type: ChecklistItemType.Subtitle, content: "If control is inoperable in all switch positions:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land as soon as possible.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
          {
            type: ChecklistItemType.Note,
            content:
              "CAUTION: A failed Fuel Control Switch will cause a fuel imbalance which will increase with continued flight.",
          },
          { type: ChecklistItemType.Subtitle, content: "If LEFT and RIGHT Switch positions are operable:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Fuel Quantity",
            response: "CHECK",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Fuel Control Switch",
            response: "FULLEST TANK, LEFT OR RIGHT ONLY",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Fuel Quantity",
            response: "MAINTAIN BALANCE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. Land as soon as possible.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELSHUTOFFFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Fuel shutoff valve not in commanded position.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Subtitle, content: "If during normal flight and engine is running:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land as soon as practicable.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
          { type: ChecklistItemType.Subtitle, content: "If airborne, and engine has shut down:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. ENGINE FIRE ACK",
            response: "LIFT GUARD, TOGGLE, CLOSE GUARD",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Perform Air Start Checklist.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
          { type: ChecklistItemType.Subtitle, content: "If during Engine Fire In Flight Checklist:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. ENGINE FIRE ACK",
            response: "CLOSE GUARD, LIFT GUARD, TOGGLE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Continue with Engine Fire In Flight Checklist.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELTEMPLOWCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Fuel temperature is low, increase OAT.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. Fuel Temp (L / R)", response: "CHECK" },
          { type: ChecklistItemType.Subtitle, content: "If in flight:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Climb or descend to warmer conditions.",
            response: null,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Note,
            content:
              "NOTE: Change altitude to increase OAT and increase fuel temperature. Due to temperature inversion, warmer temperatures may be at a higher altitude and cooler temperatures may be at a lower altitude.",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Fuel Temperature",
            response: "MONITOR",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Subtitle,
            content: "If message extinguishes:",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) No further action required.",
            response: null,
            justification: Justification.Indent2,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent2 },
          { type: ChecklistItemType.Subtitle, content: "If message persists:", justification: Justification.Indent1 },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Land as soon as practicable.",
            response: null,
            justification: Justification.Indent2,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent2 },
          { type: ChecklistItemType.Subtitle, content: "If on ground:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Warm aircraft to increase fuel temperature.",
            response: null,
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Indent1 },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELVALVE1FAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Fuel Control Valve #1 has failed.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. Fuel Quantity", response: "CHECK" },
          { type: ChecklistItemType.Challenge, content: "2. Fuel Control Switch", response: "FULLEST TANK" },
          { type: ChecklistItemType.Challenge, content: "3. Fuel Quantity", response: "MAINTAIN BALANCE" },
          { type: ChecklistItemType.Challenge, content: "4. Land as soon as practicable.", response: null },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELVALVE2FAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Fuel Control Valve #2 has failed.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. Fuel Quantity", response: "CHECK" },
          { type: ChecklistItemType.Challenge, content: "2. Fuel Control Switch", response: "AUTO" },
          { type: ChecklistItemType.Challenge, content: "3. Land as soon as practicable.", response: null },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELVALVEAUTOFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Note,
            content: "Auto fuel tank selection failure, use Manual mode.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. Fuel Quantity", response: "CHECK" },
          { type: ChecklistItemType.Challenge, content: "2. Fuel Control Switch", response: "FULLEST TANK" },
          { type: ChecklistItemType.Challenge, content: "3. Fuel Quantity", response: "MAINTAIN BALANCE" },
          { type: ChecklistItemType.Challenge, content: "4. Land as soon as practicable.", response: null },
          { type: ChecklistItemType.Note, content: "Procedure Complete", justification: Justification.Left },
        ],
        true,
      ),
    ];
  }
}
