import {
  ChecklistItemInteractionType,
  ChecklistItemType,
  Justification,
} from "@base/Shared/ChecklistSystem/ChecklistItem";
import { VisionJetChecklist, VisionJetChecklistCategory } from "../Checklist";
import { VisionJetAbnormalProceduresChecklistNames } from "../Checklists/VisionJetAbnormalProceduresChecklist";

export enum VisionJetCautionAFChecklistNames {
  AOAFAILCaution = "AOA FAIL Caution",
  AOAHEATFAILCaution = "AOA HEAT FAIL Caution",
  BLEEDAIRCaution = "BLEED AIR Caution",
  BLEEDLEAKCaution = "BLEED LEAK Caution",
  BLEEDOFFCaution = "BLEED OFF Caution",
  BLEEDOPENCaution = "BLEED OPEN Caution",
  BLEEDOVERPRESSURECaution = "BLEED OVERPRESSURE Caution",
  CABINLFENOTSETCaution = "CABIN LFE NOT SET Caution",
  CABINPRESSURECTRLFAILCaution = "CABIN PRESSURE CTRL FAIL Caution",
  DOOROPENEMEREXITCaution = "DOOR OPEN EMER EXIT Caution",
  ECSBLEEDHOTCaution = "ECS BLEED HOT Caution",
  ECSBLEEDOVERHEATCaution = "ECS BLEED OVERHEAT Caution",
  ECSCONTROLFAILCaution = "ECS CONTROL FAIL Caution",
  ECSTEMPBACKUPCaution = "ECS TEMP BACKUP Caution",
  EMERBATTERYFAILCaution = "EMER BATTERY FAIL Caution",
  EMERBATTERYFAULTCaution = "EMER BATTERY FAULT Caution",
  ENGINESTARTBATTEMPCaution = "ENGINE START BAT TEMP Caution",
  ENGINESTARTVOLTSCaution = "ENGINE START VOLTS Caution",
  ESSBUSVOLTSCaution = "ESS BUS VOLTS Caution",
  EXTERNALPOWERCONNECTEDCaution = "EXTERNAL POWER CONNECTED Caution",
  FADECNODISPATCHCaution = "FADEC NO DISPATCH Caution",
  FIREDETECTORFAILCaution = "FIRE DETECTOR FAIL Caution",
  FIREEXTLOWLRCaution = "FIRE EXT LOW L-R Caution",
  FLAPSAIRSPEEDINHIBITCaution = "FLAPS AIRSPEED INHIBIT Caution",
  FLAPSDISAGREECaution = "FLAPS DISAGREE Caution",
  FLAPSFAILCaution = "FLAPS FAIL Caution",
  FLAPSSELECTORFAILCaution = "FLAPS SELECTOR FAIL Caution",
  FLIGHTIDLEFAILCaution = "FLIGHT IDLE FAIL Caution",
  FUELIMBALANCECaution = "FUEL IMBALANCE Caution",
  FUELLOWLEFTRIGHTTOTALCaution = "FUEL LOW LEFT/RIGHT/TOTAL Caution",
  FUELPUMPFAILCaution = "FUEL PUMP FAIL Caution",
  FUELPUMPONCaution = "FUEL PUMP ON Caution",
  FUELQTYMISCOMPARECaution = "FUEL QTY MISCOMPARE Caution",
  FUELSELECTORFAILCaution = "FUEL SELECTOR FAIL Caution",
  FUELSHUTOFFFAILCaution = "FUEL SHUTOFF FAIL Caution",
  FUELTEMPLOWCaution = "FUEL TEMP LOW Caution",
  FUELVALVE1FAILCaution = "FUEL VALVE #1 FAIL Caution",
  FUELVALVE2FAILCaution = "FUEL VALVE #2 FAIL Caution",
  FUELVALVEAUTOFAILCaution = "FUEL VALVE AUTO FAIL Caution",
}

/** A utility class to generate Vision Jet Caution (A-F) checklist data. */
export class VisionJetCautionAFChecklists {
  /**
   * Generates the Vision Jet Caution (A-F) checklist data.
   * @returns An array of Vision Jet Caution (A-F) checklists.
   **/
  public static getChecklists(): VisionJetChecklist[] {
    return [
      new VisionJetChecklist(VisionJetCautionAFChecklistNames.AOAFAILCaution, VisionJetChecklistCategory.CautionAF, [
        {
          type: ChecklistItemType.Text,
          content: "AOA signal invalid.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Airspeed",
          color: "white",
          fontSize: 12,
          response: "REFER TO VREF SPEEDS TABLE",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "2. Avoid stalls, low airspeed, and uncoordinated or abrupt control inputs.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "3. Land as soon as practicable.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "VREF Speeds (KIAS)",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "-------------------------------------",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "FLAPS....4000lb 4500lb 5000lb 5550lb 6000lb",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "-------------------------------------",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "UP or",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "UNKNOWN....89....95....100.......104.....109",
          color: "white",
          fontSize: 12,
          blanksBelow: 1,
        },
        {
          type: ChecklistItemType.Text,
          content: "UP (Ice",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "Contamin.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "Airframe)....115....122...128.......135......140",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "50%...........82.....87.....91.........96.....100",
          color: "white",
          fontSize: 12,
          blanksBelow: 1,
        },
        {
          type: ChecklistItemType.Text,
          content: "50% (Ice",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "Contamin.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "Airframe).....98....104...110.......115.....120",
          color: "white",
          fontSize: 12,
          blanksBelow: 1,
        },
        {
          type: ChecklistItemType.Text,
          content: "100%..........71.....76.....81.........85......89",
          color: "white",
          fontSize: 12,
        },
      ]),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.AOAHEATFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "AOA heat failure.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. PROBE HT RIGHT CB (E4)",
            color: "white",
            fontSize: 12,
            response: "CYCLE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. PROBE HT LEFT CB (A8)",
            color: "white",
            fontSize: 12,
            response: "CYCLE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Avoid/exit icing conditions.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(VisionJetCautionAFChecklistNames.BLEEDAIRCaution, VisionJetChecklistCategory.CautionAF, [
        {
          type: ChecklistItemType.Text,
          content: "ECS bleed air system pressure low or failed.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. BLEED Switch",
          color: "white",
          fontSize: 12,
          response: "CYCLE FRESH, BLEED WITHIN < 1 SEC",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "2. Cabin Altitude",
          color: "white",
          fontSize: 12,
          response: "MONITOR",
        },
        {
          type: ChecklistItemType.Text,
          content: "If message extinguishes:",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Continue flight.",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "If message persists:",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Land as soon as practicable.",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(VisionJetCautionAFChecklistNames.BLEEDLEAKCaution, VisionJetChecklistCategory.CautionAF, [
        {
          type: ChecklistItemType.Text,
          content: "Bleed leak detected in tailcone.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Oxygen Mask",
          color: "white",
          fontSize: 12,
          response: "DON, 100%",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "2. BLEED Switch",
          color: "white",
          fontSize: 12,
          response: "FRESH",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "3. MIC SELECT Switch",
          color: "white",
          fontSize: 12,
          response: "MASK MIC",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "4. Wait 15 seconds.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "If message extinguishes:",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Descend and land as soon as practicable.",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "If message persists:",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Perform Emergency Descent checklist as required.",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "b. Thrust Lever",
          color: "white",
          fontSize: 12,
          response: "REDUCE (MINIMUM REQUIRED)",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "c. Land as soon as possible.",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(VisionJetCautionAFChecklistNames.BLEEDOFFCaution, VisionJetChecklistCategory.CautionAF, [
        {
          type: ChecklistItemType.Text,
          content: "Bleed air is switched to OFF/FRESH.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "If bleed is desired OFF:",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "a. No further action required.",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "If bleed is not desired OFF:",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "a. BLEED Switch",
          color: "white",
          fontSize: 12,
          response: "CYCLE TO BLEED",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "b. Verify message is extinguished.",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Text,
          content: "If message persists:",
          color: "white",
          fontSize: 15,
          justification: Justification.Indent1,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "(1) Cabin Altitude",
          color: "white",
          fontSize: 12,
          response: "MONITOR",
          justification: Justification.Indent2,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "(2) Monitor for CABIN ALTITUDE HIGH Warning.",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent2,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent2,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(VisionJetCautionAFChecklistNames.BLEEDOPENCaution, VisionJetChecklistCategory.CautionAF, [
        {
          type: ChecklistItemType.Text,
          content: "Shutoff solenoid failed to close.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. BLEED Switch",
          color: "white",
          fontSize: 12,
          response: "CYCLE",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "2. BLEED AIR SHUTOFF CB (D7)",
          color: "white",
          fontSize: 12,
          response: "CYCLE",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "3. Land as soon as practicable.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.BLEEDOVERPRESSURECaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "ECS bleed air system pressure high.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Thrust",
            color: "white",
            fontSize: 12,
            response: "REDUCE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. BLEED Switch",
            color: "white",
            fontSize: 12,
            response: "CYCLE FRESH, BLEED WITHIN < 1 SEC",
          },
          {
            type: ChecklistItemType.Text,
            content: "If message extinguishes:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Continue flight.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If message still persists:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Thrust",
            color: "white",
            fontSize: 12,
            response: "MINIMIZE A/R",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.CABINLFENOTSETCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Landing field elevation is not set.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Input destination airport in flight plan.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "OR",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Manually set Landing Field Elevation on GTC.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.CABINPRESSURECTRLFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Detected failure of CPCS Controller.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Cabin Altitude",
            color: "white",
            fontSize: 12,
            response: "MONITOR",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Monitor for CABIN ALTITUDE HIGH Warning.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.DOOROPENEMEREXITCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Emergency exit door is open.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If in flight:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Visually check window latch handle position.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If on ground:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Verify window is latched.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.ECSBLEEDHOTCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Bleed supply temperature is too hot.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Cabin Temp Knob",
            color: "white",
            fontSize: 12,
            response: "FULL COLD",
          },
          {
            type: ChecklistItemType.Text,
            content: "If message extinguishes:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. No further action required.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If message persists:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. TEMP BACKUP",
            color: "white",
            fontSize: 12,
            response: "SELECT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Verify message is extinguished.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.ECSBLEEDOVERHEATCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Bleed supply temperature is too hot.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Cabin Temp Knob",
            color: "white",
            fontSize: 12,
            response: "FULL COLD",
          },
          {
            type: ChecklistItemType.Text,
            content: "If message extinguishes:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. No further action required.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If message persists:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. TEMP BACKUP",
            color: "white",
            fontSize: 12,
            response: "SELECT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Verify message is extinguished.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "If message persists:",
            color: "white",
            fontSize: 15,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Thrust",
            color: "white",
            fontSize: 12,
            response: "REDUCE AS PRACTICAL",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(2) Verify message is extinguished.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Text,
            content: "If message persists or if TCV CONTROL FAIL is displayed:",
            color: "white",
            fontSize: 15,
            justification: Justification.Indent2,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(a) Oxygen Mask",
            color: "white",
            fontSize: 12,
            response: "DON, 100%",
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(b) BLEED",
            color: "white",
            fontSize: 12,
            response: "FRESH",
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(c) MIC SELECT Switch",
            color: "white",
            fontSize: 12,
            response: "MASK MIC",
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(d) Cabin Altitude",
            color: "white",
            fontSize: 12,
            response: "MONITOR",
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(e) Monitor for CABIN ALTITUDE HIGH Warning.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(f) Land as soon as practicable.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent3,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.ECSCONTROLFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "ECS controller has failed, OR",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "All cabin temperature sensors have failed, OR",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "All ECS fans in cabin have failed, OR",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "Bleed duct temperature sensor has failed.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. TEMP BACKUP",
            color: "white",
            fontSize: 12,
            response: "SELECT",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Cabin Temp Knob",
            color: "white",
            fontSize: 12,
            response: "ADJUST FOR CABIN COMFORT",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Monitor for ECS BLEED OVERHEAT Caution.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Perform ECS BLEED OVERHEAT Caution checklist, if required.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.ECSTEMPBACKUPCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Environmental control temperature backup mode.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If TEMP BACKUP mode engaged intentionally:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Cabin Temp Knob",
            color: "white",
            fontSize: 12,
            response: "ADJUST FOR CABIN COMFORT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Monitor for ECS BLEED HOT or ECS BLEED OVERHEAT cautions.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "If ECS BLEED HOT is displayed:",
            color: "white",
            fontSize: 15,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Perform ECS BLEED HOT caution checklist.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If ECS BLEED OVERHEAT is displayed:",
            color: "white",
            fontSize: 15,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Perform ECS BLEED OVERHEAT caution checklist.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If TEMP BACKUP mode engaged unintentionally:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. TEMP BACKUP",
            color: "white",
            fontSize: 12,
            response: "DESELECT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. ECS Controls",
            color: "white",
            fontSize: 12,
            response: "A/R",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.EMERBATTERYFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Emergency battery (Bat 2) service is required.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Exit IMC as soon as practicable.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "CAUTION: Emergency battery may be unavailable.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content:
              "NOTE: Battery FAIL indicates an internal condition which reduces capability of the battery. Possible conditions include a faulty temperature sensor, disconnected heater, etc.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.EMERBATTERYFAULTCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Emergency battery (Bat 2) fault detected.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. BAT 2 Switch",
            color: "white",
            fontSize: 12,
            response: "CYCLE",
          },
          {
            type: ChecklistItemType.Text,
            content: "If message extinguishes:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Continue flight.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Service aircraft as soon as practicable.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "If message persists:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Exit IMC as soon as practicable.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Contact Cirrus for corrective action.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "CAUTION: Emergency battery is unavailable.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content:
              "NOTE: Battery FAULT indicates a condition causing the battery to disable charging and/or discharging until corrected. Possible conditions include under-voltage, over-voltage, over-current, short-circuit, and over-temperature.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.ENGINESTARTBATTEMPCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Main battery (Bat 1) is below minimum start temp.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Wait until message extinguishes before attempting start.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.ENGINESTARTVOLTSCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Main battery (Bat 1) insufficient charge for reliable engine start.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "On ground only:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Battery service, preheat and/or charging is required.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.ESSBUSVOLTSCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Essential power bus voltage is low, OR",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "Loss of forward essential power bus voltage.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Perform GENERATOR 1 CURRENT Caution and GENERATOR 2 CURRENT Caution Checklists.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.EXTERNALPOWERCONNECTEDCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "External power is connected.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "On ground only:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "NOTE: Indicates external power is connected.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Ensure external power is removed before moving airplane.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FADECNODISPATCHCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Reference FADEC Fault Code Messages.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. ENG. IPS Switch (OAT < 50 F)",
            color: "white",
            fontSize: 12,
            response: "VERIFY ON",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Allow sufficient time for ice to clear from inlet probes.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. FADEC Reset via MFD Controller:",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. From Home, touch Aircraft Systems.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Touch the FADEC Stale Fault Reset Button.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "If message extinguishes:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. No further action required.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If message persists:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Continuance of flight is permitted.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FIREDETECTORFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Engine fire detector loop low pressure.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If in flight:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If on ground:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Do not dispatch.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FIREEXTLOWLRCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Pressure is low in both fire extinguishers.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If in flight:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If on ground:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Do not dispatch.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FLAPSAIRSPEEDINHIBITCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Flaps motion inhibited.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Airspeed",
            color: "white",
            fontSize: 12,
            response: "INCREASE OR REDUCE, AS REQUIRED",
          },
          {
            type: ChecklistItemType.Text,
            content: "OR",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Flaps",
            color: "white",
            fontSize: 12,
            response: "RETURN TO PREVIOUS POSITION",
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FLAPSDISAGREECaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Flaps are not within commanded position limits.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Flaps",
            color: "white",
            fontSize: 12,
            response: "CYCLE TO DESIRED POSITION",
          },
          {
            type: ChecklistItemType.Text,
            content: "If message extinguishes:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Continue flight.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If message persists:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Flaps",
            color: "white",
            fontSize: 12,
            response: "MONITOR POSITION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "If flap position is unknown:",
            color: "white",
            fontSize: 15,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Airspeed",
            color: "white",
            fontSize: 12,
            response: "BELOW 150 KIAS",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Perform Flaps Inoperative Approach/Landing checklist.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(VisionJetCautionAFChecklistNames.FLAPSFAILCaution, VisionJetChecklistCategory.CautionAF, [
        {
          type: ChecklistItemType.Text,
          content: "Flaps system inoperative, OR",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "Flaps position sensor miscompare, OR",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "Flaps sensors failed, position unknown, OR",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "Flaps have not reached the selected position.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Place flaps in last known or safe position.",
          color: "white",
          fontSize: 12,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "2. FLAPS CB (C2)",
          color: "white",
          fontSize: 12,
          response: "CYCLE",
        },
        {
          type: ChecklistItemType.Text,
          content: "If message persists:",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Perform Flaps Inoperative Approach/Landing checklist.",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FLAPSSELECTORFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Cannot determine flaps selector position.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Link,
            content: "1. Perform Flaps Inoperative Approach/Landing checklist.",
            color: "cyan",
            fontSize: 15,
            linkTarget: {
              checklistName: VisionJetAbnormalProceduresChecklistNames.FlapsInoperativeApproachLanding,
              checklistCategory: VisionJetChecklistCategory.AbnormalProcedures,
            },
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FLIGHTIDLEFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Engine idle N2 is too low.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Maintain at least 70% N2.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELIMBALANCECaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Fuel imbalance greater than or equal to 15 gallons.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Fuel Control Switch",
            color: "white",
            fontSize: 12,
            response: "AUTO",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Fuel Quantity/Fuel Remaining",
            color: "white",
            fontSize: 12,
            response: "COMPARE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Refer to EIS for fuel quantity (based on level sensors).",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Fuel Control Switch",
            color: "white",
            fontSize: 12,
            response: "FULLEST TANK",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Airspeed",
            color: "white",
            fontSize: 12,
            response: "MAINTAIN FOR ADEQUATE ROLL CONTROL",
          },
          {
            type: ChecklistItemType.Text,
            content: "If message extinguishes or imbalance decreases:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Continue flight.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Fuel Control Switch",
            color: "white",
            fontSize: 12,
            response: "AUTO",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If message persists or imbalance increases:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land as soon as possible.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELLOWLEFTRIGHTTOTALCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Left fuel quantity is low, OR",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "Right fuel quantity is low, OR",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "Total fuel quantity is low.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Fuel Quantity",
            color: "white",
            fontSize: 12,
            response: "CHECK",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Thrust Lever",
            color: "white",
            fontSize: 12,
            response: "REDUCE (MINIMUM REQUIRED)",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELPUMPFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Fuel pump has failed.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Avoid abrupt thrust lever movements.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(VisionJetCautionAFChecklistNames.FUELPUMPONCaution, VisionJetChecklistCategory.CautionAF, [
        {
          type: ChecklistItemType.Text,
          content: "Fuel pump is ON due to low fuel pressure.",
          color: "white",
          fontSize: 12,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Fuel Control Switch",
          color: "white",
          fontSize: 12,
          response: "SWITCH TO OTHER TANK",
        },
        {
          type: ChecklistItemType.Challenge,
          content:
            "a. Refer to EIS for current tank selection (AUTO selection shown in white; LEFT/RIGHT selection shown in cyan).",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "2. Fuel Control Switch",
          color: "white",
          fontSize: 12,
          response: "AUTO",
        },
        {
          type: ChecklistItemType.Text,
          content: "If message extinguishes and does not reappear:",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Continue flight.",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Text,
          content: "If message persists or reappears:",
          color: "white",
          fontSize: 15,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Fuel Control Switch",
          color: "white",
          fontSize: 12,
          response: "FULLEST TANK",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "b. Fuel Quantity",
          color: "white",
          fontSize: 12,
          response: "MAINTAIN BALANCE",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "c. Land as soon as practicable.",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Text,
          content: "Procedure Complete",
          color: "white",
          fontSize: 12,
          justification: Justification.Indent1,
          interactionType: ChecklistItemInteractionType.NoScrollStop,
        },
      ]),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELQTYMISCOMPARECaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Sensed and totalized fuel quantity disagreement.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Fuel Quantity/Fuel Remaining",
            color: "white",
            fontSize: 12,
            response: "COMPARE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Refer to EIS for fuel quantity (based on level sensors).",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELSELECTORFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Cannot determine fuel selector position.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Fuel Control Switch",
            color: "white",
            fontSize: 12,
            response: "CHECK LEFT/AUTO/RIGHT",
          },
          {
            type: ChecklistItemType.Text,
            content: "If control is inoperable in all switch positions:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land as soon as possible.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content:
              "CAUTION: A failed Fuel Control Switch will cause a fuel imbalance which will increase with continued flight.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If LEFT and RIGHT Switch positions are operable:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Fuel Quantity",
            color: "white",
            fontSize: 12,
            response: "CHECK",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Fuel Control Switch",
            color: "white",
            fontSize: 12,
            response: "FULLEST TANK, LEFT OR RIGHT ONLY",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Fuel Quantity",
            color: "white",
            fontSize: 12,
            response: "MAINTAIN BALANCE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. Land as soon as possible.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELSHUTOFFFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Fuel shutoff valve not in commanded position.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If during normal flight and engine is running:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If airborne, and engine has shut down:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. ENGINE FIRE ACK",
            color: "white",
            fontSize: 12,
            response: "LIFT GUARD, TOGGLE, CLOSE GUARD",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Perform Air Start Checklist.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If during Engine Fire In Flight Checklist:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. ENGINE FIRE ACK",
            color: "white",
            fontSize: 12,
            response: "CLOSE GUARD, LIFT GUARD, TOGGLE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Continue with Engine Fire In Flight Checklist.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELTEMPLOWCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Fuel temperature is low, increase OAT.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Fuel Temp (L / R)",
            color: "white",
            fontSize: 12,
            response: "CHECK",
          },
          {
            type: ChecklistItemType.Text,
            content: "If in flight:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Climb or descend to warmer conditions.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content:
              "NOTE: Change altitude to increase OAT and increase fuel temperature. Due to temperature inversion, warmer temperatures may be at a higher altitude and cooler temperatures may be at a lower altitude.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Fuel Temperature",
            color: "white",
            fontSize: 12,
            response: "MONITOR",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "If message extinguishes:",
            color: "white",
            fontSize: 15,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) No further action required.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If message persists:",
            color: "white",
            fontSize: 15,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Land as soon as practicable.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent2,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Text,
            content: "If on ground:",
            color: "white",
            fontSize: 15,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Warm aircraft to increase fuel temperature.",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            justification: Justification.Indent1,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELVALVE1FAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Fuel Control Valve #1 has failed.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Fuel Quantity",
            color: "white",
            fontSize: 12,
            response: "CHECK",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Fuel Control Switch",
            color: "white",
            fontSize: 12,
            response: "FULLEST TANK",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Fuel Quantity",
            color: "white",
            fontSize: 12,
            response: "MAINTAIN BALANCE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELVALVE2FAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Fuel Control Valve #2 has failed.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Fuel Quantity",
            color: "white",
            fontSize: 12,
            response: "CHECK",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Fuel Control Switch",
            color: "white",
            fontSize: 12,
            response: "AUTO",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetCautionAFChecklistNames.FUELVALVEAUTOFAILCaution,
        VisionJetChecklistCategory.CautionAF,
        [
          {
            type: ChecklistItemType.Text,
            content: "Auto fuel tank selection failure, use Manual mode.",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "1. Fuel Quantity",
            color: "white",
            fontSize: 12,
            response: "CHECK",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. Fuel Control Switch",
            color: "white",
            fontSize: 12,
            response: "FULLEST TANK",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "3. Fuel Quantity",
            color: "white",
            fontSize: 12,
            response: "MAINTAIN BALANCE",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "4. Land as soon as practicable.",
            color: "white",
            fontSize: 12,
          },
          {
            type: ChecklistItemType.Text,
            content: "Procedure Complete",
            color: "white",
            fontSize: 12,
            interactionType: ChecklistItemInteractionType.NoScrollStop,
          },
        ],
        true,
      ),
    ];
  }
}
