import { ChecklistItemType, Justification } from "@base/Shared/ChecklistSystem/ChecklistItem";
import { VisionJetChecklist, VisionJetChecklistCategory } from "../Checklist";

export enum VisionJetNormalChecklistNames {
  PreflightInspectionCabin = "Preflight Inspection - Cabin",
  PreflightInspectionEngine = "Preflight Inspection - Engine",
  PreflightInspectionLeftWing = "Preflight Inspection - Left Wing",
  PreflightInspectionFuselageEmpennage = "Preflight Inspection - Fuselage/Empennage",
  PreflightInspectionRightWing = "Preflight Inspection - Right Wing",
  PreflightInspectionNose = "Preflight Inspection - Nose",
  BeforeEngineStart = "Before Engine Start",
  EngineStart = "Engine Start",
  BeforeTaxi = "Before Taxi",
  BeforeTakeoff = "Before Takeoff",
  NormalTakeoff = "Normal Takeoff",
  ClimbCruise = "Climb / Cruise",
  DescentApproach = "Descent / Approach",
  BeforeLandingLanding = "Before Landing / Landing",
  GoAround = "Go-Around",
  AfterLanding = "After Landing",
  Shutdown = "Shutdown",
  IcingConditionsPreflightInspection = "Icing Conditions - Preflight Inspection",
  IcingConditionsBeforeTakeoff = "Icing Conditions - Before Takeoff",
  IPSActivation = "IPS Activation",
}

/** A utility class to generate Vision Jet Normal checklist data. */
export class VisionJetNormalChecklists {
  /**
   * Generates the Vision Jet Normal checklist data.
   * @returns An array of Vision Jet Normal checklists.
   **/
  public static getChecklists(): VisionJetChecklist[] {
    return [
      new VisionJetChecklist(
        VisionJetNormalChecklistNames.PreflightInspectionCabin,
        VisionJetChecklistCategory.Normal,
        [
          { type: ChecklistItemType.Subtitle, content: "1. Cabin" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Gust Lock",
            response: "REMOVED",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Cabin Door",
            response: "CHECK HINGE, LATCH AND SEAL CONDITION AND OPERATION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Egress Window",
            response: "SECURED AND PIN REMOVED",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. Seats, Interior Furnishing",
            response: "SECURED AND LOCKED",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Crew Seats",
            response: "LATCHED (FLIGHT RANGE POSITION)",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(2) Passenger Seats",
            response: "GRAB TOP, ROCK FORWARD AND AFT",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(3) Seat Levers, Latches",
            response: "VISUALLY INSPECT",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(4) Latch Pins (Child Seats)",
            response: "VISUALLY INSPECT",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(5) Console, Relief Station (if installed)",
            response: "SECURED AND LOCKED",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. Passenger Oxygen Masks",
            response: "STOWED",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "f. Required Documents",
            response: "CHECK",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "g. Fuel Control Switch",
            response: "AUTO",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "h. Alt Gear Extension Handle Cover Tab",
            response: "VISUALLY INSPECT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "i. ELT",
            response: "ARMED",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "j. Passenger Oxygen Switch",
            response: "AUTO",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "k. Fire Extinguisher",
            response: "CHARGED AND STOWED",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "l. Circuit Breaker Panels",
            response: "CHECK AND SET",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "m. Landing Gear",
            response: "DOWN",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "n. Bolster Switches",
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "o. Engine Knob",
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "p. BAT 2 Switch",
            response: "ON",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Verify the PFD, GTC 1, and GTC 2 power up.",
            response: null,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(2) Verify the MFD and GTC 3 do not power up.",
            response: null,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "q. BAT 1 Switch",
            response: "ON",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Verify ENGINE START BAT TEMP CAS message not present.",
            response: null,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Note,
            content:
              "NOTE: If ENGINE START BAT TEMP CAS message is displayed, perform ENGINE START BAT TEMP Caution checklist.",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(2) Verify the MFD and GTC 3 power up.",
            response: null,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Note,
            content:
              "NOTE: During the initialization process, expect the FADEC System annunciators to cycle On & Off and between channels.",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "r. Oxygen Pressure",
            response: "CHECK",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "s. OXYGEN MASTER",
            response: "ON",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "t. Oxygen Mask(s)",
            response: "CHECK",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Note,
            content:
              "NOTE: It is recommended to verify oxygen flow using the press to test feature on the mask on at least a monthly basis.",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "u. OXYGEN MIC SELECT",
            response: "CHECK AND SET",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "v. PROBE HEAT",
            response: "ON AND CHECK NO CAS THEN OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "w. Lights",
            response: "ON AND CHECK OPERATION THEN OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "x. Autopilot",
            response: "ON",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "y. AP DISC Button",
            response: "PRESS",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "z. AP and YD PFD Annunciations",
            response: "CONFIRM",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "aa. Aural AP Disconnect Tone",
            response: "CONFIRM",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "ab. Fuel Control Switch",
            response: "LEFT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Verify cyan L MAN selection box is displayed on the fuel section of the EIS.",
            response: null,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(2) Verify no FUEL VALVE CAS messages are displayed.",
            response: null,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "ac. Fuel Control Switch",
            response: "RIGHT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Verify cyan MAN R selection box is displayed on the fuel section of the EIS.",
            response: null,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(2) Verify no FUEL VALVE CAS messages are displayed.",
            response: null,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "ad. Fuel Control Switch",
            response: "AUTO",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Verify white L or R selection box is displayed in the fuel section of the EIS.",
            response: null,
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "ae. BAT 1 and BAT 2 Switches",
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "af. Test brakes by pressing brake pedals.",
            response: null,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Note,
            content: "WARNING: Do not fly aircraft if brake pedals on either side feel soft or spongy.",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Note,
            content:
              "NOTE: Complete the Icing Conditions Preflight Inspection Checklist if flight in icing conditions is expected or possible.",
            justification: Justification.Indent1,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetNormalChecklistNames.PreflightInspectionEngine,
        VisionJetChecklistCategory.Normal,
        [
          { type: ChecklistItemType.Subtitle, content: "2. Engine Preflight" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Engine Inlet",
            response: "CLEAR, COVER REMOVED, INSPECT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Engine Fan, Duct",
            response: "INSPECT, CLEAR",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Engine Inlet Probes",
            response: "INSPECT",
            justification: Justification.Indent1,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetNormalChecklistNames.PreflightInspectionLeftWing,
        VisionJetChecklistCategory.Normal,
        [
          { type: ChecklistItemType.Subtitle, content: "3. Left Forward Wing" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. LH Wing Root Vortex Generator",
            response: "CHECK",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. LH Fuel Collector Drain",
            response: "SAMPLE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. LH Wing Deicer and Leading Edge",
            response: "CONDITION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. LH MLG",
            response: "CONDITION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. LH MLG Door",
            response: "CONDITION, SECURITY",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "f. LH Fuel Tank Drain",
            response: "SAMPLE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "g. LH Fuel Cap",
            response: "CHECK FUEL LEVEL AND SECURE",
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Subtitle, content: "4. Left Wing Tip" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. LH Wing Tip, Strobe/Nav Lights",
            response: "CONDITION AND SECURITY",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Pitot Probe",
            response: "CLEAR, COVER REMOVED",
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Subtitle, content: "5. Left Wing Trailing Edge and Left Main Gear" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. LH Aileron, Roll Trim Tab",
            response: "CONDITION, MOTION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. T-Strip",
            response: "CHECK",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Static Wicks",
            response: "CHECK",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. LH Fuel Vent",
            response: "CLEAR",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. LH Flap",
            response: "CONDITION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "f. LH MLG Brakes, Wheel and Tire",
            response: "CONDITION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Brake Pads",
            response: "VISUALLY INSPECT FRICTIONAL MATERIAL",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(a) Center channel indicates thickness is greater than wear limit.",
            response: null,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(b) Edges are free from voids or large sections of material missing.",
            response: null,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(2) Brake Discs",
            response: "VISUALLY INSPECT SURFACE CONDITION",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(a) Surface appears smooth and uniform.",
            response: null,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content:
              "(b) Surface is free from irregularities such as large grooves, bumps, or deposits from brake pads.",
            response: null,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(3) Brake Lines",
            response: "VISUALLY INSPECT",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(a) Flexible lines for chafe and distress.",
            response: null,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(b) Lines for leaking.",
            response: null,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Note,
            content: 'NOTE: Refer to Section 8: Handling and Servicing, "Brake Overheat Inspection".',
            justification: Justification.Indent2,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetNormalChecklistNames.PreflightInspectionFuselageEmpennage,
        VisionJetChecklistCategory.Normal,
        [
          { type: ChecklistItemType.Subtitle, content: "6. Left Fuselage" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Baggage Circuit Breaker Panel",
            response: "CHECK AND SET",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Baggage",
            response: "CHECK, SECURE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Baggage Door",
            response: "SECURE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. External Power Service Door",
            response: "SECURE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. Static Ports",
            response: "CONDITION, CLEAR",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "f. Nacelle",
            response: "INSPECT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "g. Pylon Panels",
            response: "INSPECT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "h. Pylon NACA Inlet",
            response: "INSPECT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "i. Pylon Louver",
            response: "CLEAR",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "j. Antennae",
            response: "CONDITION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "k. OAT Probes",
            response: "CONDITION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "l. Ram Scoop Inlet",
            response: "CLEAR",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "m. Cabin Pressurization Static Port",
            response: "CLEAR",
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Subtitle, content: "7. Empennage" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Engine Nozzle",
            response: "INSPECT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Second LP Turbine",
            response: "INSPECT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Note,
            content:
              "NOTE: When inspecting the LP Turbine, look for Foreign Object Damage (FOD), overall damage, cracks, deformation, and evidence of pooled liquid (water, fuel, oil, etc.). If evidence of an oil leak is present, isolate the cause and correct. A flashlight may be necessary to accomplish this step.",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Stabilizer Deicers",
            response: "CONDITION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. Ruddervators, Pitch Servo Tabs",
            response: "CONDITION, MOTION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. Ventral Fins",
            response: "CONDITION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "f. Yaw SAS",
            response: "CONDITION, MOTION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "g. Static Wicks",
            response: "CHECK",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "h. Tail Lights",
            response: "CONDITION, SECURITY",
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Subtitle, content: "8. Right Fuselage" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Engine Preflight",
            response: "COMPLETE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Pylon NACA Inlet",
            response: "CLEAR",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(2) Engine Oil Level",
            response: "CHECK",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(3) Oil Cap",
            response: "CONDITION, SECURITY",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Right Fuselage",
            response: null,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Static Ports",
            response: "CONDITION, CLEAR",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(2) Overboard Drains",
            response: "CLEAR, NO LEAKS",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(3) Cabin Pressurization Static Port",
            response: "CLEAR",
            justification: Justification.Indent2,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetNormalChecklistNames.PreflightInspectionRightWing,
        VisionJetChecklistCategory.Normal,
        [
          { type: ChecklistItemType.Subtitle, content: "9. Right Wing Trailing Edge and Right Main Gear" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. RH MLG Brakes, Wheel and Tire",
            response: "CONDITION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(1) Brake Pads",
            response: "VISUALLY INSPECT FRICTIONAL MATERIAL",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(a) Center channel indicates thickness is greater than wear limit.",
            response: null,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(b) Edges are free from voids or large sections of material missing.",
            response: null,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(2) Brake Discs",
            response: "VISUALLY INSPECT SURFACE CONDITION",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(a) Surface appears smooth and uniform.",
            response: null,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content:
              "(b) Surface is free from irregularities such as large grooves, bumps, or deposits from brake pads.",
            response: null,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(3) Brake Lines",
            response: "VISUALLY INSPECT",
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(a) Flexible lines for chafe and distress.",
            response: null,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "(b) Lines for leaking.",
            response: null,
            justification: Justification.Indent3,
          },
          {
            type: ChecklistItemType.Note,
            content: 'NOTE: Refer to Section 8: Handling and Servicing, "Brake Overheat Inspection".',
            justification: Justification.Indent2,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. RH Flap",
            response: "CONDITION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Static Wicks",
            response: "CHECK",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. RH Fuel Vent",
            response: "CLEAR",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. RH Aileron, Roll Servo Tab",
            response: "CONDITION, MOVEMENT",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "f. T-Strip",
            response: "CHECK",
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Subtitle, content: "10. Right Wing Tip" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. RH Wing Tip, Strobe/Nav Lights",
            response: "CONDITION, SECURITY",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Pitot Probe",
            response: "CLEAR, COVER REMOVED",
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Subtitle, content: "11. Right Forward Wing" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. RH Fuel Cap",
            response: "CHECK FUEL LEVEL AND SECURE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. RH Fuel Tank Drain",
            response: "SAMPLE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. RH MLG Door",
            response: "CONDITION, SECURITY",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. RH MLG",
            response: "CONDITION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. RH Wing Deicer and Leading Edge",
            response: "CONDITION",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "f. RH Fuel Collector Drain",
            response: "SAMPLE",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "g. RH Wing Root Vortex Generator",
            response: "CHECK",
            justification: Justification.Indent1,
          },
        ],
      ),
      new VisionJetChecklist(VisionJetNormalChecklistNames.PreflightInspectionNose, VisionJetChecklistCategory.Normal, [
        { type: ChecklistItemType.Subtitle, content: "12. Nose, Right Side" },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Egress Window",
          response: "CONDITION, SECURITY (HANDLE FLUSH)",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "b. Air Conditioning Air Inlet",
          response: "CLEAR",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "c. Windshield Spray Bar",
          response: "CLEAR",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "d. AOA Vane",
          response: "CLEAR, COVER REMOVED, CONDITION, MOTION",
          justification: Justification.Indent1,
        },
        { type: ChecklistItemType.Subtitle, content: "13. Nose" },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Lightning Diverters (if equipped)",
          response: "CONDITION",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "b. Radome Spray Nozzle",
          response: "CONDITION",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "c. EVS Camera",
          response: "FREE & CLEAR",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "d. NLG",
          response: "CONDITION",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "e. NLG Door",
          response: "CONDITION, SECURITY",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "f. NLG Wheel, Tire",
          response: "CONDITION",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Note,
          content: "CAUTION: NLG Wheel must be pointing forward.",
          justification: Justification.Indent1,
        },
      ]),
      new VisionJetChecklist(VisionJetNormalChecklistNames.BeforeEngineStart, VisionJetChecklistCategory.Normal, [
        { type: ChecklistItemType.Challenge, content: "1. Preflight Inspection", response: "COMPLETE" },
        { type: ChecklistItemType.Challenge, content: "2. Door", response: "LATCHED" },
        { type: ChecklistItemType.Challenge, content: "3. Parking Brake", response: "A/R" },
        { type: ChecklistItemType.Challenge, content: "4. BAT 1 and BAT 2", response: "ON" },
        { type: ChecklistItemType.Challenge, content: "5. GEN 1 and GEN 2", response: "ON" },
        {
          type: ChecklistItemType.Challenge,
          content: "6. External GPU",
          response: "AS NEEDED, SET 28 VDC, 800 A (MINIMUM), 1000 A (MAXIMUM)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "7. Verify active FADEC channel is displayed below % Thrust indication.",
          response: null,
        },
      ]),
      new VisionJetChecklist(VisionJetNormalChecklistNames.EngineStart, VisionJetChecklistCategory.Normal, [
        { type: ChecklistItemType.Challenge, content: "1. Strobe Lights", response: "ON" },
        { type: ChecklistItemType.Challenge, content: "2. CAS Messages", response: "CHECK" },
        { type: ChecklistItemType.Challenge, content: "3. Thrust Lever", response: "IDLE" },
        { type: ChecklistItemType.Challenge, content: "4. Brakes", response: "HOLD" },
        { type: ChecklistItemType.Challenge, content: "5. Engine Knob", response: "RUN" },
        { type: ChecklistItemType.Challenge, content: "6. Fuel Pump", response: "CHECK" },
        {
          type: ChecklistItemType.Challenge,
          content: "a. Verify FUEL PUMP ON Advisory CAS is displayed.",
          response: null,
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "b. Audibly confirm pump is ON.",
          response: null,
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Challenge,
          content: "7. Verify ENGINE START BAT TEMP or ENGINE START VOLTS CAS message is not displayed.",
          response: null,
        },
        { type: ChecklistItemType.Challenge, content: "8. Engine Button", response: "PRESS" },
        { type: ChecklistItemType.Challenge, content: "9. Engine Instruments", response: "MONITOR" },
        {
          type: ChecklistItemType.Note,
          content:
            "CAUTION: At 25% N2, ensure positive N1 indication. Be prepared to abort start. If any of the following occur, abort start:",
          justification: Justification.Left,
        },
        {
          type: ChecklistItemType.Note,
          content: "ITT exceeds limits (red line).",
          justification: Justification.Indent1,
        },
        { type: ChecklistItemType.Note, content: "No N1 indication by 25% N2.", justification: Justification.Indent1 },
        {
          type: ChecklistItemType.Note,
          content: "No evidence of lightoff within 8 seconds.",
          justification: Justification.Indent1,
        },
        {
          type: ChecklistItemType.Note,
          content: "Low oil pressure after start.",
          justification: Justification.Indent1,
        },
        { type: ChecklistItemType.Challenge, content: "10. EIS", response: "CHECK ALL NORMAL" },
        { type: ChecklistItemType.Challenge, content: "11. Engine IPS", response: "A/R" },
        { type: ChecklistItemType.Challenge, content: "12. ECS Control Panel", response: "SET" },
        { type: ChecklistItemType.Challenge, content: "13. External GPU", response: "DISCONNECT" },
        { type: ChecklistItemType.Challenge, content: "14. Oxygen Master Switch", response: "VERIFY ON" },
        { type: ChecklistItemType.Challenge, content: "15. Avionics Initialization", response: "ALL INITS COMPLETE" },
        { type: ChecklistItemType.Challenge, content: "16. CAPS Pin", response: "REMOVE AND STOW" },
        { type: ChecklistItemType.Challenge, content: "17. Passengers", response: "BRIEF" },
        { type: ChecklistItemType.Challenge, content: "18. Seat Belts", response: "SECURED" },
        {
          type: ChecklistItemType.Note,
          content:
            "NOTE: The BLEED switch should not be set to BLEED until BAT 1 and BAT 2 have been ON for 2 minutes or more.",
          justification: Justification.Left,
        },
        { type: ChecklistItemType.Challenge, content: "19. BLEED Switch", response: "BLEED" },
      ]),
      new VisionJetChecklist(VisionJetNormalChecklistNames.BeforeTaxi, VisionJetChecklistCategory.Normal, [
        { type: ChecklistItemType.Challenge, content: "1. COM and NAV/GPS", response: "SET" },
        { type: ChecklistItemType.Challenge, content: "2. ATIS/Clearance", response: "OBTAIN" },
        { type: ChecklistItemType.Challenge, content: "3. Altimeter", response: "SET/CHECK" },
        { type: ChecklistItemType.Challenge, content: "4. Transponder", response: "SET" },
        { type: ChecklistItemType.Challenge, content: "5. Heading/Initial ALT", response: "SET" },
        { type: ChecklistItemType.Challenge, content: "6. Flight Controls", response: "FREE & CORRECT" },
        {
          type: ChecklistItemType.Note,
          content: "CAUTION: If TT2 HEAT FAIL Caution occurs with Engine IPS ON, dispatch is not allowed.",
          justification: Justification.Left,
        },
        {
          type: ChecklistItemType.Note,
          content:
            "NOTE: Turn Engine IPS ON if OAT is less than or equal to 41 F (5 C) with visible moisture or visibility of less than 1 mile.",
          justification: Justification.Left,
        },
        { type: ChecklistItemType.Challenge, content: "7. Trim", response: "SET" },
        { type: ChecklistItemType.Challenge, content: "8. Flaps", response: "50%" },
        { type: ChecklistItemType.Challenge, content: "9. Electric Roll Trim", response: "SET" },
        { type: ChecklistItemType.Challenge, content: "10. TO/GA Button", response: "PRESS" },
        { type: ChecklistItemType.Challenge, content: "11. Pitch Attitude", response: "10 DEGREES" },
        { type: ChecklistItemType.Challenge, content: "12. CAS Messages", response: "CHECK" },
        { type: ChecklistItemType.Challenge, content: "13. Seats must be in normal upright position.", response: null },
        { type: ChecklistItemType.Challenge, content: "14. Parking Brake", response: "RELEASE" },
        { type: ChecklistItemType.Challenge, content: "15. Brakes", response: "CHECK" },
      ]),
      new VisionJetChecklist(VisionJetNormalChecklistNames.BeforeTakeoff, VisionJetChecklistCategory.Normal, [
        { type: ChecklistItemType.Challenge, content: "1. Departure Briefing", response: "COMPLETE" },
        { type: ChecklistItemType.Challenge, content: "2. Landing Lights", response: "A/R" },
        {
          type: ChecklistItemType.Note,
          content:
            "CAUTION: Above 41 degrees F (5 degrees C), probe heat may only be ON for 5 minutes (continuous) during ground operations. Extended use in warmer temperatures may damage the composite structure adjacent to the pitot probe.",
          justification: Justification.Left,
        },
        { type: ChecklistItemType.Challenge, content: "3. PROBE HEAT Switch", response: "ON" },
        { type: ChecklistItemType.Challenge, content: "4. ENGINE IPS Switch", response: "A/R" },
        { type: ChecklistItemType.Challenge, content: "5. WING/STAB IPS Switch", response: "OFF" },
        { type: ChecklistItemType.Challenge, content: "6. CAS Messages", response: "CHECK" },
        { type: ChecklistItemType.Challenge, content: "7. Trim", response: "SET" },
        { type: ChecklistItemType.Challenge, content: "8. Flaps", response: "50%" },
        {
          type: ChecklistItemType.Challenge,
          content: "9. Verify TAKEOFF EMER BAT CAS message is not displayed.",
          response: null,
        },
        { type: ChecklistItemType.Challenge, content: "10. Multi-Function Windows", response: "CONFIGURE" },
      ]),
      new VisionJetChecklist(VisionJetNormalChecklistNames.NormalTakeoff, VisionJetChecklistCategory.Normal, [
        { type: ChecklistItemType.Challenge, content: "1. Brakes", response: "HOLD" },
        { type: ChecklistItemType.Challenge, content: "2. Thrust Lever", response: "T/O" },
        {
          type: ChecklistItemType.Challenge,
          content: "3. Thrust Setting (N1% Indicator)",
          response: "ALIGNED w/ BUG (T)",
        },
        { type: ChecklistItemType.Challenge, content: "4. Engine Instruments", response: "CHECK NORMAL" },
        { type: ChecklistItemType.Challenge, content: "5. Brakes", response: "RELEASE" },
        { type: ChecklistItemType.Challenge, content: "6. VR", response: "85 KIAS" },
        { type: ChecklistItemType.Challenge, content: "7. Pitch Attitude", response: "10 DEGREES" },
        { type: ChecklistItemType.Challenge, content: "8. Landing Gear", response: "UP w/ POSITIVE RATE OF CLIMB" },
        { type: ChecklistItemType.Challenge, content: "9. Flaps", response: "UP AT 115 KIAS, CLEAR OF OBSTACLES" },
        { type: ChecklistItemType.Challenge, content: "10. Airspeed", response: "PER CLIMB TABLES" },
      ]),
      new VisionJetChecklist(VisionJetNormalChecklistNames.ClimbCruise, VisionJetChecklistCategory.Normal, [
        { type: ChecklistItemType.Subtitle, content: "Climb" },
        { type: ChecklistItemType.Challenge, content: "1. Thrust Lever", response: "MCT" },
        { type: ChecklistItemType.Challenge, content: "2. Engine Parameters", response: "MONITOR" },
        { type: ChecklistItemType.Challenge, content: "3. Cabin Pressure", response: "MONITOR" },
        { type: ChecklistItemType.Challenge, content: "4. Ice Protection", response: "A/R" },
        {
          type: ChecklistItemType.Challenge,
          content: "5. Altimeter Transition Altitude",
          response: "SET 29.92 INCHES / 1013 MB",
        },
        { type: ChecklistItemType.Subtitle, content: "Cruise" },
        { type: ChecklistItemType.Challenge, content: "1. Thrust Lever", response: "A/R" },
        { type: ChecklistItemType.Challenge, content: "2. Ice Protection", response: "A/R" },
        { type: ChecklistItemType.Subtitle, content: "In RVSM Airspace:" },
        { type: ChecklistItemType.Subtitle, content: "Wing/Stab IPS ON:", justification: Justification.Indent1 },
        {
          type: ChecklistItemType.Challenge,
          content: "(1) Contact ATC and notify of non-RVSM status.",
          response: null,
          justification: Justification.Indent2,
        },
        { type: ChecklistItemType.Challenge, content: "3. EIS", response: "MONITOR" },
      ]),
      new VisionJetChecklist(VisionJetNormalChecklistNames.DescentApproach, VisionJetChecklistCategory.Normal, [
        { type: ChecklistItemType.Subtitle, content: "Descent" },
        { type: ChecklistItemType.Challenge, content: "1. Thrust Lever", response: "A/R" },
        { type: ChecklistItemType.Challenge, content: "2. Landing Field Elevation", response: "CHECK" },
        { type: ChecklistItemType.Challenge, content: "3. Ice Protection", response: "A/R" },
        { type: ChecklistItemType.Challenge, content: "4. Altimeter Transition Altitude", response: "LOCAL SETTING" },
        { type: ChecklistItemType.Challenge, content: "5. Seats and Seat Belts", response: "SECURE" },
        { type: ChecklistItemType.Challenge, content: "6. Brake Pressure", response: "CHECK" },
        { type: ChecklistItemType.Subtitle, content: "Approach" },
        { type: ChecklistItemType.Challenge, content: "1. Approach Briefing", response: "COMPLETE" },
        {
          type: ChecklistItemType.Challenge,
          content: "2. All seats must be in normal upright position.",
          response: null,
        },
        { type: ChecklistItemType.Challenge, content: "3. Ice Protection", response: "A/R" },
        { type: ChecklistItemType.Challenge, content: "4. Lights", response: "A/R" },
        { type: ChecklistItemType.Challenge, content: "5. Flaps", response: "50%" },
        { type: ChecklistItemType.Challenge, content: "6. Airspeed", response: "140 KIAS" },
      ]),
      new VisionJetChecklist(VisionJetNormalChecklistNames.BeforeLandingLanding, VisionJetChecklistCategory.Normal, [
        { type: ChecklistItemType.Subtitle, content: "Before Landing" },
        { type: ChecklistItemType.Challenge, content: "1. Landing Gear", response: "DOWN AND LOCKED" },
        { type: ChecklistItemType.Challenge, content: "2. Flaps", response: "A/R" },
        { type: ChecklistItemType.Challenge, content: "3. Cabin Pressure Diff", response: "APPROX 0 PSI" },
        { type: ChecklistItemType.Challenge, content: "4. WINDSHLD IPS Switch", response: "OFF" },
        {
          type: ChecklistItemType.Note,
          content: "NOTE: IPS fluid decreases flight visibility.",
          justification: Justification.Left,
        },
        { type: ChecklistItemType.Challenge, content: "5. Autopilot", response: "OFF" },
        { type: ChecklistItemType.Challenge, content: "6. Airspeed", response: "VREF TO VREF+10" },
        { type: ChecklistItemType.Challenge, content: "7. Brake Pressure", response: "CHECK" },
        { type: ChecklistItemType.Subtitle, content: "Landing" },
        {
          type: ChecklistItemType.Challenge,
          content: "1. Flaps",
          response: "100% (50%, IF AIRFRAME IS ICE CONTAMINATED)",
        },
        {
          type: ChecklistItemType.Challenge,
          content: "2. Airspeed",
          response: "VREF (REFER TO LANDING CONSIDERATIONS TABLE)",
        },
        { type: ChecklistItemType.Challenge, content: "3. Thrust Lever", response: "A/R" },
        { type: ChecklistItemType.Note, content: "After landing:", justification: Justification.Left },
        { type: ChecklistItemType.Challenge, content: "4. Brakes", response: "A/R" },
      ]),
      new VisionJetChecklist(VisionJetNormalChecklistNames.GoAround, VisionJetChecklistCategory.Normal, [
        { type: ChecklistItemType.Challenge, content: "1. Thrust Lever", response: "T/O" },
        { type: ChecklistItemType.Challenge, content: "2. TO/GA Button", response: "PRESS" },
        { type: ChecklistItemType.Challenge, content: "3. Pitch Attitude", response: "7 DEGREES" },
        { type: ChecklistItemType.Challenge, content: "4. Flaps", response: "50%" },
        { type: ChecklistItemType.Challenge, content: "5. Landing Gear", response: "UP w/ POSITIVE RATE OF CLIMB" },
        { type: ChecklistItemType.Challenge, content: "6. Airspeed", response: "VX" },
        { type: ChecklistItemType.Challenge, content: "7. Flaps", response: "UP AT 115 KIAS, CLEAR OF OBSTACLES" },
        { type: ChecklistItemType.Challenge, content: "8. Climb Out", response: "RESUME NORMAL CLIMB OUT" },
      ]),
      new VisionJetChecklist(VisionJetNormalChecklistNames.AfterLanding, VisionJetChecklistCategory.Normal, [
        { type: ChecklistItemType.Challenge, content: "1. Flaps", response: "UP" },
        { type: ChecklistItemType.Challenge, content: "2. WING/STAB IPS Switch", response: "OFF" },
        { type: ChecklistItemType.Challenge, content: "3. ENGINE IPS Switch", response: "A/R" },
        {
          type: ChecklistItemType.Note,
          content:
            "CAUTION: Above 41 degrees F (5 degrees C), probe heat may only be ON for 5 minutes (continuous) during ground operations. Extended use in warmer temperatures may damage the composite structure adjacent to the pitot probe.",
          justification: Justification.Left,
        },
        { type: ChecklistItemType.Challenge, content: "4. PROBE HEAT Switch", response: "OFF" },
        { type: ChecklistItemType.Challenge, content: "5. External Lights", response: "A/R" },
        { type: ChecklistItemType.Challenge, content: "6. Brakes", response: "CHECK" },
      ]),
      new VisionJetChecklist(VisionJetNormalChecklistNames.Shutdown, VisionJetChecklistCategory.Normal, [
        { type: ChecklistItemType.Challenge, content: "1. Thrust Lever", response: "IDLE" },
        { type: ChecklistItemType.Challenge, content: "2. ENGINE IPS Switch", response: "OFF" },
        { type: ChecklistItemType.Challenge, content: "3. BLEED Switch", response: "FRESH" },
        { type: ChecklistItemType.Challenge, content: "4. OXYGEN MASTER", response: "OFF" },
        { type: ChecklistItemType.Challenge, content: "5. Lights", response: "OFF" },
        {
          type: ChecklistItemType.Note,
          content:
            "CAUTION: To avoid unnecessary FADEC System faults, do not remove aircraft power until N2 is less than 24%.",
          justification: Justification.Left,
        },
        { type: ChecklistItemType.Challenge, content: "6. GEN 1 and GEN 2", response: "OFF" },
        { type: ChecklistItemType.Challenge, content: "7. Engine Knob", response: "OFF" },
        { type: ChecklistItemType.Challenge, content: "8. Engine Button", response: "PRESS" },
        { type: ChecklistItemType.Challenge, content: "9. N2", response: "BELOW 24%" },
        { type: ChecklistItemType.Challenge, content: "10. CAPS Pin", response: "REPLACE" },
        { type: ChecklistItemType.Challenge, content: "11. BAT 1 and BAT 2", response: "OFF" },
        { type: ChecklistItemType.Challenge, content: "12. Parking Brake", response: "A/R" },
        { type: ChecklistItemType.Challenge, content: "13. Egress Door Pin", response: "REPLACE" },
        { type: ChecklistItemType.Challenge, content: "14. Airplane", response: "SECURE" },
        { type: ChecklistItemType.Challenge, content: "15. Engine Cycles", response: "COUNT AND RECORD" },
      ]),
      new VisionJetChecklist(
        VisionJetNormalChecklistNames.IcingConditionsPreflightInspection,
        VisionJetChecklistCategory.Normal,
        [
          { type: ChecklistItemType.Subtitle, content: "1. Cabin" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Circuit Breakers",
            response: "SET",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. BAT 1 and BAT 2",
            response: "ON",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. WINDSHLD IPS MAX Switch",
            response: "PRESS AND HOLD UNTIL FLUID EXITS SPRAY BAR",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "d. IPS Fluid",
            response: "VERIFY QUANTITY",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Note,
            content: "NOTE: IPS fluid minimum dispatch quantity is 1 U.S. gallon.",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "e. ICE Light",
            response: "ON",
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Subtitle, content: "2. Exterior" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. ICE Light",
            response: "CHECK",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. Nose Section",
            response: "VERIFY EVIDENCE OF IPS FLUID",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Note,
            content: "NOTE: Fluid will spray clear of the airframe.",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. Engine Inlet",
            response: "INSPECT",
            justification: Justification.Indent1,
          },
          { type: ChecklistItemType.Subtitle, content: "3. Cabin" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. PROBE HEAT",
            response: "ON AND CHECK NO CAS THEN OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "b. ICE Light",
            response: "OFF",
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Challenge,
            content: "c. BAT 1 and BAT 2",
            response: "OFF",
            justification: Justification.Indent1,
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetNormalChecklistNames.IcingConditionsBeforeTakeoff,
        VisionJetChecklistCategory.Normal,
        [
          {
            type: ChecklistItemType.Challenge,
            content: "1. ENGINE IPS Switch",
            response: "ON AND CHECK OPERATION AND NO CAS THEN A/R",
          },
          {
            type: ChecklistItemType.Challenge,
            content: "2. WING/STAB IPS Switch",
            response: "ON AND CHECK OPERATION AND NO CAS THEN OFF",
          },
        ],
      ),
      new VisionJetChecklist(
        VisionJetNormalChecklistNames.IPSActivation,
        VisionJetChecklistCategory.Normal,
        [
          {
            type: ChecklistItemType.Subtitle,
            content: "OAT is less than or equal to 41 F (5 C) with visible moisture or visibility less than 1 mile:",
          },
          { type: ChecklistItemType.Subtitle, content: "IN FLIGHT:" },
          { type: ChecklistItemType.Challenge, content: "1. PROBE HEAT Switch", response: "ON" },
          { type: ChecklistItemType.Challenge, content: "2. ENGINE IPS Switch", response: "ON" },
          { type: ChecklistItemType.Challenge, content: "3. WING/STAB IPS Switch", response: "OFF" },
          { type: ChecklistItemType.Challenge, content: "4. WINDSHLD IPS Switch", response: "OFF" },
          { type: ChecklistItemType.Subtitle, content: "ON GROUND:" },
          { type: ChecklistItemType.Challenge, content: "1. PROBE HEAT Switch", response: "ON" },
          { type: ChecklistItemType.Challenge, content: "2. ENGINE IPS Switch", response: "ON" },
          { type: ChecklistItemType.Subtitle, content: "At first sign of ice:" },
          {
            type: ChecklistItemType.Note,
            content:
              "WARNING: Ice contamination of the lifting surfaces may result in an inoperable or inadequate stall warning, which may cause an inadvertent stall. The resulting stall may lead to loss of control of the airplane. The WING/STAB IPS switch must remain at the ON position until either the entire wing is free of ice accretion or ice is no longer accreting on the aircraft. Stall Warning offset must remain ON until entire airframe is free of ice.",
            justification: Justification.Left,
          },
          {
            type: ChecklistItemType.Note,
            content:
              "NOTE: The left wing leading edge is the primary reference area for determining if ice is accumulating on the aircraft. Ice may be visible on other areas of the aircraft as well, such as the forward windshield.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "1. PROBE HEAT Switch", response: "ON" },
          { type: ChecklistItemType.Challenge, content: "2. ENGINE IPS Switch", response: "ON" },
          { type: ChecklistItemType.Challenge, content: "3. WING/STAB IPS Switch", response: "ON" },
          { type: ChecklistItemType.Subtitle, content: "In RVSM Airspace:" },
          {
            type: ChecklistItemType.Challenge,
            content: "a. Contact ATC and notify of non-RVSM status.",
            response: null,
            justification: Justification.Indent1,
          },
          {
            type: ChecklistItemType.Note,
            content: "NOTE: Verify STALL SPEED HIGH CAS Advisory is present.",
            justification: Justification.Left,
          },
          { type: ChecklistItemType.Challenge, content: "4. WINDSHLD IPS Switch", response: "ON" },
        ],
        true,
      ),
    ];
  }
}
