import {ChecklistItemType, Justification} from '@base/Shared/ChecklistSystem/ChecklistItem';
import {TbmChecklist, TbmChecklistCategory} from "../TbmChecklist";

export enum AmplifiedChecklistNames {
  PreflightInspection = 'Preflight inspection',
  InsideInspection = 'Inside inspection',
  BeforeStartingEngine = 'Before starting engine',
  EngineStart = 'Engine start',
  Motoring = 'Motoring',
  MotoringFollowedByEngineStart = 'Motoring followed by an engine start',
  AfterEngineStartWithGPU = 'After engine start with GPU',
  AfterEngineStart = 'After engine start',
  InFlightAvailableOxygenQuantity = 'In-flight available oxygen quantity',
  BeforeTaxiing = 'Before taxiing',
  Taxiing = 'Taxiing',
  BeforeLineUp = 'Before line up',
  NormalTakeoff = 'Normal takeoff',
  ShortTakeoff = 'Short takeoff',
  AfterTakeoff = 'After takeoff',
  Climb = 'Climb',
  Cruise = 'Cruise',
  BeforeDescent = 'Before descent',
  Approach = 'Approach',
  FinalOrDownwind = 'Final approach (in GS) or downwind leg (VMC)',
  ShortFinal = 'Short final (≈ 500 ft)',
  Landing = 'Landing',
  GoAroundAPOff = 'Go-around with AP OFF',
  GoAroundAPOn = 'Go-around with AP ON',
  TouchAndGo = 'Touch and go',
  RunwayClear = 'Runway clear',
  Shutdown = 'Shutdown',
  OutsideInspectionAfterShutdown = 'Outside inspection after shutdown',
}

/** A utility class to generate normal checklist data. */
export class AmplifiedChecklists {
  /**
   * Generates the normal checklist data.
   * @returns An array of normal checklists.
   **/
  public static getChecklists(): TbmChecklist[] {
    return [
      new TbmChecklist(
        AmplifiedChecklistNames.InsideInspection,
        TbmChecklistCategory.Amplified,
        [
          { type: ChecklistItemType.PlainText, content: 'After completion of preflight inspection. Initial inside inspection and outside inspection performed.' },
          { type: ChecklistItemType.Challenge, content: '1. Cabin door\nand pilot door,\nif installed', response: 'Closed / Locked' },
          { type: ChecklistItemType.Challenge, content: '2. Baggage', response: 'Stowed' },
          { type: ChecklistItemType.Challenge, content: '3. EMERGENCY\nEXIT pin', response: 'Removed' },
          { type: ChecklistItemType.Challenge, content: '4. Seats,\npedals, harness', response: 'Adjust / Lock' },
          { type: ChecklistItemType.Caution, content: 'CAUTION: It is mandatory to set the seat to the highest position before adjusting\nthe front seats fore or aft. Otherwise, moving the seat may damage the\nupholstery on the side panels.' },
          { type: ChecklistItemType.Challenge, content: 'Pilot seat and\nR.H. front\nseat, if occupied', response: 'Adjust', justification: Justification.Indent1 },
          { type: ChecklistItemType.Note, content: 'NOTE: Adjust seats and harnesses to ensure access to flight controls. The pilot at L.H.\nposition must be able to easily reach the A/C and PRESSURIZATION panel.' },
          { type: ChecklistItemType.Challenge, content: '5. Height\nadjustment', response: 'Max. UP', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '6. Fore and aft\nadjustment', response: 'Adjust and check\nlocking', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '7. Height\nadjustment', response: 'Adjust', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '8. L.H and R.H.\npedals', response: 'Adjust', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '9. Pilot and\npassengers\nbelts and\nharnesses', response: 'Fasten', justification: Justification.Indent1 },
          { type: ChecklistItemType.Note, content: 'NOTE: Check for the correct locking of belt buckles for the pilot and passengers ; as\nwell as automatic locking of shoulder harness by exerting a rapid pull on the\nharness.\nIf airbags are installed, unoccupied seat belts need to be strapped. It is\nprohibited to fly with these belts unstrapped.' },
          { type: ChecklistItemType.Challenge, content: '10. PASSENGER\nOXYGEN switch', response: 'STBY' },
          { type: ChecklistItemType.Challenge, content: '11. OXYGEN\nswitch', response: 'ON' },
          { type: ChecklistItemType.Note, content: 'NOTE: Make sure to set on STBY the PASSENGER OXYGEN switch before setting\nthe OXYGEN switch to ON to avoid passengers mask deployment.' },
          { type: ChecklistItemType.Challenge, content: '12. Crew oxygen\nmasks', response: 'Test' },
          { type: ChecklistItemType.Note, content: 'NOTE: Press push-button PRESS TO TEST : the blinker shall turn red momentarily,\nthen turns transparent.' },
          { type: ChecklistItemType.Challenge, content: '13. EXT LIGHTS\npanel', response: 'All OFF' },
          { type: ChecklistItemType.Challenge, content: '14. INT LIGHTS\npanel', response: 'All OFF' },
          { type: ChecklistItemType.Challenge, content: '15. DIMMER\nswitch', response: 'OFF' },
          { type: ChecklistItemType.Challenge, content: '16. CABIN switch', response: 'OFF' },
          { type: ChecklistItemType.Challenge, content: '17. ACCESS\nswitch', response: 'OFF' },
          { type: ChecklistItemType.Challenge, content: '18. PANEL\nrheostat', response: 'Fully turned to\nthe left' },
          { type: ChecklistItemType.Challenge, content: '19. All lights', response: 'OFF' },
          { type: ChecklistItemType.Challenge, content: '20. Crash lever', response: 'Down' },
          { type: ChecklistItemType.Challenge, content: '21. STARTER\nswitch', response: 'OFF' },
          { type: ChecklistItemType.Note, content: 'NOTE: If not, starter is going to operate as soon as SOURCE selector is positioned on\nBATT or GPU.' },
          { type: ChecklistItemType.Challenge, content: '22. IGNITION\nswitch', response: 'AUTO' },
          { type: ChecklistItemType.Note, content: 'NOTE: The IGNITION switch is normally selected to AUTO. This ensures ignition,\nwhenever the starter is activated.' },
          { type: ChecklistItemType.Challenge, content: '23. AUX BP\nswitch', response: 'OFF' },
          { type: ChecklistItemType.Challenge, content: '24. FUEL SEL\nswitch', response: 'MAN' },
          { type: ChecklistItemType.Challenge, content: '25. AP / TRIMS\nswitch', response: 'OFF' },
          { type: ChecklistItemType.Challenge, content: '26. A/C switch', response: 'OFF' },
          { type: ChecklistItemType.Challenge, content: '27. SEATS HTRS\nMASTER switch', response: 'OFF' },
          { type: ChecklistItemType.Challenge, content: '28. CB LIGHTS\nswitch', response: 'OFF' },
          { type: ChecklistItemType.Challenge, content: '29. MICRO / MASK\nswitch', response: 'MICRO / Guarded' },
          { type: ChecklistItemType.Challenge, content: '30. DE ICE\nSYSTEM panel', response: 'All OFF' },
          { type: ChecklistItemType.Challenge, content: '31. INERT SEP\nswitch', response: 'OFF' },
          { type: ChecklistItemType.Challenge, content: '32. PARK BRAKE', response: 'Reset / ON' },
          { type: ChecklistItemType.Challenge, content: '33. LANDING GEAR\nlever', response: 'DN' },
          { type: ChecklistItemType.Challenge, content: '34. DUMP switch', response: 'NORM / Guarded' },
          { type: ChecklistItemType.Challenge, content: '35. BLEED switch', response: 'OFF' },
          { type: ChecklistItemType.Challenge, content: '36. HOT AIRFLOW\ndistributor', response: 'Fully turned to\nthe right' },
          { type: ChecklistItemType.Challenge, content: '37. Pitch trim\nwheel', response: 'Check' },
          { type: ChecklistItemType.Caution, content: 'CAUTION: Make sure that MAN OVRD control is backward to avoid\novertemperature risks at start.' },
          { type: ChecklistItemType.Challenge, content: '38. MAN OVRD\ncontrol', response: 'Full backward\n(notched)' },
          { type: ChecklistItemType.Caution, content: 'CAUTION: When the engine is shut down, the THROTTLE must not be moved into\nthe reverse area.' },
          { type: ChecklistItemType.Challenge, content: '39. THROTTLE', response: 'CUT OFF' },
          { type: ChecklistItemType.Challenge, content: '40. FUEL TANK\nSELECTOR', response: 'Open / L or R' },
          { type: ChecklistItemType.Challenge, content: '41. ALTERNATE\nSTATIC SOURCE\nselector', response: 'Normal / Pushed' },
          { type: ChecklistItemType.Challenge, content: '42. EMERGENCY\nRAM AIR', response: 'Closed / Pushed' },
          { type: ChecklistItemType.Challenge, content: '43. ESS BUS TIE\nswitch', response: 'NORM / Guarded' },
          { type: ChecklistItemType.Challenge, content: '44. Breakers', response: 'All pushed' },
          { type: ChecklistItemType.Challenge, content: '45. EMERGENCY\nLANDING GEAR\nlever', response: 'Check' },
        ],
      ),
      new TbmChecklist(
        AmplifiedChecklistNames.BeforeStartingEngine,
        TbmChecklistCategory.Amplified,
        [
          { type: ChecklistItemType.PlainText, content: 'Check that the weight and balance are within the correct limits. Brief passengers about use of seat belts and the emergency oxygen system, as well as opening the access door and the emergency exit.' },
          { type: ChecklistItemType.Challenge, content: '1. Preflight\ninspection', response: 'Completed' },
          { type: ChecklistItemType.Challenge, content: '2. Crash lever', response: 'Up' },
          { type: ChecklistItemType.Challenge, content: '3. ATIS', response: 'Copied' },
          { type: ChecklistItemType.Challenge, content: '4. Start\nclearance', response: 'As required' },
          { type: ChecklistItemType.Challenge, content: '5. SOURCE\nselector', response: 'BATT (battery\nstart) or GPU\n(GPU start)' },
          { type: ChecklistItemType.PlainText, content: 'If one screen (L or R PFD, or MFD) is missing:' },
          { type: ChecklistItemType.Challenge, content: '6. SOURCE\nselector', response: 'OFF', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '7. Wait for 30 seconds', response: null, justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '8. SOURCE\nselector', response: 'BATT (battery\nstart) or GPU\n(GPU start)', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: 'If GPU use:' },
          { type: ChecklistItemType.Challenge, content: '9.GPU DOOR', response: 'Check ON', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '10. Voltmeter', response: 'Check 28 Volts ±\n0.5 Volt', justification: Justification.Indent1 },
          { type: ChecklistItemType.Note, content: 'NOTE: Voltage is higher than 24.5 Volts which corresponds to the voltage in case of\nbattery use.' },
          { type: ChecklistItemType.PlainText, content: 'If battery use:' },
          { type: ChecklistItemType.Challenge, content: '11. Battery\nvoltage', response: 'Check > 24.5 V', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: 'If battery voltage < 24.5 V:', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '12. Ask for a GPU and be ready to a GPU start.', response: null, justification: Justification.Indent2 },
          { type: ChecklistItemType.Challenge, content: '13. GENERATOR\nselector', response: 'MAIN' },
          { type: ChecklistItemType.Challenge, content: '14. MAIN GEN', response: 'Check ON' },
          { type: ChecklistItemType.Challenge, content: '15. O2 CYL\nCLOSED', response: 'Check OFF' },
          { type: ChecklistItemType.PlainText, content: 'If O2 CYL CLOSED is ON:', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '16. Open isolation valve of the oxygen cylinder in R.H. Karman.', response: null, justification: Justification.Indent2 },
          { type: ChecklistItemType.Challenge, content: '17. TEST\npush-button', response: 'Press\nAudio / DE ICE SYSTEM lights / stick shaker' },
          { type: ChecklistItemType.Challenge, content: '18. DUMP switch', response: 'NORM / Guarded' },
          { type: ChecklistItemType.Challenge, content: '19. LANDING GEAR\nlight / CHECK\nDOWN', response: 'Test' },
          { type: ChecklistItemType.Challenge, content: '20. MFD', response: 'Initialize' },
          { type: ChecklistItemType.Challenge, content: '21. Fuel onboard', response: 'Check' },
          { type: ChecklistItemType.Challenge, content: 'a. Quantity', response: 'Check', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: 'b. FUEL TANK\nSELECTOR', response: 'L or R', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '22. Residual ITT', response: 'Check' },
          { type: ChecklistItemType.PlainText, content: 'If residual ITT > 150°C:' },
          { type: ChecklistItemType.Link, content: '23. Perform Motoring procedure', linkTarget: AmplifiedChecklistNames.Motoring, justification: Justification.Indent1 },
          { type: ChecklistItemType.Note, content: 'NOTE: A start up procedure with an engine residual ITT above 150°C may generate\nan ITT exceedance.\nParticular monitoring of ITT will have to be performed during start up to ensure\nto keep the temperature within ITT envelope.' },
          { type: ChecklistItemType.Challenge, content: '24. VOLTS:\nBAT > 24.5 V /\nGPU ≈ 28 V', response: 'Check' },
          { type: ChecklistItemType.Challenge, content: '25. CAS display', response: 'Check' },
          { type: ChecklistItemType.Challenge, content: '26. PARK BRAKE', response: 'Check ON\nLast check before proceeding to engine start' },
          { type: ChecklistItemType.Challenge, content: '27. PARK BRAKE', response: 'Check ON' },
          { type: ChecklistItemType.Note, content: 'NOTE: PARK BRAKE appearance does not indicate that parking brake is set. For\nthat, press on brake pedals before turning brake selector to the right.' },
        ],
      ),
      new TbmChecklist(
        AmplifiedChecklistNames.EngineStart,
        TbmChecklistCategory.Amplified,
        [
          { type: ChecklistItemType.Challenge, content: '1. STROBE switch', response: 'ON' },
          { type: ChecklistItemType.Challenge, content: '2. G3000', response: 'DISPLAY BACKUP\nComposite mode' },
          { type: ChecklistItemType.Note, content: 'NOTE: If there is a loss of MFD during start up sequence, that sequence will be ended\nusing the left PFD in composite mode.' },
          { type: ChecklistItemType.Challenge, content: '3. IGNITION\nswitch', response: 'AUTO' },
          { type: ChecklistItemType.Challenge, content: '4. AUX BP switch', response: 'ON' },
          { type: ChecklistItemType.Challenge, content: '5. AUX BOOST PMP\nON', response: 'Check ON' },
          { type: ChecklistItemType.Challenge, content: '6. FUEL PRESS', response: 'Check OFF' },
          { type: ChecklistItemType.Challenge, content: '7. Propeller\narea', response: 'Clear' },
          { type: ChecklistItemType.Caution, content: 'CAUTION: If 5 seconds after having positioned the STARTER switch in ON\nposition there is no start, interrupt starting attempt using the ABORT\nposition of the STARTER switch.' },
          { type: ChecklistItemType.Caution, content: 'CAUTION: Starter operation is bound by limitations in chapter 2.4 Starter operating\nlimits.' },
          { type: ChecklistItemType.Challenge, content: '8. STARTER\nswitch', response: 'ON\n2 sec then OFF' },
          { type: ChecklistItemType.PlainText, content: 'Simultaneously:' },
          { type: ChecklistItemType.Challenge, content: '9. Timer clock', response: 'Start\nTo check startup acceleration', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '10. STARTER', response: 'Check ON', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '11. MAIN GEN', response: 'Check ON', justification: Justification.Indent1 },
          { type: ChecklistItemType.Caution, content: 'CAUTION: When THROTTLE is positioned on LO-IDLE before having obtained\n13 % of Ng, there is a risk of overtemperature further to an excessive\naccumulation of fuel inside the combustion chamber before ignition.' },
          { type: ChecklistItemType.Note, content: 'NOTE: In case of starting with high residual ITT, an ITT decrease below 150°C (within\nstarter operation limits) may allow to stay within the allowed ITT envelope\nduring startup sequence.' },
          { type: ChecklistItemType.PlainText, content: 'When' },
          { type: ChecklistItemType.PlainText, content: '- Ng about 13 % and,', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: '- ITT below 150°C and,', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: '- time below 20 seconds:', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '12. THROTTLE', response: 'LO-IDLE', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: 'Abort starting procedure if:', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: '- No ignition 10 seconds after having positioned THROTTLE to LO-IDLE,', justification: Justification.Indent2 },
          { type: ChecklistItemType.PlainText, content: '- lights on (max ITT < 870°C for more than 20 seconds, < 1000°C for more than 5 seconds),', justification: Justification.Indent2 },
          { type: ChecklistItemType.PlainText, content: '- Ng < 30 % after 30 seconds of starter use,', justification: Justification.Indent2 },
          { type: ChecklistItemType.PlainText, content: '- Ng < 50 % after 60 seconds of starter use,', justification: Justification.Indent2 },
          { type: ChecklistItemType.Challenge, content: '13. THROTTLE', response: 'CUT OFF', justification: Justification.Indent3 },
          { type: ChecklistItemType.Challenge, content: '14. IGNITION\nswitch', response: 'OFF or AUTO', justification: Justification.Indent3 },
          { type: ChecklistItemType.PlainText, content: 'When ITT < 850°C:', justification: Justification.Indent3 },
          { type: ChecklistItemType.Challenge, content: '15. STARTER\nswitch', response: 'ABORT', justification: Justification.Indent4 },
          { type: ChecklistItemType.PlainText, content: 'When' },
          { type: ChecklistItemType.PlainText, content: '- Ng > 50 % and,', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: '- 1 minute max:', justification: Justification.Indent1 },
          { type: ChecklistItemType.Caution, content: 'CAUTION: If the starter does not go off automatically, disengage it using the\nABORT position of the STARTER switch.' },
          { type: ChecklistItemType.Challenge, content: '16. Starter', response: 'Check OFF\nautomatically', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '17. STARTER', response: 'Check OFF', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '18. Engine\nparameters', response: 'Check\nCheck 54 % ≤ Ng ≤ 58 %, oil pressure and ITT in green sector' },
        ],
      ),
      new TbmChecklist(
        AmplifiedChecklistNames.Motoring,
        TbmChecklistCategory.Amplified,
        [
          { type: ChecklistItemType.PlainText, content: 'To drain fuel accumulated inside the combustion chamber, a motoring procedure is required following an aborted start.' },
          { type: ChecklistItemType.PlainText, content: 'A 15-second dry motoring run is sufficient to clear any fuel pooled in the engine. The fuel is removed in liquid or vapor form, through an airflow intended to dry combustion chamber, turbines and exhaust nozzles.' },
          { type: ChecklistItemType.PlainText, content: 'To improve cooling of the bearing cavities and prevent oil coking after shutdown in high OAT [above 35° C (95° F)] environment, it is recommended to perform a 30-second dry motoring run.' },
          { type: ChecklistItemType.PlainText, content: 'It is possible that no trace of drainage be observed under engine, due to the drainage collector intended to prevent parking area from contamination.' },
          { type: ChecklistItemType.Caution, content: 'CAUTION: After any starting interrupt procedure, wait for engine total shutdown\nand wait at least 30 seconds before initiating a motoring.' },
          { type: ChecklistItemType.PlainText, content: 'Engine controls' },
          { type: ChecklistItemType.Challenge, content: '1. MAN OVRD\ncontrol', response: 'Full backward\n(notched)', justification: Justification.Indent1 },
          { type: ChecklistItemType.Caution, content: 'CAUTION: When the engine is shut down, the THROTTLE must not be moved into\nthe reverse area.' },
          { type: ChecklistItemType.Challenge, content: '2. THROTTLE', response: 'CUT OFF', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '3. IGNITION\nswitch', response: 'OFF' },
          { type: ChecklistItemType.Challenge, content: '4. IGNITION', response: 'Check OFF' },
          { type: ChecklistItemType.PlainText, content: 'Fuel' },
          { type: ChecklistItemType.Challenge, content: '5. FUEL TANK\nSELECTOR', response: 'L or R', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '6. AUX BP switch', response: 'ON', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '7. AUX BOOST PMP\nON', response: 'Check ON', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '8. FUEL PRESS', response: 'Check OFF\nFuel pressure is necessary for lubrication of HP pump.', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '9. Propeller\narea', response: 'Clear' },
          { type: ChecklistItemType.PlainText, content: 'To clear fuel and vapor internally trapped:' },
          { type: ChecklistItemType.Challenge, content: '10. STARTER\nswitch', response: 'ON\n2 sec then OFF', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: 'Simultaneously:', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '11. Timer clock', response: 'Start', justification: Justification.Indent2 },
          { type: ChecklistItemType.Challenge, content: '12. STARTER', response: 'Check ON', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '13. Motor', response: 'For 15 sec. max', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '14. STARTER\nswitch', response: 'ABORT\nThen OFF', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '15. STARTER', response: 'Check OFF', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: 'To cool engine following shutdown in high temperature environment:' },
          { type: ChecklistItemType.Challenge, content: '16. STARTER\nswitch', response: 'ON\n2 sec then OFF', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: 'Simultaneously:', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '17. Timer clock', response: 'Start', justification: Justification.Indent2 },
          { type: ChecklistItemType.Challenge, content: '18. STARTER', response: 'Check ON', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '19. Motor', response: 'For 30 sec. max', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: 'If ignition symptoms occur (ITT increasing):', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '20. IGNITION\nswitch', response: 'Check OFF', justification: Justification.Indent2 },
          { type: ChecklistItemType.Challenge, content: '21. THROTTLE', response: 'Check CUT OFF', justification: Justification.Indent2 },
          { type: ChecklistItemType.PlainText, content: '22 - Continue motoring.', justification: Justification.Indent2 },
          { type: ChecklistItemType.Challenge, content: '23. STARTER\nswitch', response: 'ABORT\nThen OFF', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '24. STARTER', response: 'Check OFF', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: 'FUEL panel' },
          { type: ChecklistItemType.Challenge, content: '25. AUX BP\nswitch', response: 'OFF', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '26. AUX BOOST\nPMP ON', response: 'Check OFF', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '27. FUEL PRESS', response: 'Check ON', justification: Justification.Indent1 },
        ],
      ),
      new TbmChecklist(
        AmplifiedChecklistNames.MotoringFollowedByEngineStart,
        TbmChecklistCategory.Amplified,
        [
          { type: ChecklistItemType.PlainText, content: 'Amplified procedures stated in starting engine sequences using airplane power or with GPU are also to be applied to hereunder procedure.' },
          { type: ChecklistItemType.PlainText, content: 'Within starter operating limits (continuous max. 1 minute), it is possible to initiate a starting procedure from a motoring procedure.' },
          { type: ChecklistItemType.PlainText, content: 'This procedure will conserve the battery by taking advantage of first Ng acceleration.' },
          { type: ChecklistItemType.PlainText, content: 'Engine controls' },
          { type: ChecklistItemType.Challenge, content: '1. MAN OVRD\ncontrol', response: 'Full backward\n(notched)', justification: Justification.Indent1 },
          { type: ChecklistItemType.Caution, content: 'CAUTION: When the engine is shut down, the THROTTLE must not be moved into\nthe reverse area.' },
          { type: ChecklistItemType.Challenge, content: '2. THROTTLE', response: 'CUT OFF', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '3. IGNITION\nswitch', response: 'OFF' },
          { type: ChecklistItemType.Challenge, content: '4. IGNITION', response: 'Check OFF' },
          { type: ChecklistItemType.PlainText, content: 'Fuel' },
          { type: ChecklistItemType.Challenge, content: '5. FUEL TANK\nSELECTOR', response: 'L or R', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '6. AUX BP switch', response: 'ON', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '7. AUX BOOST PMP\nON', response: 'Check ON', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '8. FUEL PRESS', response: 'Check OFF\nFuel pressure is necessary for lubrication of HP pump.', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '9. Propeller\narea', response: 'Clear' },
          { type: ChecklistItemType.Challenge, content: '10. STARTER\nswitch', response: 'ON\n2 sec then OFF' },
          { type: ChecklistItemType.PlainText, content: 'Simultaneously:' },
          { type: ChecklistItemType.Challenge, content: '11. Timer clock', response: 'Start', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '12. STARTER', response: 'Check ON' },
          { type: ChecklistItemType.Challenge, content: '13. Motor', response: 'For 30 sec. max' },
          { type: ChecklistItemType.PlainText, content: 'After 20 seconds and if ITT < 150°C:' },
          { type: ChecklistItemType.Challenge, content: '14. IGNITION\nswitch', response: 'AUTO', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '15. Ng', response: 'Check > 13 %', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '16. THROTTLE', response: 'LO-IDLE', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: 'Monitor increase of:', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '17. ITT', response: 'max.: < 870°C\nfor 20 sec max.\n< 1000°C for 5 sec max.', justification: Justification.Indent2 },
          { type: ChecklistItemType.PlainText, content: '18 - Ng', justification: Justification.Indent2 },
          { type: ChecklistItemType.PlainText, content: '19 - Oil pressure', justification: Justification.Indent2 },
          { type: ChecklistItemType.Challenge, content: '20. OIL PRESS', response: 'Check OFF', justification: Justification.Indent2 },
          { type: ChecklistItemType.PlainText, content: 'When Ng > 50 %:' },
          { type: ChecklistItemType.Caution, content: 'CAUTION: If the starter does not go off automatically, disengage it using the\nABORT position of the STARTER switch.' },
          { type: ChecklistItemType.Challenge, content: '21. Starter', response: 'Check OFF\nautomatically', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '22. STARTER', response: 'Check OFF', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '23. Engine\nparameters', response: 'Check\nCheck 54 % ≤ Ng ≤ 58 %, oil pressure and ITT in green sector' },
          { type: ChecklistItemType.PlainText, content: 'Fuel panel' },
          { type: ChecklistItemType.Challenge, content: '24. AUX BP\nswitch', response: 'AUTO', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '25. AUX BOOST\nPMP ON', response: 'Check OFF', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: 'Electric power' },
          { type: ChecklistItemType.Challenge, content: '26. MAIN GEN', response: 'Check OFF\nReset if necessary', justification: Justification.Indent1 },
          { type: ChecklistItemType.Note, content: 'NOTE: MAIN GEN normally goes off as soon as STARTER goes off.' },
          { type: ChecklistItemType.PlainText, content: 'If MAIN GEN does not go off:', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '27. Ng', response: 'Increase to more\nthan 70 %\nTo start main generator', justification: Justification.Indent2 },
          { type: ChecklistItemType.Challenge, content: '28. Generator\nand battery AMPS', response: 'Check charge\nOn EIS of MFD', justification: Justification.Indent1 },
          { type: ChecklistItemType.Challenge, content: '29. Battery and\nESS. bus VOLTS', response: 'Check voltage ≈ 28 Volts\nOn EIS of MFD', justification: Justification.Indent1 },
        ],
      ),
      new TbmChecklist(
        AmplifiedChecklistNames.AfterEngineStartWithGPU,
        TbmChecklistCategory.Amplified,
        [
          { type: ChecklistItemType.Challenge, content: '1. SOURCE\nselector', response: 'BATT' },
          { type: ChecklistItemType.Challenge, content: '2. Electrical\nnetwork', response: 'Check' },
          { type: ChecklistItemType.Challenge, content: '3. GPU', response: 'Disconnect' },
          { type: ChecklistItemType.PlainText, content: 'Performed by ground personnel' },
          { type: ChecklistItemType.Challenge, content: '4. GPU DOOR', response: 'Check OFF' },
          { type: ChecklistItemType.Challenge, content: '5. GENERATOR\nselector', response: 'MAIN' },
          { type: ChecklistItemType.Challenge, content: '6. MAIN GEN', response: 'Check OFF' },
          { type: ChecklistItemType.Note, content: 'NOTE: MAIN GEN normally goes off as soon as STARTER goes off.' },
          { type: ChecklistItemType.PlainText, content: 'If MAIN GEN does not go off:' },
          { type: ChecklistItemType.Challenge, content: '7. Ng', response: 'Increase over 70\n%', justification: Justification.Indent1 },
          { type: ChecklistItemType.PlainText, content: 'To start main generator' },
          { type: ChecklistItemType.Challenge, content: '8. Generator and\nbattery AMPS', response: 'Check charge' },
          { type: ChecklistItemType.PlainText, content: 'On EIS of MFD' },
          { type: ChecklistItemType.Challenge, content: '9. Battery and\nESS. bus VOLTS', response: 'Check voltage ≈\n28 Volts' },
          { type: ChecklistItemType.PlainText, content: 'On EIS of MFD' },
          { type: ChecklistItemType.Challenge, content: '10. CAS display', response: 'Check' },
          { type: ChecklistItemType.Challenge, content: '11. A/C switch', response: 'As required' },
          { type: ChecklistItemType.Challenge, content: '12. BLEED switch', response: 'AUTO or MAX DIFF' },
          { type: ChecklistItemType.PlainText, content: 'When ground personnel is cleared from propeller area:' },
          { type: ChecklistItemType.Link, content: '13. Perform After engine start procedure', linkTarget: AmplifiedChecklistNames.AfterEngineStart, justification: Justification.Indent1 },
        ],
      ),
    ];
  }
}