name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create zips
        run: |
          for dir in dist/*; do
            zip -r "${dir}.zip" "$dir"
          done
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
