name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
      - name: Check types
        run: npx tsc --noEmit
      - name: Build
        run: npm run build
      - name: Create zips
        run: |
          Get-ChildItem "dist" | 
          ForEach-Object { Compress-Archive -path "dist/$($_.Name)" -destinationPath "$($_.Name).zip"}
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.zip
